### ISSUE TITLE
dbo.sp_sql_perf_mon_retention not Found on the Tempd DB after the instalation 

### ISSUE THREAD

**Issue by djadcareer** [marcingminski/sqlwatch#1]
i have install the sollution when i try to run the two jobs manually , DBA-PERF-LOGGER succeeded and the  DBA-PERF-LOGGER-RETENTION failed with message
Message
Executed as user: NT AUTHORITY\NETWORK SERVICE. Could not find stored procedure 'dbo.sp_sql_perf_mon_retention'. [SQLSTATE 42000] (Error 2812).  The step failed.

**Comment by marcingminski** [comment]
Hi, thanks for using this! I have fixed it now, please re-run setup.sql and it will create the missing procedure.
