### ISSUE TITLE
Add ability to send SQL Monitoring data to Azure Monitor Public API

### ISSUE THREAD

**Issue by scautomation** [marcingminski/sqlwatch#102]
Azure Monitor Log Analytics workspaces have a public API to send custom json logs to.

Currently we can monitor OS performance health, and windows services including SQL services and sql event logs. But we cannot monitor SQL DB space, DB performance, queries etc.

If we can send those logs to log analytics we can have end to end monitoring with SQL and provide that gap for IaaS VMs and on-prem VMs inside Azure Monitor.

**Comment by marcingminski** [comment]
This may be coming soon :)

**Comment by marcingminski** [comment]
This has been implemented in the most recent 2.2 beta release https://github.com/marcingminski/sqlwatch/releases/tag/2.2.7316.33346. Please take a look, feedback welcome.
