### ISSUE TITLE
Unable to schedule refresh in Power BI service 

### ISSUE THREAD

**Issue by spencerhammond002** [marcingminski/sqlwatch#103]
![image](https://user-images.githubusercontent.com/48012730/67025627-a2816e80-f106-11e9-9503-fa2a362762e4.png)

If no current solutions is present. Do you have an ideas on how to setup a scheduled/automated refresh ?

Currently using the latest version of SQLWATCH beta 6

**Comment by marcingminski** [comment]
Hi, I don’t think this will ever work. Functions are used as we have to pass parameters for the time slice delta calculations. For example, to show 24 hours of hourly delta snapshots we only have to pull 24 rows per metric, even though collections happen every minute. Without it, we’d have to pull 1440 rows. It means all data within the period would have to be pulled from Sql into PBI and all calculations done in the service which would put some load on the db and PBI. Having said that, I will play around with the service and see how it can be achieved without building a full blown DW.

**Comment by spencerhammond002** [comment]
Thank you for the clarification and thank you for SQLWATCH!

Your feedback is highly appreciated.

Regards,

**Comment by marcingminski** [comment]
Hi, thank you for the kind words. 
I think I have some ideas that I may release soon in 2.1. 
SQLWATCH always meant to be flexible and deliver unified performance data to work with different dashboards, not only PowerBI. As part of that, I have been slowly moving some of the logic from PowerBI to the database and started exposing performance data through stored procedures. I can try create set of views with delta calculated for each collection i.e. every minute, it will produce much more granularity and likely impact performance but will have to see how it behaves. With dedicated central repository and PBI Service this may not be a big problem. At least we may benefit from the query folding in PBI.

**Comment by marcingminski** [comment]
hi, can you please try 2.1, you should be able to schedule it now.

**Comment by spencerhammond002** [comment]
Thank you for your response!

Your update is sincerely appreciated.

Regards,
