### ISSUE TITLE
SQLWATCH.dacpac not exist in sqlwatch-2_0.zip

### ISSUE THREAD

**Issue by cpesqueran** [marcingminski/sqlwatch#105]
Hi all,

A need install with SSMS SQLWATCH 2.0 but SQLWATCH.dacpac not exist in sqlwatch-2_0.zip

Best regards.

**Comment by marcingminski** [comment]
Hi, thank you for this. You may have noticed that I backed out 2.0 release due to few bugs, including cartesian product which caused exponential growth of index stats and histogram. Can you please try 2.1 instead?

**Comment by cpesqueran** [comment]
Thank you! we will try it.
