### ISSUE TITLE
Carthesian product in usp_sqlwatch_logger_index_usage_stats

### ISSUE THREAD

**Issue by SanSalpeter** [marcingminski/sqlwatch#106]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**
stored procedure gives to much rows as result.

**To Reproduce**
1. Go to..
2. Click this..

**Expected behavior**
expect not more rows than indexes in sys.indexes table.
Correction joins on sqlwatch_meta_index
New:
			inner join [dbo].[sqlwatch_meta_index] mi
				on mi.sql_instance = mdb.sql_instance
				and mi.sqlwatch_database_id = mdb.sqlwatch_database_id
				and mi.sqlwatch_table_id = mt.sqlwatch_table_id
                                and mi.index_id = ixus.index_id
Old:
			--inner join [dbo].[sqlwatch_meta_index] mi
			--	on mi.sql_instance = mdb.sql_instance
			--	and mi.sqlwatch_database_id = mi.sqlwatch_database_id
			--	and mi.sqlwatch_table_id = mi.sqlwatch_table_id

**Screenshots**

**Windows Server (please complete the following information):**
Windows NT 6.3 <X64>

**SQL Server (please complete the following information):**
Microsoft SQL Server 2012 (SP4-OD) (KB4091266) - 11.0.7469.6 (X64)   Feb 28 2018 17:47:20   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) 
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
Microsoft SQL Server Management Studio						14.0.17224.0
Microsoft Analysis Services Client Tools						14.0.1016.244
Microsoft Data Access Components (MDAC)						10.0.14393.0
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.14393.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.14393
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 2.0.0.0
 
**Additional context**

**Comment by marcingminski** [comment]
Hi, thank you for this. You may have noticed that I backed out 2.0 release due to few bugs, including cartesian product which caused exponential growth of index stats and histogram. Can you please try 2.1 instead?
