### ISSUE TITLE
Stored procedure usp_sqlwatch_logger_index_histogram trips over availability group databases.

### ISSUE THREAD

**Issue by SanSalpeter** [marcingminski/sqlwatch#108]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**
Stored procedure usp_sqlwatch_logger_index_histogram trips over availability group databases.

**To Reproduce**
1. Go to..
2. Click this..

**Expected behavior**
Skip unavailable databases in logging index histogram data.
Additional code in cursor:

declare c_index cursor for
select md.[database_name], table_name=mt.table_name , index_name = mi.index_name, mi.index_id, mi.sqlwatch_database_id, mi.sqlwatch_table_id, mi.sqlwatch_index_id
from [dbo].[sqlwatch_meta_index] mi
	inner join [dbo].[sqlwatch_meta_table] mt
		on mt.sqlwatch_database_id = mi.sqlwatch_database_id
		and mt.sql_instance = mi.sql_instance
		and mt.sqlwatch_table_id = mi.sqlwatch_table_id
	inner join [dbo].[sqlwatch_meta_database] md
		on md.sql_instance = mi.sql_instance
		and md.sqlwatch_database_id = mi.sqlwatch_database_id
	inner join sys.databases sdb
		on sdb.name = md.database_name collate database_default
		and sdb.create_date = md.database_create_date
```
--begin hadr aware and db online 
   LEFT JOIN sys.dm_hadr_availability_replica_states hars ON sdb.replica_id = hars.replica_id
   LEFT JOIN sys.availability_replicas ar ON sdb.replica_id = ar.replica_id
--end hadr aware and db online ? 
```
where mi.[sql_instance] = @@SERVERNAME
and mi.date_deleted is null
```
--begin hadr aware and db online ?
AND database_id > 4 
AND state_desc = 'ONLINE'
AND (  (hars.role_desc = 'PRIMARY' OR hars.role_desc IS NULL)
      OR (hars.role_desc = 'SECONDARYY' AND ar.secondary_role_allow_connections_desc IN ('READ_ONLY','ALL')))
and [name] not like '%ReportingServer%'
--end hadr aware and db online ? 
```
**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: Windows NT 6.3 <X64>

**SQL Server (please complete the following information):**
 - SQL Version: Microsoft SQL Server 2012 (SP4-OD) (KB4091266) - 11.0.7469.6 (X64)   Feb 28 2018 17:47:20   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) 
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
Microsoft SQL Server Management Studio						14.0.17224.0
Microsoft Analysis Services Client Tools						14.0.1016.244
Microsoft Data Access Components (MDAC)						10.0.14393.0
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.14393.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.14393
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 2.0.0.0
 
**Additional context**

**Comment by marcingminski** [comment]
Thank you , I will address this in the next release
