### ISSUE TITLE
Cartesian product in stored procedure usp_sqlwatch_logger_index_usage_stats

### ISSUE THREAD

**Issue by SanSalpeter** [marcingminski/sqlwatch#110]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**

Cartesian product in stored procedure usp_sqlwatch_logger_index_usage_stats in the join for sqlwatch_meta_index:
```
		inner join [dbo].[sqlwatch_meta_index] mi
			on mi.sql_instance = @@SERVERNAME
			and mi.sqlwatch_database_id = mi.sqlwatch_database_id -- selfreferencing
			and mi.sqlwatch_table_id = mi.sqlwatch_table_id -- selfreferencing
		inner join [dbo].[sqlwatch_meta_database] mdb
			on mdb.sqlwatch_database_id = mi.sqlwatch_database_id
			and mdb.database_name = dbs.name collate database_default
			and mdb.database_create_date = dbs.create_date
```

**To Reproduce**
1. Go to..
2. Click this..

**Expected behavior**

Join should via database --> table --> index

```
			inner join [dbo].[sqlwatch_meta_database] mdb
				on mdb.sql_instance = ''' + @@SERVERNAME + '''
				and mdb.database_name = dbs.name collate database_default
				and mdb.database_create_date = dbs.create_date

			inner join [dbo].[sqlwatch_meta_table] mt
				on mt.sql_instance = mdb.sql_instance
				and mt.sqlwatch_database_id = mdb.sqlwatch_database_id
				and mt.table_name = s.name + ''.'' + t.name collate database_default

			inner join [dbo].[sqlwatch_meta_index] mi
				on mi.sql_instance = mdb.sql_instance
				and mi.sqlwatch_database_id = mdb.sqlwatch_database_id
				and mi.sqlwatch_table_id = mt.sqlwatch_table_id
                	and mi.index_id = ixus.index_id
```

Screenshots

Windows Server (please complete the following information):
Windows NT 6.3

SQL Server (please complete the following information):
Microsoft SQL Server 2012 (SP4-OD) (KB4091266) - 11.0.7469.6 (X64) Feb 28 2018 17:47:20 Copyright (c) Microsoft Corporation Enterprise Edition (64-bit) on Windows NT 6.3 (Build 9600: )

SQL Server Management Studio (SSMS -> about -> copy info):
Microsoft SQL Server Management Studio 14.0.17224.0
Microsoft Analysis Services Client Tools 14.0.1016.244
Microsoft Data Access Components (MDAC) 10.0.14393.0
Microsoft MSXML 3.0 6.0
Microsoft Internet Explorer 9.11.14393.0
Microsoft .NET Framework 4.0.30319.42000
Operating System 6.3.14393

SQLWATCH version (from DACPAC or from sysinstances)

    2.2 beta

Additional context
 
**Additional context**

**Comment by marcingminski** [comment]
Hi, could you please check if this is related? I remeber fixing this https://github.com/marcingminski/sqlwatch/commit/f165e7153e4495fbd2de61dccd97a407a4078d40

Thanks.

**Comment by SanSalpeter** [comment]
Hi Marcin,
It's related. But sqlwatch_meta_index still holds a self reference. I suggest using the proposed join using the hierarchy through database --> table --> index

**Comment by marcingminski** [comment]
Ah, I see what you mean. I thought I had fixed that. Apologies.

**Comment by SanSalpeter** [comment]
No problem. Happy to assist. :+1:
