### ISSUE TITLE
sqlwatch_logger_xes_long_queries issue in datatypes and a misspelling on a column here too

### ISSUE THREAD

**Issue by cperez120** [marcingminski/sqlwatch#111]
Steps to reproduce just install SQLWatch using dbatools using the newest version available there. The stored procedure "usp_sqlwatch_logger_xes_long_queries" would fail under the job "SQLWATCH-LOGGER-PERFORMANCE". I manually edited 2 smallint dataypes to bigint you will see being pointed to in the bottom screenshot and that ended up fixing the job.

![image](https://user-images.githubusercontent.com/57533711/68485383-d54dec80-0204-11ea-85c7-dab31341a924.png)

Picture of misspelling all the code on the back end and references are the same so this is just aesthetics.

![image](https://user-images.githubusercontent.com/57533711/68485220-7b4d2700-0204-11ea-95eb-aba310af15da.png)

"activity_seqeuence_xfer" to "activity_sequence_xfer"

**Comment by marcingminski** [comment]
Thank you. I’ll get that fixed in the next release.
