### ISSUE TITLE
Error with dbo.vw_sqlwatch_report_dim_performance_counters_poster

### ISSUE THREAD

**Issue by Sqlrepairman** [marcingminski/sqlwatch#114]
Trying to setup sqlwatch 2.1
Install-DbaSqlWatch which succeeds 
However I cannot get the powerbi desktop to work
looking at the queries I see the following

Expression.Error: The key didn't match any rows in the table.
Details:
    Key=
        Schema=dbo
        Item=vw_sqlwatch_report_dim_performance_counters_poster
    Table=[Table]

And I cannot find vw_sqlwatch_report_dim_performance_counters_poster in the sqlwatch database

**Comment by marcingminski** [comment]
Hi, the query is actually not enabled for load so should not be causing any issues. You can either delete it or keep disabled.

**Comment by Sqlrepairman** [comment]
Sorry Marcin 

I have just found that out on further investigation.

I still cannot get the PowerBIdesktop to work. It seems to get the data OK but will not render.

I have installed R and the 2 modules RcolorBrewer and rpart.plot

I have included the error output from PowerBI in case it is a common issue

[sqlwatch01.log](https://github.com/marcingminski/sqlwatch/files/3832105/sqlwatch01.log)


Thanks

Steve

**Comment by marcingminski** [comment]
Neither R nor any additional modules are needed. First make sure you have the latest PBI Desktop installed and privacy options disabled. Apart from setting parameters to connect to your SQLWATCH database there is no configuration required.

**Comment by DiHo78** [comment]
Gotcha.  I have struggled a bit with the PBI Desktop. Once I edited the privacy setting the data models were loaded.
Maybe you add this info to the documentation, e.g. in the section Installation->Client Components->Power BI Desktop ?

Regards
Dirk

**Comment by marcingminski** [comment]
Hi, glad you sorted it. I thought this was documented but if it isn’t I’ll update docs. Thanks!

**Comment by DiHo78** [comment]
Well... maybe I did not look close enough.  I am more the try and error guy  ;-)
Will take a closer look at this solution (which is already awesome in my eyes) tomorrow.

**Comment by marcingminski** [comment]
Looks like I wrote a blog post but never added it to the documentation. I think that's because it was a problem with the beta that I was meant to fix in 2.x but it cannot actually be fixed, it just how PBI works. It seems to not like the fundamental database feature - joins and as soon as there is a join, it complains about potential privacy violation.

**Comment by marcingminski** [comment]
https://docs.sqlwatch.io/v/2.2/known-issues-and-limitations/power-bi-load-errors
