### ISSUE TITLE
Missing Index only on SQLWATCH

### ISSUE THREAD

**Issue by FrenchDataWizard** [marcingminski/sqlwatch#115]
Testing v2.1

[SQLWATCH].[dbo].[sqlwatch_meta_index_missing] only contains indexes from SQLWATCH.
This is due to the use of sys.tables in [dbo].[usp_sqlwatch_internal_add_index_missing].

A loop on all tables to get that list, like it is done on other procedures that populate table information would solve this issue.
At the moment, we get all indexes and the join on tables only of the active DB restricts this.

Still present in 2.2

**Comment by marcingminski** [comment]
Yes, you are right. Thank you. I am working on 2.2 will get that fixed soon.
