### ISSUE TITLE
Missing index report

### ISSUE THREAD

**Issue by marcingminski** [marcingminski/sqlwatch#12]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Likely a daily or weekly snapshot of what SQL things are missing indexes, this will allow to track how this changes if at all.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ColinDouglas92** [comment]
Has any work been started here? This one sounds like a good starter issue to snag for my first contribution 😄

**Comment by marcingminski** [comment]
I got that in the pipeline but go ahead and give it a go. My approach is more or less the below:

```
select  
gs.last_user_seek,
gs.unique_compiles, 
gs.user_seeks, 
gs.user_scans, 
gs.avg_total_user_cost, 
gs.avg_user_impact, 
gs.user_seeks * gs.avg_total_user_cost * (gs.avg_user_impact * 0.01) AS benefit
from sys.dm_db_missing_index_groups g 
inner join sys.dm_db_missing_index_group_stats gs ON gs.group_handle = g.index_group_handle 
inner join sys.dm_db_missing_index_details d ON g.index_handle = d.index_handle
```

**Comment by ColinDouglas92** [comment]
Thanks for the snippet. I'll start tackling this soon. Thanks!

**Comment by ColinDouglas92** [comment]
@marcingminski I have the bulk of this finished; I just have a design question. Should we implement the missing index collection code into the existing sp_sql_perf_mon_logger/cleanup jobs using something similar to the logic below to increase snapshot interval time to daily/weekly:

```
declare @micollectioninterval int = 1440  --Minutes (1440 min = 1 day)

......
-------------------------------------------
-- Missing index collection
------------------------------------------

if (DATEDIFF(MINUTE,@date_snapshot_previous,@date_snapshot_current) >= @micollectioninterval)
begin
    print ' run missing index collection'
end
```

Or would you prefer that the missing index collection was it's own SP and had it's own Agent job so the user can disable or increase/decrease the collection time schedule. I see pro's / con's for both options so thought I would get your input. Thanks!

**Comment by marcingminski** [comment]
Great, thank you. Have a look on our Slack channel I have been playing with different visualisation for index report. There’s been few ideas how take this further. I prefer individual job as it’s transaorent and easy and with its own snapshot ID peole can set their own schedules and retention as they wish. I can sort out execution don’t worry about it.
