### ISSUE TITLE
Possibility to exclude some DBs from collection and reporting

### ISSUE THREAD

**Issue by FrenchDataWizard** [marcingminski/sqlwatch#121]
I don't know if this would be helpfull to everybody, but excluding Microsoft Components databases for MSSQL, and maybe SQLWatch itself would be interesting as they can generate a lot of noise.
I need to exclude DQS, MDM, Polybase, ReportServer, SQLWatch and SSISDB to better monitor the databases I am in real charge of.

My idea:
Create a _dbo.sqlwatch_config_exclude_database_ with 2 columns: instance, database
that would be used in _usp_sqlwatch_internal_add_database_ to exclude them during the insertion in the @database table.

**Comment by marcingminski** [comment]
Good idea. In 2.2 there is a new view `[dbo].[vw_sqlwatch_sys_databases]` that was introduced on the back of https://github.com/marcingminski/sqlwatch/issues/108, and it already excludes `ReportServer`. A quick solution for you would be to edit this view (although not 100% code uses it yet) before I implement something more permanent.

**Comment by FrenchDataWizard** [comment]
Yes, already modified this view as a "quick fix" for us :)
Maybe getting the data and only excluding it at restitution through the view would be smarter indeed. the "pollution" is mostly for indexes as we won't dare modify those technical DBs.

**Comment by marcingminski** [comment]
Yeah, I need to think about the best approach. Not getting the data in the first place would save storage space. No point getting something that we will not use.

**Comment by marcingminski** [comment]
I have pushed a couple of commits that should help handling exclusion. As per your suggestion, there is a new table `[dbo].[sqlwatch_config_logger_exclude_database]` that contains exclusion pattern `%ReportServer%` and the id of the snapshots that should be excluded. So if you want to exclude missing index collection from any `Report Server`, `master` and `msdb` databases you'd put something like this:

![image](https://user-images.githubusercontent.com/8288333/69502246-12a0c280-0f05-11ea-9031-cf222f23bb1a.png)

This way we can still collect database growth, performance and so on but exclude stuff that we cannot do anything about, i.e. indexes.

If we want to exclude database completely, we would have to put all snapshot ids there, for each database or each pattern.

Note that this will still collect databases in some meta tables to satisfy relationships and dimensions.

If you could test this it would be great.

Thank you
