### ISSUE TITLE
dedicated history cleanup for SQLWatch Jobs?

### ISSUE THREAD

**Issue by DiHo78** [marcingminski/sqlwatch#124]
for discussion - enhancement 

Not really a problem but again an "edge case".

I have a system where I have to keep the agent job history for a longer period of time (about 15 months).
If the SQLWatch Agent Jobs run with the default schedules, then I'll get round about 35.000 rows per day. That would result in nearly 16 million of rows just for the SQLWatch Jobs.

So, do you think it makes sense to implement a dedicated procedure and job for cleaning job history with focus on SQLWatch Jobs?

I have already created something simple which fits my needs:
[https://github.com/DiHo78/sqlwatch/blob/2_2_beta_dev/SQLWATCHDB/dbo/Procedures/usp_sqlwatch_internal_purge_jobhistory.sql](url)

**Comment by marcingminski** [comment]
My question is why you have to store this history, if for regulatory, sox or any other compliance reasons then you have to keep all jobs as when you become selective you open up holes in the policy so it does not make sense to allow to delete some history. Perhaps a better option would be to send this to a log management software, splunk, graylog etc. However, if you are allowed to delete individual jobs that should be applied at the server, i.e. you should have a "global process" that handles these exceptions, and not at the individual application level. 

Having said all that, I will be happy to accept it as a PR but without agent job, or optional agent job, or agent job left disabled, left for individuals to decide and create as they wish.

**Comment by DiHo78** [comment]
Ha, good catch.
It'll make more sense to take a look at a log monitoring software. 

And yes, it is for compliance reason so that auditors have the information available that a special job runs without any problems or not.
