### ISSUE TITLE
Missing Double quote in SQLWATCH-INTERNAL-ACTIONS job step

### ISSUE THREAD

**Issue by ParadoxMachine** [marcingminski/sqlwatch#131]
Hi,

Missing a double quote powershell script in the Process Actions job step of the SQLWATCH-INTERNAL-ACTIONS job. Corrected version:

$output = "x"
while ($output -ne $null) { 
	$output = Invoke-SqlCmd -ServerInstance "D92108R5\CENTRAL" -Database SQLWATCH -MaxCharLength 2147483647 -Query "set xact_abort on
	begin tran
		;with cte_get_message as (
		  select top 1 *
		  from [dbo].[sqlwatch_meta_action_queue]
		  where [exec_status] is null
		  order by [time_queued]
		)
		update cte_get_message
			set [exec_status] = 'PROCESSING'
			output deleted.[action_exec], deleted.[action_exec_type], deleted.[queue_item_id]
	commit tran"

	$status = ""
	$queue_item_id = $output.queue_item_id
    $operation = ""
	$ErrorOutput = ""
	
	if ( $output -ne $null) {
		if ( $output.action_exec_type -eq "T-SQL" ) {
			try {
				Invoke-SqlCmd -ServerInstance "D92108R5\CENTRAL" -Database SQLWATCH -ErrorAction "Stop" -Query $output.action_exec -MaxCharLength 2147483647
			}
			catch {
				$ErrorOutput = $error[0] -replace "'", "''"
			}
		}

		if ( $output.action_exec_type -eq "PowerShell" ) {
			try {
				$action_exec = $output.action_exec
				Invoke-Expression $output.action_exec
			}
			catch {
				$ErrorOutput = $_.Exception.Message
				}
		}

       if ($ErrorOutput -ne "") {
 			$query = "update [dbo].[sqlwatch_meta_action_queue] set [exec_status] = 'FAILED' where queue_item_id = $queue_item_id;
					exec [dbo].[usp_sqlwatch_internal_log]
							@procces_name = 'PowerShell',
							@process_stage = '6DC68414-915F-4B52-91B6-4D0B6018243B',
							@process_message = '$ErrorOutput',
							@process_message_type = 'ERROR'"
        } else {
			$query = "update [dbo].[sqlwatch_meta_action_queue] set [exec_status] = 'OK' where queue_item_id = $queue_item_id"
        }
		Invoke-SqlCmd -ServerInstance "D92108R5\CENTRAL" -Database SQLWATCH -Query $query
		Invoke-SqlCmd -ServerInstance "D92108R5\CENTRAL" -Database SQLWATCH -Query "delete from [dbo].[sqlwatch_meta_action_queue] [exec_status] = 'OK' and [time_queued] > dateadd(day,-1,sysdatetime())"
	}
}

**Comment by marcingminski** [comment]
Duplicate https://github.com/marcingminski/sqlwatch/issues/126
Thanks
