### ISSUE TITLE
Duplicate database error if tempdb recreated (e.g. via restart)

### ISSUE THREAD

**Issue by ParadoxMachine** [marcingminski/sqlwatch#132]
**Apologies if this is a duplicate but could not find similar issue.**

**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

Yes - nothing found for "tempdb"

**Describe the bug**

Error due to multiple entries for tempdb in dbo.sqlwatch_meta_database.
Currently PK for table dbo.sqlwatch_meta_database is sql_instance and sqlwatch_database_id, however sqlwatch_database_id is an identity column, so will always be unique 

Refreshing PowerBI report data throws the following error:
_"Column 'database_name' in Table 'Dim Database' contains a duplicate value 'tempdb' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table."_

**To Reproduce**
1. Restart SQL Server, so tempdb is recreated with a new create date
2. run dbo.usp_sqlwatch_internal_add_database
3. Duplicate entries for tempdb should now be in dbo.sqlwatch_meta_database
4. Refresh report data

**Expected behavior**
A new entry should not be created for a given DB

**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: [e.g. Windows 2016 Standard

**SQL Server (please complete the following information):**
- SQL Version: SQL Server 2016 SP2 - CU 11
- SQL Edition: Enterprise
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 1.3.6967.36446 
 
**Additional context**
Issue is due to table structure and the procedures merge statement for creating new entries 

Recommend:
1. Adding dbid from sys.sysdatabases to the dbo.sqlwatch_meta_database as [sql_instance_dbid] 
2. Add a unique constraint on  sql_instance, database_name, and [sql_instance_dbid]
3. Change dbo.usp_sqlwatch_internal_add_database to match on [sql_instance], [database_name], [sql_instance_dbid]

This way existing foreign keys are not modified and the duplicated are avoided

**Comment by marcingminski** [comment]
Hi, The mentioned procedure does not exist in 1.3, can you double check which version you have?

Are you experiencing errors in PBI only, or in the database too? The primary key for database is `[sql_instance], [sqlwatch_database_id]` and there is a unique constraint to not allow duplicate databases: `[sql_instance], [database_name], [database_create_date]`

In the PBI itself, a new composite key is generated for each record that includes server name and the database id. This is so we can track history of deleted dbs, including tempdb, but this will never be a duplicate per se.
![image](https://user-images.githubusercontent.com/8288333/71771077-78816080-2f2d-11ea-8930-a865a4f33e26.png)

**Comment by marcingminski** [comment]
Hi, I am going to close this as I believe the issue does not exist in the most recent version. However, if you do experience it please get in touch on our slack channel so I can understand it better. Thanks

**Comment by ghost** [comment]
This is still occurring in 2.2.7367.29602.
It seems that `usp_sqlwatch_internal_add_database` has made a return and is joining on the create_date column of `vw_sqlwatch_sys_databases`, as the create_date value is not persistent for tempdb and will always be the last boot time of the instance.

**Comment by marcingminski** [comment]
Can you please show an example? Logging multiple instances of tempdb is per design but the original issue I believe was about failing to filter them out. 

This will be absolutely fine in `[dbo].[sqlwatch_meta_database]`
![image](https://user-images.githubusercontent.com/8288333/76092420-45079480-5fb7-11ea-9f6b-ac10bbecd8c7.png)

but the view `[dbo].[vw_sqlwatch_report_dim_database]` filters it out on the `is_current=1` flag:
` FROM [SQLWATCH].[dbo].[vw_sqlwatch_report_dim_database]
  where is_current = 1`
![image](https://user-images.githubusercontent.com/8288333/76092514-6c5e6180-5fb7-11ea-8a69-cd95f051c880.png)

**Comment by ghost** [comment]
Apologies, I believed the multiple tempdb entries were causing primary key violations elsewhere in my environment, but I discovered this was due to an unrelated issue. The deduplication filters are all working as intended.
