### ISSUE TITLE
Missing procedures in latest beta release

### ISSUE THREAD

**Issue by dennisa95** [marcingminski/sqlwatch#133]
I used the SSMS method to install SQLWATCH v2.2 beta 2.2.7275.26487.  I created the databases and all the jobs.  However, there are several that are failing to run mainly due to missing stored procedures.  I did have an older version installed so I dropped that database before deploying this one.  SLQWATCH-INTERNAL-ACTIONS had a few typos in the PS script.  I fixed those.
SQLWATCH-INTERNAL-CONFIG, RETENTION, SQLWATCH-LOGGER-DISK-UTILIZATION and PERFORMANCE are all missing stored procedures:
dbo.sp_sql_perf_mon_add_database
dbo.sp_sql_perf_mon_retention
dbo.usp_logger_disk_utilisation
dbo.sp_sql_perf_mon_logger

Can you help me fix these?  Where do I get those store procedures?

**Comment by marcingminski** [comment]
Hi, you will also need to re-recreate jobs. the old jobs have reference to old procedures. We do not drop or modify jobs in anyway during upgrades as users could have modified schedules etc.
You can run `[dbo].[usp_sqlwatch_config_set_default_agent_jobs] @remove_existing = 1`

If you are coming from a really old version some jobs were renamed, it may be best if you drop all of them manually first.

**Comment by dennisa95** [comment]
Thanks for the command to fix the job issue.  Just FYI this job : SQLWATCH-INTERNAL-ACTIONS still needs to be fixed in the code.  I've included the corrected code below
$output = "x"
while ($output -ne $null) { 
	$output = Invoke-SqlCmd -ServerInstance "AUSLYNCDBSAF03" -Database SQLWATCH -MaxCharLength 2147483647 -Query "set xact_abort on
	begin tran
		;with cte_get_message as (
		  select top 1 *
		  from [dbo].[sqlwatch_meta_action_queue]
		  where [exec_status] is null
		  order by [time_queued]
		)
		update cte_get_message
			set [exec_status] = 'PROCESSING'
			output deleted.[action_exec], deleted.[action_exec_type], deleted.[queue_item_id]
	commit tran"

	$status = ""
	$queue_item_id = $output.queue_item_id
    $operation = ""
	$ErrorOutput = ""
	
	if ( $output -ne $null) {
		if ( $output.action_exec_type -eq "T-SQL" ) {
			try {
				Invoke-SqlCmd -ServerInstance "AUSLYNCDBSAF03" -Database SQLWATCH -ErrorAction "Stop" -Query $output.action_exec -MaxCharLength 2147483647
			}
			catch {
				$ErrorOutput = $error[0] -replace "'", "''"
			}
		}

		if ( $output.action_exec_type -eq "PowerShell" ) {
			try {
				$action_exec = $output.action_exec
				Invoke-Expression $output.action_exec
			}
			catch {
				$ErrorOutput = $_.Exception.Message
				}
		}

       if ($ErrorOutput -ne "") {
 			$query = "update [dbo].[sqlwatch_meta_action_queue] set [exec_status] = 'FAILED' where queue_item_id = $queue_item_id;
					exec [dbo].[usp_sqlwatch_internal_log]
							@procces_name = 'PowerShell',
							@process_stage = '6DC68414-915F-4B52-91B6-4D0B6018243B',
							@process_message = '$ErrorOutput',
							@process_message_type = 'ERROR'"
        } else {
			$query = "update [dbo].[sqlwatch_meta_action_queue] set [exec_status] = 'OK' where queue_item_id = $queue_item_id;"
        }
		Invoke-SqlCmd -ServerInstance "AUSLYNCDBSAF03" -Database SQLWATCH -Query $query
		Invoke-SqlCmd -ServerInstance "AUSLYNCDBSAF03" -Database SQLWATCH -Query "delete from [dbo].[sqlwatch_meta_action_queue] [exec_status] = 'OK' and [time_queued] > dateadd(day,-1,sysdatetime())"
	}
}

**Comment by dennisa95** [comment]
Marcin,
I need more help with getting SQLWatch working.  I have the database
installed and all the jobs are working, however, the dashboard isn't being
populated completely.  I get a few things like whosactive and the number of
datrabases but none of the measurements are populated and the checks are
still reporting null values.  I've even tried refreshing the data from
within Power BI but nothing seems to be working.
What am I missing?
Dennis
