### ISSUE TITLE
Integration with WhoIsActive doesn't work on case sensitive collations

### ISSUE THREAD

**Issue by tvanzele** [marcingminski/sqlwatch#135]
The stored procedure (dbo.usp_sqlwatch_logger_whoisactive) used to detect the presence of sp_WhoIsActive uses all lowercase characters, while the default installation of sp_WhoIsActive uses some uppercase characters. 
This results in the stored procedure not being detected and the agent job SQLWATCH-LOGGER-WHOISACTIVE not being enabled by default.

**Comment by marcingminski** [comment]
Good point. I’ll fix that.
