### ISSUE TITLE
The project in branch 2.2 can't currently build in environments other than Visual Studio 2019

### ISSUE THREAD

**Issue by csatnic** [marcingminski/sqlwatch#136]
**Describe the bug**
The msdb dacpac reference uses a hardcoded path that only works if Visual Studio 2019 is used:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\110\SqlSchemas\msdb.dacpac

This leads to build errors when Visual Studio 2017 is used (since that referenced path does not exist).

**To Reproduce**
1. Attempt to build the SQLWATCH project from Visual Studio 2017 (for example)
2. Observe the build errors

**Comment by csatnic** [comment]
I have a solution for this and will be submitting a PR shortly.

**Comment by marcingminski** [comment]
Hi, there is no solution that can be PR'd that will work for everyone. Every time you import new database project from a different version of VS, you have to re-reference system databases as in different versions of VS they are in different folders (referenced by the VS version). All you need to do, go to References, remove master and msdb, and re-add system dbs

![image](https://user-images.githubusercontent.com/8288333/72211764-9e2bde00-34c8-11ea-8ea8-cb950a3ff88a.png)
