### ISSUE TITLE
[New Feature] Server configuration overview

### ISSUE THREAD

**Issue by marcingminski** [marcingminski/sqlwatch#14]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Configuraton change history to be able to correlate performace isses with configuration changes. A collateral benefit will be a dashboard page showing in-depth information about the instance.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by schenkfab** [comment]
Hi @marcingminski 
I could work on that feature, if OK with you.
I could collect server / instance information plus capture all changes on the server / instance.

**Comment by marcingminski** [comment]
Hi, 

Sure, 
I was planning on the sys.configuration to be captured in :
`sqlwatch_logger_server_configuration` or something along these lines.

I was also going to include things like updates, services packs and CUs so we can track when SQL was upgraded and to what version etc.

Normally the logger would just log a snapshot of the data, however, in case of the configuration, I think it would be sensible to approach it as if it was a slowly changing dimension i.e. capture changes only. It would save space and make it more transparent. 

On the other hand, this may make it difficult to follow the current model with the header as a parent entity, so alternative I am thinking of is to log snapshots and then have another table that will look like:

```

+--------------+--------------------+---------------------+------------+------------+
| sql_instance | configuration_name | configuration_value | valid_from |  valid_to  |
+--------------+--------------------+---------------------+------------+------------+
| SQL-1        | VERSION            | 2016 SP1            | 01/03/2020 | 10/03/2020 |
| SQL-1        | VERSION            | 2016 SP2            | 11/03/2020 | NULL       |
+--------------+--------------------+---------------------+------------+------------+
```

and the traditional logger table:

```
+--------------+--------------------+---------------------+---------------+
| sql_instance | configuration_name | configuration_value | snapshot_time |
+--------------+--------------------+---------------------+---------------+
| SQL-1        | VERSION            | 2016 SP1            | 10/03/2020    |
| SQL-1        | VERSION            | 2016 SP2            | 11/03/2020    |
+--------------+--------------------+---------------------+---------------+
```

The next hurdle will be retention. The standard retention routine will apply to logger tables but not the other table. Alternatively, depending on the volumes, which should not be too large, the "summary" could be done on the fly in a view.

I think we should try and do the "slowly changing dimension" first. On second thought, the relation with the header should not be a problem.

**Comment by schenkfab** [comment]
Hey @marcingminski in the guidelines, you state to have a pull request into the development branch. What is your development branch? 2.4?

**Comment by marcingminski** [comment]
Hi, Yes 2.4 please. Apologies, I may have to update the guidelines :)

**Comment by marcingminski** [comment]
Errmm... bit embarrassing question but where do you see these guidelines? I remember writing them but no idea where they are now...

**Comment by schenkfab** [comment]
There you go :-)

https://github.com/marcingminski/sqlwatch/blob/2_4/.github/CONTRIBUTING.MD

**Comment by marcingminski** [comment]
https://github.com/marcingminski/sqlwatch/pull/167
