### ISSUE TITLE
'Disk Utilisation' dasboard only shows one volume

### ISSUE THREAD

**Issue by ClaudioESSilva** [marcingminski/sqlwatch#140]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**
I could only see the C: volume where I also have D and a couple of mount points.

**To Reproduce**
1. Deploy the DACPAC
2. Wait for initial collections
3. Query `SELECT * FROM sqlwatch_meta_os_volume` has just one record with `is_record_deleted` to `0`. The ones with `1` are the ones not being shown

**Expected behavior**

**Screenshots**
Before the last "Filtered Rows" step everything is there
![image](https://user-images.githubusercontent.com/19521315/72340956-09400500-36c1-11ea-8d74-74327fc55acd.png)

After:
![image](https://user-images.githubusercontent.com/19521315/72340990-19f07b00-36c1-11ea-84fd-2041ef8fa3ac.png)

**Fix**
As discussed and suggested by @marcingminski maybe rely just on `[date_last_seen]` column.
Remove the current `is_record_deleted` column

**Windows Server (please complete the following information):**
 - OS Version: Windows Server 2016

**SQL Server (please complete the following information):**
 - SQL Version: SQL Server 2016 SP2 CU11
 - SQL Edition: Enterprise
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - Microsoft SQL Server Management Studio						13.0.15700.28
Microsoft Analysis Services Client Tools						13.0.1700.68
Microsoft Data Access Components (MDAC)						10.0.14393.0
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.14393.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.14393
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 2.2.7316.33346

**Comment by marcingminski** [comment]
Hi, Is this now fixed in the latest release?

**Comment by marcingminski** [comment]
The latest dashboard shows all disks.
