### ISSUE TITLE
Some descriptions have words "splited" by "-" char

### ISSUE THREAD

**Issue by ClaudioESSilva** [marcingminski/sqlwatch#142]
**Describe the bug**
Some descriptions have words "splited" by "-" char

**Expected behavior**
Have single word without separator
I see this come from `ref_perf_counters_poster` on Power BI.

**Screenshots**
![image](https://user-images.githubusercontent.com/19521315/72885482-ec7a8180-3cff-11ea-87fe-39a7314f4d9b.png)

![image](https://user-images.githubusercontent.com/19521315/72885820-9528e100-3d00-11ea-97f0-6aaa2acb1762.png)

**PBI Version:**
2.2.7 beta MASTER

NOTE: @marcingminski because you are working on the PBI, I will not submit a fix for it. If you want me to do so, let me know.

**Comment by marcingminski** [comment]
Thank you. Yes. It was a poor copy-paste job from the performance counters poster :)
I’ll fix PBI thank you for the offer though.
