### ISSUE TITLE
Jobs no longer created with "sa"

### ISSUE THREAD

**Issue by FrenchDataWizard** [marcingminski/sqlwatch#144]
Since the December change, the procedure that creates the jobs no longer sets the owner as "SA".
By default, the jobs are created with the owner set as the user that created them.
This can cause an issue where administrators are in another domain as the service accounts running the services.

This is not an issue once you change the ownership, but it generates incorrect setup of SQLWatch as the post-execution script doesn't let you change that ownership before running the jobs.

Error is:
 The job failed.  Unable to determine if the owner (xxx) of job xxx has server access (reason: Could not obtain information about Windows NT group/user ‘xxx’, error code 0x5. SQLSTATE 42000 (Error 15404))

Fix would be to restore the Job Owner being set to "SA" as it was before. This would at least make it work at setup, and then we can all happily change it to whatever we want for daily run.
It would also allow to integrate the pending pull request suggesting to use the user with id 01 rather than explicitly the "SA" account.

**Comment by marcingminski** [comment]
Can you see if this fixes it for you, please? It has been long overdue but I had limited ability to test it

**Comment by FrenchDataWizard** [comment]
Hello,
copied the project. Compiled to DACPAC. Deployed. All green.

We'll deploy this on our production and UAT DataWarehouse infrastructure.
I'll give you feedback on the exclude_database feature in a couple of days.
Thanks as always for the great work.

Le mer. 29 janv. 2020 à 12:05, Marcin Gminski <notifications@github.com> a
écrit :
