### ISSUE TITLE
PowerBI Report, wrong Datasource for Index Histogram

### ISSUE THREAD

**Issue by steffenengelhamburg** [marcingminski/sqlwatch#145]
Hi,
i try load Data from SQLWATCH Dashboard 2.2.5 beta.pbix

an Import Error leads to a wrong Datasource  of 'Index Histogram'

data = Source{[Schema="dbo",Item="vw_sqlwatch_report_fact_index_usage_stats_histogram"]}[Data],
need to be changed to 
data = Source{[Schema="dbo",Item="vw_sqlwatch_report_fact_index_histogram"]}[Data],

**Comment by marcingminski** [comment]
Hi, thanks. I am aware of it, the beta dashboard is still work in progress.
