### ISSUE TITLE
2.2.7275.26487 breaks SSIS data importing

### ISSUE THREAD

**Issue by ghost** [marcingminski/sqlwatch#146]
**Version:**
BETA 2.2.7275.26487 and above

**Summary:**
control_import.dtsx package calls a column that no longer exists in [sqlwatch_config_sql_instance] table

**Steps to reproduce:**
Using release 2.2.7275.26487 assets; 

- Set up a central repository and add a remote instance
- Configure SQLWATCHSSIS catalog for connections to remote instance and central repository
- Execute control_import.dtsx package

**Expected results**
Data is loaded from remote instance to central repository

**Actual results**

> Data Flow Task:Error: SSIS Error Code DTS_E_OLEDBERROR.  An OLE DB error has occurred. Error code: 0x80040E14.
> An OLE DB record is available.  Source: "Microsoft SQL Server Native Client 11.0"  Hresult: 0x80040E14  Description: "The batch could not be analyzed because of compile errors.".
> An OLE DB record is available.  Source: "Microsoft SQL Server Native Client 11.0"  Hresult: 0x80040E14  Description: "Invalid column name 'is_active'.".

Offending SqlCommand:
```
select sql_instance 
 , ntile(isnull(?,1)) over(order by sql_instance) as thread_id
 from [dbo].[sqlwatch_config_sql_instance]
 where is_active = 1
 /* do not collect own instance */
 and sql_instance <> @@servername
```

Column [is_active] was updated to [repo_collector_is_active] in [2.2 Beta December Update](https://github.com/marcingminski/sqlwatch/commit/8a3743511c0340709c04263bb85d7fad9220503b#diff-67eb57d73efed4ae035150094fc5fca6)

**Comment by marcingminski** [comment]
Hi, thank you. I’m aware the SSIS is a bit behind. It will be updated soon.

**Comment by marcingminski** [comment]
Should be now fixed in: https://github.com/marcingminski/sqlwatch/commit/c758a30aba4618e914d03ac37aaa7aab7bd13088

**Comment by ghost** [comment]
Seems to be a fix - package execution tested with success using https://github.com/marcingminski/sqlwatch/commit/05dee8381fb77bb0c1a441a41c7e4ca80e8bd09d ispac and release [2.2.7327.25234](https://github.com/marcingminski/sqlwatch/releases/tag/2.2.7327.25234) dacpac
