### ISSUE TITLE
vw_sqlwatch_report_fact_whoisactive: Arithmetic overflow error converting expression to data type int.

### ISSUE THREAD

**Issue by steffenengelhamburg** [marcingminski/sqlwatch#148]
INT Overflow in [vw_sqlwatch_report_fact_whoisactive]
If wait_time_ms exceed INT than arithmetic Error on Calculating [end_time] with Dateadd
Error: 
Msg 8115, Level 16, State 2, Line 2
Arithmetic overflow error converting expression to data type int.

On System with long runtime some waitinfo from sp_server_diagnostics may occour:
Microsoft® Windows® Operating System | sp_server_diagnostics

wait_info
(2520191090ms)PREEMPTIVE_XE_GETTARGETSTATE
(2449121747ms)SP_SERVER_DIAGNOSTICS_SLEEP
(2284274354ms)PREEMPTIVE_XE_GETTARGETSTATE
(2279039978ms)SP_SERVER_DIAGNOSTICS_SLEEP

in this cases endtime is Reporttime

Windows 2012 R2

SQL Server 2012 SP4 GDR 11.0.7462.6
  
**SQLWATCH version (DACPAC)
 - 2.1 & 2.2 Beta
 
**suggested Fix**
Because it's only a workaround i put this here instead of a Pull request:
[vw_sqlwatch_report_fact_whoisactive]
Replace Line

 ,[end_time] = DATEADD(ms, CONVERT(BIGINT, SUBSTRING([wait_info], 2, PATINDEX('%)%', [wait_info]) - 4)), CONVERT(DATETIME, LTRIM([start_time])))

with following:

      ,[end_time] =  CASE
                        WHEN CONVERT(BIGINT, SUBSTRING([wait_info], 2, PATINDEX('%)%', [wait_info]) - 4)) < 2147483648
                        THEN DATEADD(ms, CONVERT(BIGINT, SUBSTRING([wait_info], 2, PATINDEX('%)%', [wait_info]) - 4)), CONVERT(DATETIME, LTRIM([start_time])))
                        ELSE [report_time]
                     END

Var2:
there is a Function around:
https://stackoverflow.com/questions/15030474/sql-using-dateadd-with-bigints

**Comment by marcingminski** [comment]
Thank you for raising this. I can see where the problem is. 
We could convert the 2520191090ms to 2520191.09 seconds first and then do `dateadd` s instead of ms. It would mean we're losing the ms fraction from the time end:

```
  ,[end_time] = dateadd(s,(convert(bigint,substring([wait_info],2,patindex('%)%',[wait_info])-4))/1000.0),convert(datetime,ltrim([start_time])))
```
