### ISSUE TITLE
Feature request: Input sanitation for SSIS (package job error:  "Invalid character value for cast specification")

### ISSUE THREAD

**Issue by SheldonDBA** [marcingminski/sqlwatch#151]
I pasted instance names from Excel one at a time into the sql_instance config table.  I guess it entered other characters in there too like "new lines".  So it caused problems with only 1 of 29 instances showing up in PBI dashboard and the SSIS job control_import package to error out.  Input likely just needs sanitizing into the sql_instance table.  Silly move on my part.

![image](https://user-images.githubusercontent.com/59664659/76033461-2e970580-5ef1-11ea-86fa-20287bd2d734.png)

Windows 2016
SQL 2016 SP2 Standard Edition
 
SQLWATCH version is 2.2.7367.29602

**Comment by marcingminski** [comment]
Marking this as a feature to implement some sort of input sanitisation.
