### ISSUE TITLE
Can not upgrade from 2.0 to 2.2

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [marcingminski/sqlwatch#152]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**
Tried to upgrade from 2.0 to latest via dbatools failed for data loss - tried to use SSMS to deploy package errors below

Created deployment script and ran that

Msg 547, Level 16, State 0, Line 6346
The ALTER TABLE statement conflicted with the CHECK constraint "chk_sqlwatch_config_sql_instance_is_active". The conflict occurred in database "SQLWatch", table "dbo.sqlwatch_config_sql_instance".

** An error was encountered during execution of batch. Exiting.

**Expected behavior**
An upgrade ;-)

**Windows Server (please complete the following information):**
 Windows 2012 R2

**SQL Server (please complete the following information):**
 - SQL Version: SQL 2014
 - SQL Edition: Enterprise
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
Microsoft SQL Server Management Studio						14.0.17285.0
Microsoft Analysis Services Client Tools						14.0.1016.283
Microsoft Data Access Components (MDAC)						10.0.17134.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.17134.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.17134
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 2.2 2.2.7367.29602
 
**Additional context**
TITLE: Microsoft SQL Server Management Studio
------------------------------

Could not deploy package.
Warning SQL72012: The object [SQLWatch] exists in the target, but it will not be dropped even though you selected the 'Generate drop statements for objects that are in the target database but that are not in the source' check box.
Warning SQL72012: The object [SQLWatch_log] exists in the target, but it will not be dropped even though you selected the 'Generate drop statements for objects that are in the target database but that are not in the source' check box.
Warning SQL72038: The object [SQLWATCH_blockers] already exists in database with a different definition and will not be altered.
Warning SQL72038: The object [SQLWATCH_long_queries] already exists in database with a different definition and will not be altered.
Warning SQL72038: The object [SQLWATCH_waits] already exists in database with a different definition and will not be altered.
Warning SQL72015: The column [dbo].[sqlwatch_config_sql_instance].[repo_last_collection_finish_time] is being dropped, data loss could occur.
Warning SQL72015: The column [dbo].[sqlwatch_config_sql_instance].[repo_last_collection_status] is being dropped, data loss could occur.
Warning SQL72016: The column environment on table [dbo].[sqlwatch_config_sql_instance] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
Warning SQL72016: The column sqlwatch_database_name on table [dbo].[sqlwatch_config_sql_instance] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
Warning SQL72016: The column date_created on table [dbo].[sqlwatch_meta_index] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
Warning SQL72015: The column [dbo].[sqlwatch_meta_index_missing].[date_updated] is being dropped, data loss could occur.
Warning SQL72016: The column date_created on table [dbo].[sqlwatch_meta_index_missing] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
Warning SQL72016: The column date_created on table [dbo].[sqlwatch_meta_sql_text] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
Warning SQL72015: The column [dbo].[sqlwatch_meta_table].[date_updated] is being dropped, data loss could occur.
Warning SQL72016: The column date_created on table [dbo].[sqlwatch_meta_table] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
Error SQL72014: .Net SqlClient Data Provider: Msg 1205, Level 13, State 56, Line 25 Transaction (Process ID 64) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
Error SQL72045: Script execution error.  The executed script:
ALTER TABLE [dbo].[sqlwatch_logger_agent_job_history] WITH CHECK CHECK CONSTRAINT [fk_sqlwatch_logger_agent_job_history_snapshot_header];

ALTER TABLE [dbo].[sqlwatch_logger_disk_utilisation_database] WITH CHECK CHECK CONSTRAINT [FK_logger_disk_util_database_snapshot];

ALTER TABLE [dbo].[sqlwatch_logger_disk_utilisation_volume] WITH CHECK CHECK CONSTRAINT [FK_disk_util_vol_snapshot_header];

ALTER TABLE [dbo].[sqlwatch_logger_index_missing_stats] WITH CHECK CHECK CONSTRAINT [fk_logger_missing_indexes_snapshot_header];

ALTER TABLE [dbo].[sqlwatch_logger_index_usage_stats] WITH CHECK CHECK CONSTRAINT [fk_index_usage_stats_header];

ALTER TABLE [dbo].[sqlwatch_logger_index_histogram] WITH CHECK CHECK CONSTRAINT [fk_logger_index_histogram];

ALTER TABLE [dbo].[sqlwatch_logger_perf_file_stats] WITH CHECK CHECK CONSTRAINT [fk_sql_perf_mon_file_stats_snapshot_header];

ALTER TABLE [dbo].[sqlwatch_logger_perf_os_memory_clerks] WITH CHECK CHECK CONSTRAINT [fk_sql_perf_mon_os_memory_clerks_snapshot_head
Error SQL72014: .Net SqlClient Data Provider: Msg 4916, Level 16, State 0, Line 25 Could not enable or disable the constraint. See previous errors.
Error SQL72045: Script execution error.  The executed script:
ALTER TABLE [dbo].[sqlwatch_logger_agent_job_history] WITH CHECK CHECK CONSTRAINT [fk_sqlwatch_logger_agent_job_history_snapshot_header];

ALTER TABLE [dbo].[sqlwatch_logger_disk_utilisation_database] WITH CHECK CHECK CONSTRAINT [FK_logger_disk_util_database_snapshot];

ALTER TABLE [dbo].[sqlwatch_logger_disk_utilisation_volume] WITH CHECK CHECK CONSTRAINT [FK_disk_util_vol_snapshot_header];

ALTER TABLE [dbo].[sqlwatch_logger_index_missing_stats] WITH CHECK CHECK CONSTRAINT [fk_logger_missing_indexes_snapshot_header];

ALTER TABLE [dbo].[sqlwatch_logger_index_usage_stats] WITH CHECK CHECK CONSTRAINT [fk_index_usage_stats_header];

ALTER TABLE [dbo].[sqlwatch_logger_index_histogram] WITH CHECK CHECK CONSTRAINT [fk_logger_index_histogram];

ALTER TABLE [dbo].[sqlwatch_logger_perf_file_stats] WITH CHECK CHECK CONSTRAINT [fk_sql_perf_mon_file_stats_snapshot_header];

ALTER TABLE [dbo].[sqlwatch_logger_perf_os_memory_clerks] WITH CHECK CHECK CONSTRAINT [fk_sql_perf_mon_os_memory_clerks_snapshot_head
 (Microsoft.SqlServer.Dac)

------------------------------
BUTTONS:

OK
------------------------------

**Comment by marcingminski** [comment]
This seems to collateral from a bug in 2.1. The column `[repo_collector_is_active]` must be 0 for local instance. You fix it by running the below update and then re-running the upgrade:

```sql
UPDATE [dbo].[sqlwatch_config_sql_instance]
SET [repo_collector_is_active] = 0
WHERE [sql_instance] = @@SERVERNAME
```

And please let me know if this works

**Comment by SQLDBAWithABeard** [comment]
Apologies, the databases are at 2.0 and not 2.1 and that column does not exist ;-)

**Comment by marcingminski** [comment]
Ah... 2.0 was pulled a few days after the initial release due to a nasty bug - a cartesian product causing ugly exponential growth. It was quickly replaced with 2.1 but sadly, there is no upgrade path from 2.0 to 2.1 due to migration from GUIDs to INTs.

**Comment by SQLDBAWithABeard** [comment]
So best to blow it away and start again?

**Comment by marcingminski** [comment]
Yes, apologies, 2.0 is crap.
