### ISSUE TITLE
Be able to alias instances

### ISSUE THREAD

**Issue by FrenchDataWizard** [marcingminski/sqlwatch#160]
**Is your feature request related to a problem? Please describe.**
When managing multiple instances, with server names that are not always friendly, it would be nice to be able to alias instances in the Dasboard.

**Describe the solution you'd like**
Add an alias column on the config instance table, and use it for display in the report.

**Comment by marcingminski** [comment]
Good idea but it will be time consuming to implement as it will require changing most of the dashboard.

**Comment by FrenchDataWizard** [comment]
No urgency on my side, I did a fork of the report.
What I did was quick: rename the column in the backend so that the Alias matches the currently used one :)

**Comment by marcingminski** [comment]
You can now add your own name in `[dbo].[sqlwatch_config_sql_instance]`, column `[sql_instance_user_alias]` which will be displayed across the dashboard in filters. If no user alias given a standard name will be shown. 
![image](https://user-images.githubusercontent.com/8288333/85951597-fd3cbc80-b95b-11ea-9068-aaa156a49acf.png)
