### ISSUE TITLE
Filter out technical partitions

### ISSUE THREAD

**Issue by FrenchDataWizard** [marcingminski/sqlwatch#161]
**Is your feature request related to a problem? Please describe.**
Windows technical partitions starting by \\?\ show up in the report and I've never seen anybody having to monitor those

**Describe the solution you'd like**
Filter them out at the report level (so preople could easily edit them back in) by adding a modeling step on the Dim OS Disk table, excluding drives starting with \\?\

**Comment by marcingminski** [comment]
Yeah this is a bug, they used to be filtered out but somehow are no longer. Thanks.

**Comment by marcingminski** [comment]
Can you please provide a screenshot of all tables and views where they appear please?

**Comment by FrenchDataWizard** [comment]
It seems the only table is **sqlwatch_meta_os_volume** (as the others refer to content via ID in this table)
And for views, in **vw_sqlwatch_report_fact_disk_utilisation_volume** and **vw_sqlwatch_report_dim_os_volume**

Recommendation would be to filter them out in **usp_sqlwatch_internal_add_os_volume** on the merge.
