### ISSUE TITLE
Proposal on how to integrate dbachecks into SQLWATCH

### ISSUE THREAD

**Issue by marcingminski** [marcingminski/sqlwatch#166]
dbachecks is a framework created by Rob Sewell (@SQLDBAWithABeard) and it's designed to validate server and database configuration. The benefit of integrating it with SQLWATCH will be the ability to correlate configuration change and impact on performance. For example, someone changes MaxDop and it has a negative impact on the application. You will be able to correlate these and feedback to your project/developer/manager.

# Assumptions
dbachecks are best run from a central location. Whilst it would be possible to run them in a decentralised manner, same as SQLWATCH, it would mean that all dependencies would also have to be installed on each monitored server: dbachecks, pester, dbatools. 
Therefore, I am going to suggest that dbachecks are only run from the SQLWATCH central repository. However, the database design will allow for either approach.

# Options

## 1. Leave as is
dbachecks can write results to a SQL database. We could leave it as is, completely independent and integrate with SQLWATCH by:
* have a simple page in PBI with check timeline/status so we can overlay any failed checks on the performance graphs. The in-depth report would still be the dbachecks PBI
* dbachecks tables would not be part of the SQLWATCH schema as far as FK goes but they would be deployed with SQLWATCH to make PBI work.
	
## 2. Normalise dbacheck and load into SQLWATCH schema. 
* This would allow us to maintain snapshot types and retention as well as correlate by snapshot time. We would still need the original tables from step 1 So this could be developed in phases. The benefit of this approach is that normalisation will allow to reduce the size of tables and improve PBI performance. Fk to snapshot time would leverage existing retention mechanism. 

# Execution and customisation
There could be a config table sqlwatch_dbachecks_config that would allow setting different checks (inclusion or exclusion) per server. As much as I do not like making exclusion in the policy, sometimes this is unavoidable and it would be good to be able to account for it. This could also correspond with the -Label parameter.

Since we are mainly focusing on performance-related checks, SQLWATCH would have to ship with pre-defined perf related checks. 

I will have to think about how to design the schema to be able to handle per-server exclusion or inclusion.

the invokation would be driven by the existing `sqlwatch_config_sql_instance` table:

```
$SqlRepository = "192.168.3.15"
$SqlGetInstances = "SELECT SqlInstance = ISNULL(hostname,sql_instance) + 
	CASE WHEN [sql_port] IS NOT NULL THEN ',' + CONVERT(VARCHAR,[sql_port]) ELSE '' END
  FROM [dbo].[sqlwatch_config_sql_instance]"

$SqlInstance = (Invoke-DbaQuery -Query $SqlGetInstances -SqlInstance $SqlRepository -Database SQLWATCH).SqlInstance

Invoke-DbcCheck -SqlInstance $SqlInstance -AllChecks -PassThru | Convert-DbcResult -Label SQLWATCH `
    | Write-DbcTable -SqlInstance $SqlRepository -Database SQLWATCH -Table dbachecksResults 
	
Invoke-SqlCmd -Query "..Normalise results..."
```
OR, a simpler per-server execution would be to simply store the invocation command per server in one of the config tables:

`SERVER1, Invoke-DbcCheck -SqlInstance $SqlInstance -AllChecks`
`SERVER2, Invoke-DbcCheck -SqlInstance $SqlInstance -Check -SomeCheck`
`SERVER2, Invoke-DbcCheck -SqlInstance $SqlInstance -Check Check1,Check2,Check3`

If we are going to normalise results, we are also going to have to provide views or synonyms (or leave original tables) for the original dbachecks PBI to work. 

Please comment and suggest the best approach.

**Comment by SQLDBAWithABeard** [comment]
So, first thought is about configurations.
dbachecks is configurable using the json file from the export-dbcconfig command. 
People will have different threshholds/values for checks which they control via the config.
There is no reason that this could not be stored in the database for each check.

The best option would be to include the schema of the two tables that take the results of the checks from write-dbctable so dbachecks results can be delivered to them and then process them as needed.

dbachecks can be run from a central location or from multiple locations to a central hub. the easiest option is to ensure that the pre-reqs are available at the central location and check all of the instances from there (unless the environment is more complex and there are connectivity/authentication issues but that should be outside of the scope of this initial suggestion.

I would think the normalisation should be done with a proc as an Agent Job rather than being called from the PowerShell

**Comment by marcingminski** [comment]
Hi Rob, thanks.

So I think step 2 compliments step 1. I will start with Step 1 (keep it simple to start with) and maybe normalise results. Then, later on, we can figure out how to apply execution customisation if at all. 

Realistically speaking, the next release of SQLWATCH could, therefore, include the two dbachecks tables (`dbachecksChecks` and `dbachecksResults`) and some form of integration, likely via the SQLWATCH internal checks/actions mechanism to indicate what dbachecks fail and when. It could be as simple as a single indication "dbachecks failed" (similar to SQL agent job failed) and for details, people would run your fantastic PBI. 

Actually, with this approach, the default tables do not even have to be in the SQLWATCH database as the SQLWATCH actions can be configured to check any database but for simplicity, I will start with that. 

Yes, the normalisation would be run via stored procedure it was just me drafting the approach. Once the brain goes into PS it stays in PS for a bit. But I am still debating whether I should normalise it. Such tight integration will create constraints on future changes.

**Comment by marcingminski** [comment]
74e7999c6a54fa9d2f3ca7f6bdef13cf098ef3df
