### ISSUE TITLE
Days Until Full When no growth on disk

### ISSUE THREAD

**Issue by simonwhybrow-cbre** [marcingminski/sqlwatch#172]
Hi,

First of all this looks like an amazing tool and looking forward to using it in anger.

I've been using it initially in a test environment and come across an issue whereby the "Days Until Full" is reporting as 0 for disks that have no change in their growth per day

The disk configuration on our standard SQL instance uses a mount drive from which all the other drives (data, log temp etc) hang. This mount volume never has anything written to it so the volume_bytes_growth" is always going to be 0
We also have other drives where this may be applicable.

I can see in the view that is used to alert on Days Until Full that it uses a case statement:

```
case when [total_growth_days] > 0 and volume_bytes_growth > 0 then volume_free_space_bytes_current / ([volume_bytes_growth] / [total_growth_days]) else 0 end
```
So as the volume_bytes_growth isn't greater than 0, it gets the default value of 0.

In my eyes, unless I've misunderstood this, if the growth on a disk is 0 then the days until full is effectively infinite. So therefore I'd expect this days until full to be either a large value (e.g 999999) or something similar.

For information below are the details for where I'm running SQLWatch:
 - OS Version: Windows 2012 R2

**SQL Server (please complete the following information):**
 - SQL Version: SQL 2017 CU13
 - SQL Edition: Developer
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
SQL Server Management Studio						15.0.18330.0
SQL Server Management Objects (SMO)						16.100.37971.0
Microsoft Analysis Services Client Tools						15.0.19040.0
Microsoft Data Access Components (MDAC)						10.0.18362.1
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.18363
 
**SQLWATCH version (from DACPAC or from sysinstances)**
2.3.7404.25402

**Comment by marcingminski** [comment]
Hi,

Thanks. Yes, I am aware of it but at the time this came to attention, I wasn't sure how to make it work in PBI. 
Ideally, this should be NULL or -1 in the view and PBI to translate it to infinity ∞ but for some reason, this turned out more difficult than I thought. I will revisit it again.
