### ISSUE TITLE
Stored procedure [dbo].[usp_sqlwatch_internal_add_table] is very slow

### ISSUE THREAD

**Issue by MartinBarhon** [marcingminski/sqlwatch#176]
Stored procedure [dbo].[usp_sqlwatch_internal_add_table] is called like step 7 of job SQLWATCH-INTERNAL-CONFIG. It is very slow on SQL instance where is more then 20.000 records in table dbo.sqlwatch_meta_table. It can last more then 20-40 minutes to execute.

There is problem with using view [dbo].[vw_sqlwatch_sys_databases] in join
merge [dbo].[sqlwatch_meta_table] as target
using (
	select [t].[TABLE_CATALOG], [t].[TABLE_SCHEMA], [t].[TABLE_NAME], [t].[TABLE_TYPE], mdb.sqlwatch_database_id, mtb.sqlwatch_table_id
	from ##98308FFC2C634BF98B347EECB98E3490 t
	inner join **[dbo].[vw_sqlwatch_sys_databases] dbs**
		on dbs.name = t.TABLE_CATALOG 
	inner join [dbo].[sqlwatch_meta_database] mdb
		on mdb.database_name = dbs.name collate database_default
		and mdb.database_create_date = dbs.create_date
		and mdb.sql_instance = @@SERVERNAME
	left join [dbo].[sqlwatch_meta_table] mtb
		on mtb.sql_instance = mdb.sql_instance
		and mtb.sqlwatch_database_id = mdb.sqlwatch_database_id
		and mtb.table_name = t.TABLE_SCHEMA + '.' + t.TABLE_NAME collate database_default
	) as source

When I create temporary table
CREATE TABLE #sqlwatch_sys_databases(
	[name] [sysname] NOT NULL,
	[create_date] [datetime] NOT NULL,
	constraint PK_TMP_sqlwatch_sys_databases primary key clustered (
		[name]
		)
) 
and insert rows from view to this table so that SQL can use statistics
INSERT INTO #sqlwatch_sys_databases
SELECT name, create_date
FROM [dbo].[vw_sqlwatch_sys_databases]

and use it in that join
merge [dbo].[sqlwatch_meta_table] as target
using (
	select [t].[TABLE_CATALOG], [t].[tablename], [t].[TABLE_TYPE], mdb.sqlwatch_database_id, mtb.sqlwatch_table_id
	from ##11198308FFC2C634BF98B347EECB98E3490 t
	inner join #sqlwatch_sys_databases dbs
		on dbs.name = t.TABLE_CATALOG 
	inner join [dbo].[sqlwatch_meta_database] mdb
		on mdb.database_name = dbs.name collate database_default
		and mdb.database_create_date = dbs.create_date
		and mdb.sql_instance = @@SERVERNAME
	left join [dbo].[sqlwatch_meta_table] mtb
		on mtb.sql_instance = mdb.sql_instance
		and mtb.sqlwatch_database_id = mdb.sqlwatch_database_id
		and mtb.table_name = t.tablename collate database_default

	) as source
it lasts only 20-40 seconds.

Next optimization of this stored procedure can be done
by change of table ##11198308FFC2C634BF98B347EECB98E3490 to use column tablename like TABLE_SCHEMA + ''.'' + TABLE_NAME which is used in other tables and we can join it.

create table ##11198308FFC2C634BF98B347EECB98E3490 (
	[TABLE_CATALOG] [nvarchar](128) NOT NULL,
	[tablename] [sysname] NOT NULL,
	[TABLE_TYPE] [varchar](10) NULL,
	constraint PK_TMP_11198308FFC2C634BF98B347EECB98E3490 primary key clustered (
		[TABLE_CATALOG], [tablename]
		)
)

exec [dbo].[usp_sqlwatch_internal_foreachdb] @command = '
USE [?]
insert into ##11198308FFC2C634BF98B347EECB98E3490 ([TABLE_CATALOG],[tablename],[TABLE_TYPE])
SELECT [TABLE_CATALOG],TABLE_SCHEMA + ''.'' + TABLE_NAME,[TABLE_TYPE] 
from INFORMATION_SCHEMA.TABLES
WHERE''?'' <> ''tempdb''', @databases = '-tempdb', @calling_proc_id = @@PROCID

so that we can join 
mtb.table_name = t.tablename
which are both indexed again in join
merge [dbo].[sqlwatch_meta_table] as target
using (
	select [t].[TABLE_CATALOG], [t].[tablename], [t].[TABLE_TYPE], mdb.sqlwatch_database_id, mtb.sqlwatch_table_id
	from ##11198308FFC2C634BF98B347EECB98E3490 t
	inner join ##sqlwatch_sys_databases dbs
		on dbs.name = t.TABLE_CATALOG 
	inner join [dbo].[sqlwatch_meta_database] mdb
		on mdb.database_name = dbs.name collate database_default
		and mdb.database_create_date = dbs.create_date
		and mdb.sql_instance = @@SERVERNAME
	left join [dbo].[sqlwatch_meta_table] mtb
		on mtb.sql_instance = mdb.sql_instance
		and mtb.sqlwatch_database_id = mdb.sqlwatch_database_id
		and mtb.table_name = t.tablename collate database_default
	) as source

I use actual version SQLWATCH 2.5.7460.35921 on SQL Server 2017 CU20.

**Comment by marcingminski** [comment]
Hi, can you provide an execution plan please? I am unable to replicate this issue.
I have a test database with 256050 tables and the execution takes ~20 seconds
![image](https://user-images.githubusercontent.com/8288333/85232394-7be2a880-b3f6-11ea-8059-d540a2c5b977.png)

**Comment by MartinBarhon** [comment]
[usp_sqlwatch_internal_add_table.zip](https://github.com/marcingminski/sqlwatch/files/4810200/usp_sqlwatch_internal_add_table.zip)

Hi, I attached execution plan from one of our servers.

**Comment by marcingminski** [comment]
Hi, Thanks for this. I can see with your suggested change it runs much faster in my environment too. It's down from ~16 seconds to 4 seconds. I do not know why it takes minutes on yours. The view has some complexity so perhaps it confuses the optimizer as the merge can generate quite a big plan. It may even time out. 

I have added your suggested change into the next release. 
I will review all procs using this view.

Thanks!
