### ISSUE TITLE
Recent Backup Reporting Incorrectly

### ISSUE THREAD

**Issue by simonwhybrow-cbre** [marcingminski/sqlwatch#179]
The query that is used to determine if a database doesn't have a recent backup (checkid -18) seems incorrect.

We currently clear down our backup history on a regular basis, but keep 30 days worth in msdb.

This means that when the check runs, it reports the maximum number of days to the oldest backup, (not the most recent) and raises an alert to say that there is a database with no recent backup.

Currently the check runs the below:
```sql
select @output=isnull(max(datediff(day,backup_finish_date,getdate())),0)
from sys.databases d
left join msdb.dbo.backupset bs
	on bs.database_name = d.name
	and bs.type <> 'L'
where d.name not in ('tempdb')
``` 

It would seem to me to be better to collect the latest backup for each database in a CTE first then check against that, as below:

```sql
WITH CTE AS (
SELECT d.Name AS DatabaseName,
MAX(bs.backup_finish_date) AS LastBackUpTime
FROM sys.sysdatabases d
LEFT JOIN msdb.dbo.backupset bs ON bs.database_name = d.name
	and bs.type <> 'L'
where d.name not in ('tempdb')
GROUP BY d.Name
)
select isnull(max(datediff(day,LastBackUpTime,getdate())),0)
from CTE
```

Currently using version 2.5.7460.35921

Thanks
Simon

**Comment by marcingminski** [comment]
Hi, can you please check this commit as I believe this was recently fixed:
https://github.com/marcingminski/sqlwatch/commit/8e53b2390e3897866f881c343b75df316b71efac

**Comment by simonwhybrow-cbre** [comment]
Hi,

By changing it to a min in the query though will mean that if at least one database has had a recent backup on a server, but one or more databases haven't it will be reported as being OK as the query returns the min for all databases.

Using the CTE means you get the latest backup for each database and then you can take the max of that to tell you if there is a database without a recent backup.

**Comment by marcingminski** [comment]
OK, you sound correct. let me review this, I'm getting confused why this has been "fixed" to min.

**Comment by marcingminski** [comment]
I also think the isnull should return a high number otherwise databases with no backups (null in backupset) will return 0 as if they had a recent backup?
Changing to 999 would raise the alert and be also recognisable to the DBA:
`select isnull(max(datediff(day,last_backup_time,getdate())),999)`

**Comment by simonwhybrow-cbre** [comment]
Yeah that actually makes a lot of sense too, good thinking.
