### ISSUE TITLE
Could not deploy dacpac package

### ISSUE THREAD

**Issue by RaufAsadov** [marcingminski/sqlwatch#181]
Hi everyone. I am trying to install SQLWATCH on my SQL Server 2014 which I am running on VM Windows Server 2012 R2. I have gone through all steps provided on the website (using dbatools, using dacpac file, using sqlpackage.exe, creating SQLWATCH database beforehand and upgrading it) but every time got stuck on this:

`Could not deploy package.
Warning SQL72038: The object [SQLWATCH_blockers] already exists in database with a different definition and will not be altered.
Warning SQL72038: The object [SQLWATCH_long_queries] already exists in database with a different definition and will not be altered.
Warning SQL72038: The object [SQLWATCH_waits] already exists in database with a different definition and will not be altered.
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_add_jobserver, Line 88 The specified @server_name ('WIN-J258GNQTAL6\MSSQL2014TEST') does not exist.
Error SQL72045: Script execution error.  The executed script:
BEGIN TRANSACTION;

MERGE INTO dbo.sqlwatch_config_sql_instance
 AS target
USING (SELECT @@SERVERNAME AS [servername],
              0 AS [repo_collector_is_active]) AS source ON target.sql_instance = source.[servername]
WHEN NOT MATCHED THEN INSERT (sql_instance, [repo_collector_is_active]) VALUES (source.[servername], source.[repo_collector_is_active]);

MERGE INTO [dbo].[sqlwatch_meta_server]
 AS target
USING (SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')) AS [physical_name],
              CONVERT (sysname, @@SERVERNAME) AS [servername],
              CONVERT (sysname, @@SERVICENAME) AS [service_name],
              CONVERT (VARCHAR (50), local_net_address) AS [local_net_address],
              CONVERT (VARCHAR (50), local_tcp_port) AS [local_tcp_port],
              DATEDIFF(mi, GETUTCDATE(), GETDATE()) AS [utc_offset_minutes],
              @@VERSION AS [sql_version]
       FROM   sys.dm_exec_connections
       WHERE  session_id = @@spid) AS source ON target.[se
Error SQL72014: .Net SqlClient Data Provider: Msg 14256, Level 16, State 1, Procedure sp_start_job, Line 51 Cannot start the job "SQLWATCH-INTERNAL-CONFIG" (ID 0F949341-59AB-4638-977F-FF9D49A2E12B) because it does not have any job server or servers defined. Associate the job with a job server by calling sp_add_jobserver.
Error SQL72045: Script execution error.  The executed script:
BEGIN TRANSACTION;

MERGE INTO dbo.sqlwatch_config_sql_instance
 AS target
USING (SELECT @@SERVERNAME AS [servername],
              0 AS [repo_collector_is_active]) AS source ON target.sql_instance = source.[servername]
WHEN NOT MATCHED THEN INSERT (sql_instance, [repo_collector_is_active]) VALUES (source.[servername], source.[repo_collector_is_active]);

MERGE INTO [dbo].[sqlwatch_meta_server]
 AS target
USING (SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')) AS [physical_name],
              CONVERT (sysname, @@SERVERNAME) AS [servername],
              CONVERT (sysname, @@SERVICENAME) AS [service_name],
              CONVERT (VARCHAR (50), local_net_address) AS [local_net_address],
              CONVERT (VARCHAR (50), local_tcp_port) AS [local_tcp_port],
              DATEDIFF(mi, GETUTCDATE(), GETDATE()) AS [utc_offset_minutes],
              @@VERSION AS [sql_version]
       FROM   sys.dm_exec_connections
       WHERE  session_id = @@spid) AS source ON target.[se
Error SQL72014: .Net SqlClient Data Provider: Msg 50000, Level 16, State 1, Procedure usp_sqlwatch_internal_run_job, Line 61 Job 'SQLWATCH-INTERNAL-CONFIG' has not finished successfuly or the state is not known.
Error SQL72045: Script execution error.  The executed script:
BEGIN TRANSACTION;

MERGE INTO dbo.sqlwatch_config_sql_instance
 AS target
USING (SELECT @@SERVERNAME AS [servername],
              0 AS [repo_collector_is_active]) AS source ON target.sql_instance = source.[servername]
WHEN NOT MATCHED THEN INSERT (sql_instance, [repo_collector_is_active]) VALUES (source.[servername], source.[repo_collector_is_active]);

MERGE INTO [dbo].[sqlwatch_meta_server]
 AS target
USING (SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')) AS [physical_name],
              CONVERT (sysname, @@SERVERNAME) AS [servername],
              CONVERT (sysname, @@SERVICENAME) AS [service_name],
              CONVERT (VARCHAR (50), local_net_address) AS [local_net_address],
              CONVERT (VARCHAR (50), local_tcp_port) AS [local_tcp_port],
              DATEDIFF(mi, GETUTCDATE(), GETDATE()) AS [utc_offset_minutes],
              @@VERSION AS [sql_version]
       FROM   sys.dm_exec_connections
       WHERE  session_id = @@spid) AS source ON target.[se
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_add_jobserver, Line 88 The specified @server_name ('WIN-J258GNQTAL6\MSSQL2014TEST') does not exist.
Error SQL72045: Script execution error.  The executed script:
BEGIN TRANSACTION;.............`

[Full error code.txt](https://github.com/marcingminski/sqlwatch/files/4838532/Full.error.code.txt)

![Annotation 2020-06-26 212817](https://user-images.githubusercontent.com/34750437/85886505-4cb5a800-b7f7-11ea-9091-d0a725960f8b.jpg)

![Annotation 2020-06-26 215038](https://user-images.githubusercontent.com/34750437/85886517-5212f280-b7f7-11ea-86bc-522dd06af52b.jpg)

EDIT: I checked it on SQL Server 2019, and it works with no problem. I think the problem is related to SQL Server version. I also checked with different versions of SSMS on SQL Server 2014 and got the same error.

**Comment by marcingminski** [comment]
It looks like the server in question has broken (or stopped) SQL agent or the @@SERVERNAME is incorrect. This is not SQLWATCH issue, it deploys fine but fails to launch the job required for data collection. I am going to close this as its out of scope for what we can offer here, however, if you need help with you instance please jump on our Slack channel I'm sure there will be someone able to help you out.
