### ISSUE TITLE
Should we look at using Service Broker in stead of Agent Job for collection?

### ISSUE THREAD

**Issue by marcingminski** [marcingminski/sqlwatch#182]
It would work on Express edition out of the box. We could use the timer for scheduling. I'm more interested in whether we should make this work and not how to make this work. 
Let's discuss the pros and cons.

**Comment by marcingminski** [comment]
ah well...

**Comment by Karlk7** [comment]
I think the Service Broker for the main aspects of SQLWatch would be a welcoming aspect and will allow more granularity of the checks etc.

**Comment by marcingminski** [comment]
This is happening --> https://sqlwatch.io/blog/announcements/were-moving-to-queues/

**Comment by sozezzo** [comment]
I installed SqlWatch using QUEUEs. 


I use GRAFANA to monitor but :

- If I monitor the last 5 minutes, everything works fine.

- If I change to see the last 12 hours, the SQL server increases CPU to 100%.

Workaround : disable queue "sqlwatch_exec", kill all connection to SQLWatch database, 
and execute the stored procedure :
- [dbo].[usp_sqlwatch_internal_restart_queues]


**Has anyone had this kind of problem?**


context:
- SqlWatch + 6 databases;
- Normally, without GRAFANA, CPU is between 10% and 40%; 
- There is a constant flow of data.


*by the way, I love the idea of using queues instead of Jobs.*

**Comment by marcingminski** [comment]
I suspect what happens is that you're trying to pull too much data and Grafana may be a bit too aggressive causing other queries to slow down (i.e. logger) but the queue will fire new logger every 5 seconds, so the traffic keeps growing. Can you try latest dashboard as some performance improvements have been made? Also, if you still encounter an issue, please open a new issue as this one has been closed for some time now and I struggle to find posts in closed issues. Thanks

**Comment by marcingminski** [comment]
Also, when you are selecting larger periods, please make sure to set aggregation to auto or few minutes or hours to reduce the amount of data

**Comment by sozezzo** [comment]
- There is only 5 days of monitoring data.
- I have installed in dev, staging, QA, and test environment without problems, but in these environments, there is no intensive use of the broker service, nor a high data flow.
- I cannot guarantee that to aggregation to auto or few minutes or hours, and the monitoring **must** not affect the sql server.


to-do list:
- Install another sql server (central repository) to connect with GRAFANA to analyze the data.
- Decrease the retention to 2 hours or less, just keep data for monitoring in real time.
- (try) Change the broker solution to stop when it is overloaded. (It is better to lose monitoring data than production data.)
-- or install a watchdog.

_I will be back with my **results**._

**Comment by marcingminski** [comment]
Can you please raise this as a new issue. This discussion has been whether to implement the broker solution. If you’re facing an issue with how it’s been implemented please create a new issue because no one is ever going to look at this closed issue. I only know that you’re posting here because GitHub sends me emails. Thanks.
