### ISSUE TITLE
Central Repository - error fetching data via linked server

### ISSUE THREAD

**Issue by daniellohmann** [marcingminski/sqlwatch#183]
**Describe the bug**
Pulling data for table dbo.sqlwatch_logger_system_configuration_scd throws "Invalid column name 'snapshot_time'." in profiler and will not get any data.
import_status =ERROR in dbo.sqlwatch_meta_repository_import_status.

**To Reproduce**
1. install new sqlwatch database 
2. exec usp_sqlwatch_config_repository_add_remote_instance to add a remote instance for pulling data via linked server

**Expected behavior**
Table data should be pulled to central repo without errors

**Windows Server (please complete the following information):**
Windows Server 2016

**SQL Server (please complete the following information):**
 - SQL Version: SQL Server 2017 CU 19
 - SQL Edition: Enterprise

**SQLWATCH version (from DACPAC or from sysinstances)**
 - 2.5.7460.35921

**Comment by marcingminski** [comment]
I think the following needs to happen:

1. We need dependency for `[dbo].[sqlwatch_logger_system_configuration_scd]` as it's a child of `[dbo].[sqlwatch_logger_system_configuration]`
2. The `[dbo].[sqlwatch_logger_system_configuration_scd]` must not be in the logger group as it's not a logging table. The actual logging table is `[dbo].[sqlwatch_logger_system_configuration]` and SC is the meta table providing additional information. 

All logger tables are delta loaded and require snapshot_time column, this one does not have it. Meta tables are loaded in full every time. 

I will make those changes
