### ISSUE TITLE
Invalid column name 'last_backup_finish_date'.

### ISSUE THREAD

**Issue by simonwhybrow-cbre** [marcingminski/sqlwatch#191]
**Describe the bug**
Since upgrading to 2.6 getting error in the check for latest backup

Check ID -17 is failing with:

```sql
Invalid column name 'last_backup_finish_date'.
```

The code being run has an incorrect column name in it:

```sql
select @output=isnull(max(datediff(minute,last_backup_finish_date,getdate())),999)
from sys.databases d
left join msdb.dbo.backupset bs
	on bs.database_name = d.name
	and bs.type = 'L'
where d.recovery_model_desc <> 'SIMPLE'
and d.name not in ('tempdb')
```

```last_backup_finish_date``` should be ```backup_finish_date```

As discussed in https://github.com/marcingminski/sqlwatch/issues/179 I believe these check will be updated in the next major release, but may need a hotfix to resolve the above.
 
**SQLWATCH version (from DACPAC or from sysinstances)**
| Source | Version |
|----------|-----------|
| Dacpac version | 2.6.7507.41159 |
| sqlwatch_app_version | 2.5.7507.41097 |

Seems there is also a mismatch when updating the sqlwatch_app_version table

**Comment by marcingminski** [comment]
Pants. Thanks. I know how this happened, I will fix it.

**Comment by simonwhybrow-cbre** [comment]
No worries.

Once it's fixed it then behaves the same as the full backup, by alerting all the time due to the max value being selected for the oldest backup. 
Seems to be fixed in https://github.com/marcingminski/sqlwatch/issues/179 though.

**Comment by marcingminski** [comment]
Yeah that was meant to be ported from #179 as a hot fix. I must have broken it. 
I need to build automated testing as it's getting more and more difficult to stay on top of it.
