### ISSUE TITLE
Check -3, CPU utilization calculates wrong values (too low)

### ISSUE THREAD

**Issue by daniellohmann** [marcingminski/sqlwatch#193]
**Describe the bug**
Check -3 calculates wrong values, because there are 2 entries (sql and system)

**To Reproduce**
look at your data in dbo.sqlwatch_logger_check and [dbo].[sqlwatch_logger_perf_os_performance_counters]

**Expected behavior**
check should calculate correct values

**Screenshots**
![image](https://user-images.githubusercontent.com/40454010/88685882-bf67bb00-d0f6-11ea-8667-68187292cc0a.png)

**Comment by marcingminski** [comment]
This has been merged some time ago. Closing the issue - if you still encounter problems please let me know so we can reopen it.
