### ISSUE TITLE
Cannot install properly - Get deployment failed Error SQL72014 (Possible relation to #191?)

### ISSUE THREAD

**Issue by MrGoodbyte** [marcingminski/sqlwatch#198]
**Did you check DOCS to make sure there is no workaround?** Yes
https://sqlwatch.io/docs/

**Describe the bug**
I tried to install SQLWatch on a server to evaluate it. This server has never had SQLWatch on it before. I get the following error
![image](https://user-images.githubusercontent.com/32943438/90373018-a67a7600-e0b4-11ea-86a6-f298ddf0d0fb.png)

Error SQL72014: .Net SqlClient Data Provider: Msg 50000, Level 16, State 1, Procedure usp_sqlwatch_internal_run_job,
Line 61 Job 'SQLWATCH-INTERNAL-CHECKS' has not finished successfuly or the state is not known.

Due to the fact that it is in the SQLWATCH-INTERNAL-CHECKS job that has the bug described in #191 , I suspect that it might be related but I could also be making a massive stretch :-) 

I tried to rerun the installation by uninstalling first and I get an error complaining that the DACPAC is not registered
WARNING: [15:59:44][Uninstall-DbaSqlWatch] Failed to unpublish SqlWatch DACPAC from master on [<SERVERNAME>]. |
DacInstance with the specified instance_id does not exist.

**To Reproduce**
1. Run Install-DBASQLWatch with your servername and a new database name and it will return the error

**Expected behavior**
I expect it to be installed and the DACPAC correctly registered

**Screenshots**
Screenshot as above

**Windows Server (please complete the following information):**
Windows Server 2016 Datacenter

**SQL Server (please complete the following information):**
Microsoft SQL Server 2016 (SP2-CU8) (KB4505830) - 13.0.5426.0 (X64)   Jul 21 2019 21:16:47   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
Microsoft SQL Server Management Studio						14.0.17277.0
Microsoft Analysis Services Client Tools						14.0.1016.262
Microsoft Data Access Components (MDAC)						10.0.14393.0
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.14393.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.14393
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 Powershell downloads the latest release I believe
 
**Additional context**

**Comment by marcingminski** [comment]
Thanks. This will be fixed in 3.x
At the end of the deployment, all jobs are being executed and when they fail, the impression is that the whole deployment failed.
You can just leave it as is and it should be good.
