### ISSUE TITLE
usp_sqlwatch_logger_system_configuration key violation

### ISSUE THREAD

**Issue by marcingminski** [marcingminski/sqlwatch#200]
`exec dbo.usp_sqlwatch_logger_system_configuration` threw PK violation error:

```
Msg 2627, Level 14, State 1, Procedure usp_sqlwatch_logger_system_configuration, Line 64 [Batch Start Line 0]
Violation of PRIMARY KEY constraint 'pk_sqlwatch_logger_system_configuration_scd'. Cannot insert duplicate key in object 'dbo.sqlwatch_meta_system_configuration_scd'. The duplicate key value is (15, SQL-1, Aug 21 2020  8:06AM).
```
This happened after changing configuration earlier in the day

**Comment by mike-halford** [comment]
Also started to get error. This follows NO system changes

Executed as user: *****. Violation of PRIMARY KEY constraint 'pk_sqlwatch_logger_system_configuration_scd'. Cannot insert duplicate key in object 'dbo.sqlwatch_logger_system_configuration_scd'. The duplicate key value is (78, *****\*****, Sep 22 2020  8:58AM). [SQLSTATE 23000] (Error 2627).  The step failed.

***** replaces private username and server name data.

**Comment by marcingminski** [comment]
Wonder if @schenkfab could look into this, he originally wrote this piece of code.

**Comment by mike-halford** [comment]
Is there any update on this @marcingminski @schenkfab ?

**Comment by SiavashGolchoobian** [comment]
Hi, the solution is as below:
modify [dbo].[usp_sqlwatch_logger_system_configuration] stored procedure and find below line:

```
INSERT INTO [dbo].[sqlwatch_meta_system_configuration_scd] (sql_instance, sqlwatch_configuration_id, value, value_in_use, valid_from, valid_until)
SELECT v.sql_instance, m.sqlwatch_configuration_id, v.value, v.value_in_use, @snapshot_time, NULL
```
Then replace it with below code:
```
INSERT INTO [dbo].[sqlwatch_meta_system_configuration_scd] (sql_instance, sqlwatch_configuration_id, value, value_in_use, valid_from, valid_until)
SELECT DISTINCT v.sql_instance, m.sqlwatch_configuration_id, v.value, v.value_in_use, @snapshot_time, NULL
```

**Comment by SiavashGolchoobian** [comment]
> 
> 
> `exec dbo.usp_sqlwatch_logger_system_configuration` threw PK violation error:
> 
> ```
> Msg 2627, Level 14, State 1, Procedure usp_sqlwatch_logger_system_configuration, Line 64 [Batch Start Line 0]
> Violation of PRIMARY KEY constraint 'pk_sqlwatch_logger_system_configuration_scd'. Cannot insert duplicate key in object 'dbo.sqlwatch_meta_system_configuration_scd'. The duplicate key value is (15, SQL-1, Aug 21 2020  8:06AM).
> ```
> 
> This happened after changing configuration earlier in the day

Hi, the solution is as below:
modify [dbo].[usp_sqlwatch_logger_system_configuration] stored procedure and find below line:

```
INSERT INTO [dbo].[sqlwatch_meta_system_configuration_scd] (sql_instance, sqlwatch_configuration_id, value, value_in_use, valid_from, valid_until)
SELECT v.sql_instance, m.sqlwatch_configuration_id, v.value, v.value_in_use, @snapshot_time, NULL
```
Then replace it with below code:
```
INSERT INTO [dbo].[sqlwatch_meta_system_configuration_scd] (sql_instance, sqlwatch_configuration_id, value, value_in_use, valid_from, valid_until)
SELECT DISTINCT v.sql_instance, m.sqlwatch_configuration_id, v.value, v.value_in_use, @snapshot_time, NULL
```
