### ISSUE TITLE
dacpac files missing

### ISSUE THREAD

**Issue by Jakub-prg** [marcingminski/sqlwatch#211]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

YES and I did not find anything

**Describe the bug**
Any of the versions except 1.0 are missing dacpac file. Therefore installation and upgrade is failing all the time. 
Also BI dashboard report from version 2.6 is not working on version 1.0 database.
Am I doing something wrong? Should the dacpac be generated on my side?
[Install-DbaSqlWatch] DACPAC failed to publish to SQLWatch_Test on xxxxxxxxxxx. | Cannot bind argument to parameter 'Path' because it is an empty string.

**Expected behavior**
I would expect to deploy dacpac file, or use powershell, instead nothing is working. 

**Windows Server (please complete the following information):**
 - OS Version: [Windows 2012 R2]

**SQL Server (please complete the following information):**
 - SQL Version: SQL Server 2014
 - SQL Edition:  Enterprise
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here:
Microsoft SQL Server Management Studio						12.0.6118.4
Microsoft Analysis Services Client Tools						12.0.6118.4
Microsoft Data Access Components (MDAC)						6.3.9600.17415
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.9600.19781
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.9600
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 1.0.6827.34601

Thank you a lot for your effort doing this.

**Comment by Jakub-prg** [comment]
Sorry for my noob issue. I found out that the file is located in 2.5 version.

**Comment by marcingminski** [comment]
No problem. For the reference, the relevant documentation is here: 
https://docs.sqlwatch.io/installation/getting-started/ 
https://docs.sqlwatch.io/installation/alternative-installation/
