### ISSUE TITLE
SQLWatchImport - invalid column_name sql user

### ISSUE THREAD

**Issue by 23lejoy** [marcingminski/sqlwatch#216]
**Describe the bug**
When i try to register the remoteinstance as followed:
SqlWatchImport.exe --add -s SVSQLTEST01 -d SQLWATCH

I receive the following output:
2020-11-05 15:23:48.458 DEBUG Checking if Central Repository is online (Thread: 1)
Invalid column name 'sql_user'.

This column does not exist in the sqlinstance table nor it is expected when using Windows Authentification - even providing sql user and password during the import throws the above error which is clear when the field is not there.

**Expected behavior**
I just wanted to register remote instances for the data import in central repos.

msdb.dbo.sysdac_instances:
SQLWatch Version:         2.6.7507.41159       

SQLImport version:
C:\Scripts\SQLServer\SQLWATCH 2.6\SqlWatchImport>SqlWatchImport.exe --version
SQLWATCH Remote Instance Importer 1.1.7614.24323

**Comment by marcingminski** [comment]
The column `sql_user` was added in version 3.0 and so was the `SqlWatchImport.exe`. You must be using version 3.0 for these to work but from what I can see, you are using 2.6. Closing as not an issue.

**Comment by 23lejoy** [comment]
Can you tell me why i have an old version?
I used latest dbatools version for installing sqlwatch.

How can i  upgrade?

**Comment by marcingminski** [comment]
Sure. The 2.6 is the latest version as far as the official and working release goes. The 3.0 is still work in progress and not officially released yet.

Releases are here: https://github.com/marcingminski/sqlwatch/releases and contain the source code and compiled application where applicable.

If you want to give 3.0 a go, you'd need to pull the 3.x branch and deploy database from Visual Studio.

**Comment by 23lejoy** [comment]
ahh thanks now i understand.. is there a proposal time at the end of the road for public v3.0?

As i am not that fimiliar with Github nor VS deployments I am in need of the public version :-)

**Comment by marcingminski** [comment]
Yeah was hoping soon. I got sidetracked with other things recently and have not spent too much time on sqlwatch. I may do a pre-release soon so then you can install with dbatools with the `-PreRelease` switch. Watch this space, or our user forum for updates.

**Comment by 23lejoy** [comment]
Another question from my side: if i switch datasource in the template for the pbi report pointing to the repository it wont get refreshed: queries are blocked somehow. Do you have an idea how to fix this?I got repos working with v3a deployment by the way.Thanks for your assistance:-)Gesendet mit der WEB.DE Mail AppAm 05.11.20 um 22:57 schrieb Marcin Gminski
                
            
            
                
                    Von: "Marcin Gminski" <notifications@github.com>Datum: 5. November 2020An: "marcingminski/sqlwatch" <sqlwatch@noreply.github.com>Cc: "23lejoy" <fr4g-em@web.de>,"Author" <author@noreply.github.com>Betreff: Re: [marcingminski/sqlwatch] SQLWatchImport - invalid column_name sql user (#216)
                
                
Yeah was hoping soon. I got sidetracked with other things recently and have not spent too much time on sqlwatch. I may do a pre-release soon so then you can install with dbatools with the -PreRelease switch. Watch this space, or our user forum for updates.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/marcingminski/sqlwatch/issues/216#issuecomment-722669191",
"url": "https://github.com/marcingminski/sqlwatch/issues/216#issuecomment-722669191",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by marcingminski** [comment]
Can you provide more details please? Are you getting any errors? Have you disabled privacy as in https://docs.sqlwatch.io/dashboard/powerbi/#privacy?

**Comment by 23lejoy** [comment]
Hi there,I have latest power bi desktop version running.Steps as followed:- I open the latest powerbi template uploaded on github - i edit the parameter datasource from example pointing to my repository databaseWhen i click on apply changes it starts refreshing data/report - this is where the error occurs:Look screenshots for details.This happens everytime when i want to refresh the data after editing source parameter from example to my local sqlwatch db or repository.I have disabled privacy as mentioned in this link beforeGesendet mit der WEB.DE Mail AppAm 06.11.20 um 10:44 schrieb Marcin Gminski
                
            
            
                
                    Von: "Marcin Gminski" <notifications@github.com>Datum: 6. November 2020An: "marcingminski/sqlwatch" <sqlwatch@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"23lejoy" <fr4g-em@web.de>Betreff: Re: [marcingminski/sqlwatch] SQLWatchImport - invalid column_name sql user (#216)
                
                
Can you provide more details please? Are you getting any errors? Have you disabled privacy as in https://docs.sqlwatch.io/dashboard/powerbi/#privacy?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/marcingminski/sqlwatch/issues/216#issuecomment-722983558",
"url": "https://github.com/marcingminski/sqlwatch/issues/216#issuecomment-722983558",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by marcingminski** [comment]
Can you paste the screenshot here, making sure it shows the actual error please?
