### ISSUE TITLE
WARNING: [21:14:16][Publish-DbaDacPackage] Could not load profile. | Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken

### ISSUE THREAD

**Issue by seadba** [marcingminski/sqlwatch#219]
hello, running the following cmd in ps7/6 raises following issue 

Install-DbaSqlWatch -SqlInstance $server -Database dbatools -SqlCredential SA

WARNING: [21:14:16][Publish-DbaDacPackage] Could not load profile. | Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken   The system cannot find the file specified.

**Comment by marcingminski** [comment]
Looks like one for dbatools to look into.
Did you run it in verbose mode to see why it cannot load the file?

**Comment by seadba** [comment]
yes, looks like issue for dbatools  - thanks for fast feedback

https://github.com/sqlcollaborative/dbatools/issues/6567

VERBOSE: Performing the operation "Unpacking zipfile" on target "xxlt1".
VERBOSE: [09:55:32][Install-DbaSqlWatch] Unblocking C:\Users\AppData\Roaming\PowerShell\dbatools\2.6.7507.41159\SQLWATCH.2.6.zip
VERBOSE: [09:55:32][Install-DbaSqlWatch] Extracting C:\Users\AppData\Roaming\PowerShell\dbatools\2.6.7507.41159\SQLWATCH.2.6.zip to C:\Users\AppData\Roaming\PowerShell\dbatools\2.6.7507.41159
VERBOSE: [09:55:32][Install-DbaSqlWatch] Deleting C:\Users\AppData\Roaming\PowerShell\dbatools\2.6.7507.41159\SQLWATCH.2.6.zip
VERBOSE: Performing the operation "Installing SqlWatch on dbatools" on target "SQLTest4\MSSQLSERVER17".
VERBOSE: [09:55:34][New-DbaDacProfile] Writing to C:\Users\AppData\Roaming\PowerShell\dbatools\2.6.7507.41159\MSSQLSERVER17-dbatools-publish.xml
WARNING: [09:55:34][Publish-DbaDacPackage] Could not load profile. | Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken='. The system cannot find the file specified.

**Comment by seadba** [comment]
thanks - just reverted to ps5 - that worked -
