### ISSUE TITLE
pbx file reports as corrupted

### ISSUE THREAD

**Issue by seadba** [marcingminski/sqlwatch#220]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**

**To Reproduce**
1. Go to..
2. Click this..

**Expected behavior**

**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: [e.g. Windows 2012 R2]

**SQL Server (please complete the following information):**
 - SQL Version: [e.g. SQL Server 2016 SP1]
 - SQL Edition: [e.g. Enterprise]
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here:
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 1.0.0.0
 
**Additional context**

**Comment by seadba** [comment]
hello, i downloaded the pbx from git and on opening i get the following error   
SQLWATCH.dashboard.20200820.pbx cant be opened - either the file is encrypted or corrupted

**Comment by marcingminski** [comment]
Try downloading again. The file isn't encrypted for sure so must have gotten corrupted or maybe you just need to upgrade your local PBI Desktop.

**Comment by seadba** [comment]
ok, i tried again on 2 machines , 1 with a new install of desktop - still same issue - also i couldnt find it in the dbatools install - i will keep trying - thanks

**Comment by marcingminski** [comment]
Can you open any other pbx downloaded from the internet? Maybe try some from: https://community.powerbi.com/t5/Desktop/Microsoft-Samples-PBX-File/td-p/134493

**Comment by seadba** [comment]
yes, no problem with other files - that link leads to 404 but i was able to open the pbix from this site with no issues  https://docs.microsoft.com/en-us/power-bi/create-reports/sample-covid-19-us
