### ISSUE TITLE
Error installing package on SQL Server for Linux through dacpac and dbatools

### ISSUE THREAD

**Issue by diegombt** [marcingminski/sqlwatch#221]
**Describe the bug**
 - I installed _sqlwatch_ firstly through dacpac and get this error, then I enabled SQL Server Agent and restarted the service and the virtual machine (following [this steps](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-sql-agent?view=sql-server-ver15#EnableAgentAfterCU4)). Tried again but didn't work. Finally, I removed the package (following [this steps](https://docs.sqlwatch.io/installation/removal/)) and tried again with dbatools, but error persists.

**To Reproduce**
 - I used **Deploy Data-Tier Application** on _Management Studio_ and **DbaTools**.

**Expected behavior**
 - Correctly deployed package

**Screenshots**
![image](https://user-images.githubusercontent.com/4006383/98731294-854fbb80-236b-11eb-95d7-ba5d5ef4f182.png)
![image](https://user-images.githubusercontent.com/4006383/98731225-68b38380-236b-11eb-9793-51bf02769bcc.png)

**Enabled SQL Server Agent**
![image](https://user-images.githubusercontent.com/4006383/98734677-50923300-2370-11eb-91f6-1ecdf5fa4601.png)

**Server:**
 - Linux ([KDE neon](https://en.wikipedia.org/wiki/KDE_neon) User Edition 5.20) - Ubuntu based

**SQL Server:**
 - SQL Version: 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64)
 - SQL Edition: Developer
 
**SQL Server Management Studio:**
```
SQL Server Management Studio                      15.0.18357.0
SQL Server Management Objects (SMO)               16.100.44091.28
Microsoft Analysis Services Client Tools          15.0.19260.0
Microsoft Data Access Components (MDAC)           10.0.19041.1
Microsoft MSXML                                   3.0 6.0 
Microsoft .NET Framework                          4.0.30319.42000
Operating System                                  10.0.19042 
```

**SQLWATCH version**
 - 2.6

**Error Log**
[deployment_error.txt](https://github.com/marcingminski/sqlwatch/files/5520110/deployment_error.txt)

**Comment by marcingminski** [comment]
Agent jobs are run as part of the deployment, however, sometimes the execution does not return a clear status even though the job has run successfully. Can you see if jobs have actually been deployed?

**Comment by marcingminski** [comment]
In addition, could try 3.x please?

**Comment by diegombt** [comment]
Hi @marcingminski 

Sorry I stopped trying SQL on linux and I forget this issue. So trying again I did some research and found that **SQL Agent** was not running, even when it should be active after the service was installed and successfully started (I can see it active on SSMS, maybe this is a bug).

Even, I tried [this steps](https://www.sqlservercentral.com/forums/topic/sql-server-agent-not-running-on-linux) but nothing seems to work!

I'll close this issue, but if I can resolve it, I'll put the solution here. Thank you very much, greetings!

**Comment by jjjan** [comment]
not working on linux sql server even with version 3.x !!!

**Comment by marcingminski** [comment]
> not working on linux sql server even with version 3.x !!!

Can you be more specific what is not working?

**Comment by jjjan** [comment]
> > not working on linux sql server even with version 3.x !!!
> 
> Can you be more specific what is not working?

i check mysql and except hard disk other things are working.

thanks for replay
