### ISSUE TITLE
Bug capturing performance data on case sensitive collations

### ISSUE THREAD

**Issue by MrGoodbyte** [marcingminski/sqlwatch#222]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

Yes, I searched Github and sqlwatch docs

**Describe the bug**

The table [sqlwatch_config_performance_counters] defines the counters for CPU as follows
Win32_PerfFormattedData_PerfOS_Processor	SQL	Idle Time %	NULL	1
Win32_PerfFormattedData_PerfOS_Processor	SQL	Processor Time %	NULL	1
Win32_PerfFormattedData_PerfOS_Processor	System	Processor Time %	NULL	1

However when usp_sqlwatch_logger_performance does the join for this it uses the values all in lowercase as follows:
`select 
				 [object_name] = 'win32_perfformatteddata_perfos_processor'
				,[counter_name] = 'Processor Time %'
				,[instance_name] = 'sql'
				,[cntr_value] = 39
				,[cntr_type] = 65792
			union all
			select 
				 [object_name] = 'win32_perfformatteddata_perfos_processor'
				,[counter_name] = 'Idle Time %'
				,[instance_name] = '_total'
				,[cntr_value] = 60
				,[cntr_type] = 65792
			union all
			select 
				 [object_name] = 'win32_perfformatteddata_perfos_processor'
				,[counter_name] = 'Processor Time %'
				,[instance_name] = 'system'
				,[cntr_value] = (100-60-39)
				,[cntr_type] = 65792`

(I also happened to notice that the 'IDLE Time %' in the table has an instance of SQL whereas the code adds _total as the instance in the union. I have not yet determined if this causes a problem somewhere)

The problem here is because the database collation is Latin1_General_BIN everything is case sensitive and this causes check_id -3 to return a null value when checking performance_counter_id 610 causing the following error in the sqlwatch_app_log table
process_name	process_stage	process_message	process_message_type	spid	process_login	process_user	ERROR_NUMBER	ERROR_SEVERITY	ERROR_STATE	ERROR_PROCEDURE
usp_sqlwatch_internal_process_checks	5980A79A-D6BC-4BA0-8B86-A388E8DB621D	Unable to evaluate thresholds because Check (Id: -3) has returned NULL value
--- Query -------------------------------------------------
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON 
SET ANSI_WARNINGS OFF
select @output=avg(pc.cntr_value_calculated)
from [dbo].[sqlwatch_logger_perf_os_performance_counters] pc
inner join [dbo].[sqlwatch_meta_performance_counter] mpc
	on pc.sql_instance = mpc.sql_instance
	and pc.performance_counter_id = mpc.performance_counter_id
where mpc.sql_instance = @@SERVERNAME
  and object_name = 'win32_perfformatteddata_perfos_processor'
  and counter_name = 'Processor Time %%'
and snapshot_time > '2020-11-23 09:34:45.163'	ERROR	72	MYOB\auprd.arcoltp.agt	dbo	50000	16	1	dbo.usp_sqlwatch_internal_process_checks

**To Reproduce**
1. Setup a database instance with Latin1_General_BIN as the server collation
2. Compile SQLWatch from source using Latin1_General_BIN
3. Apply fixes for checks -17 & -18
4. Check the sqlwatch_app_log and find that check -3 is returning a null value

**Expected behavior**

I expect that text comparisons are idempotent and return the same results whether the database infrastructure is set to Case sensitive or Case insensitive

**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: Windows Server 2019

**SQL Server (please complete the following information):**
 - SQL Version: Microsoft SQL Server 2017 (RTM-CU22) (KB4577467) - 14.0.3356.20
 - SQL Edition: Enterprise
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here: Microsoft SQL Server Management Studio						14.0.17277.0
Microsoft Analysis Services Client Tools						14.0.1016.262
Microsoft Data Access Components (MDAC)						10.0.14393.0
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.14393.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.14393
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 2.6
 
**Additional context**
I was considering modifying the values in sqlwatch_config_performance_counters to match but don't know what might fail elsewhere

**Comment by marcingminski** [comment]
Hi Thank you. I think case sensitivity was mentioned in the past but I have not tested it. Good catch. I will keep this in mind for 3.x version.

**Comment by marcingminski** [comment]
The `Win32_PerfFormattedData_PerfOS_Processor` is an exception as it's an OS counter so it does not have a concept of a SQL instance hence, we're hardcoding as `_total` for no better option.
