### ISSUE TITLE
PBI Dashboard - Loading blocked by failures with other queries

### ISSUE THREAD

**Issue by carl33p** [marcingminski/sqlwatch#223]
**Describe the bug**
Error connecting the PBI Dashboard to my SQLWATCH database.  Fails to "Apply changes".  Notice the error lines I bold which may be the root issue.  

Here is the entire error text.  See screenshots as well. 
- Apply query changes
- Dim Server
- Loading blocked by failures with other queries.
- Dim Environment
- Loading blocked by failures with other queries.
- Dim Database
- Loading blocked by failures with other queries.
- Dim Master File
- Loading blocked by failures with other queries.
- Dim Table
- Loading blocked by failures with other queries.
- Dim Index
- Loading blocked by failures with other queries.
- Wait Statistics
- Loading blocked by failures with other queries.
- Performance Counters
- Loading blocked by failures with other queries.
- Performance Counters Analyser Current
- Loading blocked by failures with other queries.
- Performance Counters Analyser Baseline 1
- Loading blocked by failures with other queries.
- Performance Counters Analyser Baseline 2
- Loading blocked by failures with other queries.
- Performance Counters Analyser Baseline 3
- Loading blocked by failures with other queries.
- Process Memory
- Loading blocked by failures with other queries.
- Memory Clerks
- Loading blocked by failures with other queries.
- File Statistics
- Loading blocked by failures with other queries.
- Schedulers
- Loading blocked by failures with other queries.
- XE IO Subsystem
- Loading blocked by failures with other queries.
- XE Query Processing
- Loading blocked by failures with other queries.
- XE Query Waits
- Loading blocked by failures with other queries.
- Blockers
- Loading blocked by failures with other queries.
- WhoIsActive
- Loading blocked by failures with other queries.
- File Statistics Sankey File to Disk
- Loading blocked by failures with other queries.
- Missing Index Stats
- Loading blocked by failures with other queries.
- Index Statistics
- Loading blocked by failures with other queries.
- Index Histogram
- Loading blocked by failures with other queries.
- Disk Utilisation DB
- Loading blocked by failures with other queries.
- Disk Utilisation OS
- Loading blocked by failures with other queries.
- Dim Time Server
- Loading blocked by failures with other queries.
- Dim Agent Jobs
- Loading blocked by failures with other queries.
- Dim Agent Job Steps
- Loading blocked by failures with other queries.
- Disk Utilisation Table
- Loading blocked by failures with other queries.
- Agent History
- Loading blocked by failures with other queries.
- Dim OS Volume
- Loading blocked by failures with other queries.
- Dim Missing Index
- Loading blocked by failures with other queries.
- **File Statistics Sankey Database to File**
- **The column 'database_name' of the table wasn't found.**
- Dim Check
- Loading blocked by failures with other queries.
- Checks
- Loading blocked by failures with other queries.
- Dim Perf Counter Instance
- Loading blocked by failures with other queries.
- Dim Time
- Loading blocked by failures with other queries.

**To Reproduce**
1. Open SQLWATCH Dashboard 20200820.pbix
2. Transform Data -> Edit parameters
3. I put my computer name in the SQL Instance input field.  (same connection info works fine in SSMS)
4. Apply Changes

**Expected behavior**
The Power BI report should load data from my database.

**Screenshots**
[Server/DB Config screenshot](https://ibb.co/BtXx8jK)
[PBI error full screenshot](https://ibb.co/3zW4M4G)

Power BI version:
Version: 2.87.923.0 64-bit (November 2020)

Windows and SQL Version/Edition:
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)  Developer Edition (64-bit) on Windows 10 Pro
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
SQL Server Management Studio						15.0.18358.0
SQL Server Management Objects (SMO)						16.100.44091.28
Microsoft Analysis Services Client Tools						15.0.19260.0
Microsoft Data Access Components (MDAC)						10.0.19041.1
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.19041
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 2.5.7507.41097
 
**Additional context**
I have never used SQLWATCH until yesterday.  I have installed the latest everything.  This is being tested on my local laptop.

**Comment by carl33p** [comment]
I was able to load your old PBI dashboard fine: SQLWATCH Dashboard 20200528.pbix

**Comment by marcingminski** [comment]
Looks like you are trying to use newer version of the dashboard with the older version of the database.
Did you get the dashboard from the release, or from the repository?

**Comment by 23lejoy** [comment]
i had the same problem once, therefore because i didnt managed to get the pbi dashboards working with refreshing data i dropped sqlwatch.io and waiting for the new version 3 with grafana integration.  And i tried all released dashboards even the latest and the last one made especially for version 2.6 - refreshing data was not working with the same error like you receive @carl33p

**Comment by carl33p** [comment]
@marcingminski - It isn't intuitive that one would need to match the versions of each.  
I installed with dbatools, and expected the latest dashboard to be compatible.  Explicitly labeling and linking to the dashboard versions on your website would make it all simple and intuitive to find.  
Either way, thanks for building out such an amazing product.  The PBI report is mind-blowing what you've done with it.

**Comment by marcingminski** [comment]
Every release contains corresponding dashboard. 
https://github.com/marcingminski/sqlwatch/releases
if you are installing with dbatools, the included dashboard is also pulled and extracted via dbatools.
Looking at the 2.6 release, it does indeed not contain the PBI which is a problem with this particular release rather than the overall process.
