### ISSUE TITLE
Power BI data loading raise error because of missing vw_sqlwatch_report_fact_xes_waits_stats

### ISSUE THREAD

**Issue by SiavashGolchoobian** [marcingminski/sqlwatch#226]
**Describe the bug**
In version 3.x power bi report, you encountered error when loading data.

**To Reproduce**
1. Open existed SQLWATCH Power BI Report
2. Go to "Queries" menu, select "Transform Data", Click on "Edit Parameters", set your SQL Instance and click on "OK"
3. When you "Apply Changes" you encountered with error because of data refresh issue.

**Expected behavior**
In correct situation we expect that Power BI report get refreshed without any error after Applying Changes.

**Solution**
Go to "Queries" menu, select "Transform Data", select "Transform Data" again and from new opened window select "XE Query Waits" from left pane (Queries), then from right pane (Applied Steps) click on "Navigation" step and change it's contents (current specified view name is not compatible with version 3.x and you don't have "vw_sqlwatch_report_fact_xes_waits_stats" view any more, then you should replace it with it's new version "vw_sqlwatch_report_fact_xes_wait_events" as below:
= Source{[Schema="dbo",Item="vw_sqlwatch_report_fact_xes_wait_events"]}[Data]

**Windows Server:**
 - OS Version: Windows 2019 Core

**SQL Server:**
 - SQL Version: SQL Server 2019 CU8
 - SQL Edition: Enterprise Core Edition
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
SQL Server Management Studio						15.0.18369.0
SQL Server Management Objects (SMO)						16.100.46041.41
Microsoft Analysis Services Client Tools						15.0.19342.0
Microsoft Data Access Components (MDAC)						10.0.19041.1
Microsoft MSXML						3.0 5.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.19042
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 3.0.7686.42226

**Comment by marcingminski** [comment]
Which version of the PBI were you using?

**Comment by marcingminski** [comment]
Never mind. I found it. Thank you for spotting that. The 3.x is still work in progress so things are expected to not work. However, this was a good catch, I was not aware of it being broken. Thanks

**Comment by SiavashGolchoobian** [comment]
> 
> 
> Which version of the PBI were you using?

It's Power BI Report Server Version: 2.86.1321.0 64-bit (October 2020)

**Comment by Salvo** [comment]
Good afternoon,
I am experiencing the same problem.
I cannot find the view vw_sqlwatch_report_fact_xes_waits_stats, in the database.
Are you in the process of solving it? Is there anything I can help with?

Regards,

Salvo
![Capture](https://user-images.githubusercontent.com/249936/114199504-a6d1c500-9954-11eb-84ec-dce596c6ebc1.JPG)
![Capture2](https://user-images.githubusercontent.com/249936/114200332-64f54e80-9955-11eb-8ef2-9cc07b1ddc03.JPG)

**Comment by marcingminski** [comment]
Hi, this was fixed some time ago. Please make sure you are using the lastest PBI file and database
