### ISSUE TITLE
WhoIsActive job fails when default collation is case sensitive

### ISSUE THREAD

**Issue by Shashtsoh** [marcingminski/sqlwatch#229]
**Did you check DOCS to make sure there is no workaround?**
I could not find the issue in the documentation

**Describe the bug**
On SQL instances with a case-sensitive default collation, the whoisactive logger job will fail.  This is due to the call to run sp_WhoIsActive is executed as "exec sp_whoisactive".  

**To Reproduce**
Install SQLWatch on an instance with a case-sensitive default collation (my server uses SQL_Latin1_General_CP1_CS_AS by default)
Install sp_WhoIsActive
Exec SQLWatch.dbo.sqlwatch_logger_whoisactive

**Expected behavior**
The stored procedure used to run sp_whoisactive should be able to execute it no matter the default server collation.

**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: [e.g. Windows 2012 R2]

**SQL Server (please complete the following information):**
 - 2016SP2CU15
 - Enterprise
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here:
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 2.6
 
**Additional context**
I was able to work around the issue by modifying the procedure to use the correctly capitalized name for sp_whoisactive.  I chose that route, as it seemed simpler than renaming whoisactive to all lower-case, then modifying the calling procedure, which checks for the capitalized version.

**Comment by marcingminski** [comment]
Thanks
