### ISSUE TITLE
Win32_PerfFormattedData_PerfOS_Processor - Idle Time % is not collected

### ISSUE THREAD

**Issue by LionelFremondiere** [marcingminski/sqlwatch#230]
**Describe the bug**
win32_perfformatteddata_perfos_processor - Idle Time % is marked as collected (collect=1) in table [sqlwatch_config_performance_counters] but the view [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters] don't report the counter.

**Windows Server (please complete the following information):**
 - OS Version: Windows 2016 Standard

**SQL Server (please complete the following information):**
 - SQL Version: SQL Server 2014 and SQL Server 2019
 - SQL Edition: Enterprise
 
sqlwatch_version
3.0.7544.33251
 
Issue : Idle Time % is set with instance_name = SQL in config table and in stored procedure usp_sqlwatch_logger_performance Idle Time % is set with instance_name = _total

Solution : update the config table with instance_name = _total
Be careful about case for system with a case sensitive collation.
Personally I prefer to update with _Total in config table and sp.

Thanks for sqlwatch

**Comment by marcingminski** [comment]
Thank you for this.
Do you know if this problem has been introduced in 3.0 or has this existed in previous version too?
Either way, I will investigate it.

Thanks

**Comment by LionelFremondiere** [comment]
Sorry I don't know

**Comment by MrGoodbyte** [comment]
I mentioned this in https://github.com/marcingminski/sqlwatch/issues/222, but didn't describe it very well, and we are using 2.6 so I would say this was not introduced in v3
