### ISSUE TITLE
Dont generate notification actions for checks by template

### ISSUE THREAD

**Issue by KONEL-68** [marcingminski/sqlwatch#235]
Sorry for my english. I'm learning this.

I want send notifications for check templates, but actions don't generates.
Also, for example, if the user database has been dropped. Checks by template are not deleted for it.

Issue here: [dbo].[usp_sqlwatch_internal_expand_checks] in load action templates.
![image](https://user-images.githubusercontent.com/47787046/110764494-cdb8b080-825b-11eb-9ea3-b6e981ea78d6.png)

**Comment by kekcjkee** [comment]
Also, for example, if the user database has been dropped. Checks by template are not deleted for it.
