### ISSUE TITLE
Orphaned Database Checks on dbo.sqlwatch_config_check when Database removed

### ISSUE THREAD

**Issue by steffenengelhamburg** [marcingminski/sqlwatch#236]
There are orphaned Checks for Databases that no longer exist in SQLWatch Database because of Retention Settings.
 I tested the following Way:
Database not listed in sqlwatch_meta_database after Retention for Last Seen Objects
```
SELECT * FROM [dbo].[sqlwatch_meta_database]
```
Database WiedeWorldImporters is not Listed...

In sqlwatch_config_check the Checks are still existing and getting errors like last 'Database WideWorldImporters Data Backup Age'

With the following Statement i get all Checks for Databases (~ Checks based on Templates for Databases) and that corresponding Databases are no longer listed in [sqlwatch_meta_database]

```
USE SQLWATCH
SELECT cc.check_id,
  cc.check_name,
  cc.check_enabled,
  cc.check_template_id
  FROM dbo.sqlwatch_config_check AS cc
  JOIN dbo.sqlwatch_config_check_template AS ct ON ct.check_template_id = cc.check_template_id
  WHERE NOT EXISTS ( 
    SELECT md.database_name,
	    md.sql_instance
    FROM [dbo].[sqlwatch_meta_database] AS md
	WHERE cc.check_name LIKE 'Database ' + md.database_name + '%'
	AND md.sql_instance = @@SERVERNAME
	)
  AND ct.check_name LIKE '%{DATABASE}%'
```

My workaround:
Set all Database Jobs to False that have no Database in sqlwatch_meta_database

```
UPDATE dbo.sqlwatch_config_check
  SET check_enabled = 0
  FROM dbo.sqlwatch_config_check AS cc
  JOIN dbo.sqlwatch_config_check_template AS ct ON ct.check_template_id = cc.check_template_id
  WHERE NOT EXISTS ( 
    SELECT md.database_name,
	    md.sql_instance
    FROM [dbo].[sqlwatch_meta_database] AS md
    WHERE cc.check_name LIKE 'Database ' + md.database_name + '%'
    AND md.sql_instance = @@SERVERNAME
	)
  AND ct.check_name LIKE '%{DATABASE}%'
```

or Delete them

```
DELETE dbo.sqlwatch_config_check
  FROM dbo.sqlwatch_config_check AS cc
  JOIN dbo.sqlwatch_config_check_template AS ct ON ct.check_template_id = cc.check_template_id
  WHERE NOT EXISTS ( 
    SELECT md.database_name,
	    md.sql_instance
    FROM [dbo].[sqlwatch_meta_database] AS md
	WHERE cc.check_name LIKE 'Database ' + md.database_name + '%'
	AND md.sql_instance = @@SERVERNAME
	)
  AND ct.check_name LIKE '%{DATABASE}%'
```

This should be implemented somewhere in the Retention Jobs to remove Jobs that no longer needed or set check_enabled to False.

**Comment by marcingminski** [comment]
Yes, but removing checks is tricky. For example, if someone drops a database by mistake, we want the check to stay to alert us that the database does not longer exist. An option would be to have this parameterised so users can set according to their preference.

**Comment by steffenengelhamburg** [comment]
Hi Marcin,
you are right. That‘s the point, why i suggested to remove the Check only when the database entry is removed from sqlwatch_meta_database.

If the Database is removed by a mistake the entry in this table still exist. When i‘m correct your retention cleanup remove the entry in sqlwatch_meta_database only when the last seen object cleanuptime is reached. Only then my cleanup of Checks will remove this.

Just to be sure: what will happen when a Database is renamed? Will the entry in sqlwatch_meta_database and the Jobs will Change too? Wouldn‘t be better to have a object id column in the sqlwatch_config_check table to have an link, and a trigger in sqlwatch_meta_database to change or delete the check if an update occours?

Greatings from Hamburg
Steffen

**Comment by marcingminski** [comment]
I don't know if you are referring to version 3.x or prior. In version 3.x, there is a concept of automatically managing checks. Before version 3.x there was no link between checks and meta. As you had to do in your query, you're joining on a string `WHERE cc.check_name LIKE 'Database ' + md.database_name + '%'`. Some people may create checks with different names so there is no way to enforce this. 

When database is renamed, it will be registered as a new database and the old database will stay until retention kicks in.

**Comment by steffenengelhamburg** [comment]
Hi Marcin,
i tested on 3.0.9 beta. You are alright :) It's difficult to delete Checks "automatic" after retention kicks in if the Customer implements own checks with other naming schema.

I close this and tell my customers they had to implement an own job to cleanup old checks if the database is deleted.

Thank you much
Steffen

**Comment by steffenengelhamburg** [comment]
Hi Marcin,
i tested on 3.0.9 beta. You are alright :) It's difficult to delete Checks "automatic" after retention kicks in if the Customer implements own checks with other naming schema.

I close this and tell my customers they had to implement an own job to cleanup old checks if the database is deleted.

Thank you much
Steffen

**Comment by marcingminski** [comment]
In version 3.x, when database checks are automatically created via `usp_sqlwatch_internal_expand_checks`, when the database is later deleted, the check for the said database will be returning NULL and thus will be failing with `CHECK ERROR`. I suppose an option would be to delete checks that have been in `CHECK ERROR` state after some period.

Normally, checks will return `OK`, `WARNING` or `CRITICAL` and `CHECK ERROR` is when the check fails to run.
