### ISSUE TITLE
Question about SQL Server collation for SQLWATCH above 3.1 version

### ISSUE THREAD

**Issue by KONEL-68** [marcingminski/sqlwatch#248]
Hello!

_(I am in the process of learning English. Sorry for mistakes.)_

We have an installed SQLWATCH 3.0 (last stable release) on a production environment. We really enjoy using it to monitor our systems with Grafana Dashboards. But sometimes we are testing new versions (pre-release) and faced that on all our systems during installation an error related to collation appeared. One of the examples is in the screenshot. Is it worth living with or will you fix it?

![image](https://user-images.githubusercontent.com/47787046/114043709-344ae180-988f-11eb-80e5-c84e7fdda79e.png)

I understand that this is not a bug and I read the documentation, but there was no such error before. We also saw that an improvement in SqlWatchImport.exe #227 is being prepared, which solves the problem with different collations between remote instances and central repository. Is it planned?

Thanks for your hard work.

**Comment by marcingminski** [comment]
Please read https://docs.sqlwatch.io/known-issues/#collation-conflict
Are you saying this is something introduced in 3.0?

**Comment by KONEL-68** [comment]
> Please read https://docs.sqlwatch.io/known-issues/#collation-conflict
> Are you saying this is something introduced in 3.0?

Yes, I did.
This error does not occur on SQLWATCH 3.0 (from here: [sqlwatch/releases](https://github.com/marcingminski/sqlwatch/releases)). 
This has appeared in the most recent versions. When I just clone the repository to my computer and create dacpac from Visual Studio.

**Comment by marcingminski** [comment]
The 3.0 is the most recent version. Anything in the 3.x branch which has not been released as a Release or Pre-Release is work in progress and not guaranteed to work at all. You are however free to contribute to the project.

**Comment by KONEL-68** [comment]
> The 3.0 is the most recent version. Anything in the 3.x branch which has not been released as a Release or Pre-Release is work in progress and not guaranteed to work at all. You are however free to contribute to the project.

Thank you for your response and patience. I just wanted to know if the situation with collation is planned to change or not.

**Comment by marcingminski** [comment]
Yes the `SqlWatchImport` collation will be handled at some point

**Comment by marcingminski** [comment]
I was able to recreate this error:
```
Error SQL72014: .Net SqlClient Data Provider: Msg 468, Level 16, State 9, Procedure usp_sqlwatch_internal_add_wait_type, Line 10 Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_CI_AS" in the equal to operation.
```

Thank you for this. I will look into it
