### ISSUE TITLE
add ability to process checks on the central repository

### ISSUE THREAD

**Issue by marcingminski** [marcingminski/sqlwatch#250]
Currently it is not possible for central repository to process checks and send alerts for remote instances as each remote instance must process its own checks. 

Each processed check is logged to `sqlwatch_logger_check` which is then imported by the `SqlWatchImporter` 

Now with real-time processing and `SqlWatchImport.exe` being able to import remote data in almost real time, we could be processing checks on the central repository.

Whilst it's easy to expand checks template by `sql_instance` (just needs an outer cursor) we need to change the code to deal with the `sqlwatch_logger_check` as check processing will insert `@@SERVERNAME` as `sql_instance`.

A solution would be to:
1. Change the check processing and add a column to primary key `sql_instance_source`
2. OR, Change the code so it inserts @@SERVER matching the remote instance rather than local instance into the `sqlwatch_logger_check`

Option 1 would be more transparent.

**Comment by marcingminski** [comment]
The same will apply to all the related tables `sqlwatch_meta_check` etc.
Whilst the first option would be more transparent, it would require more changes to the PBI and Grafana dashboards as they all rely on the `sql_instance` to select data for the relevant instsance.

**Comment by steffenengelhamburg** [comment]
Good Morning Marcin,
very cool idea. I think too 1) would be the more consistent way with implementing sql_instance_source.

With extending the views with an additional Case for [sql_instance] Column, there wouldn't be so much changes on the Reporting PBI & Grafana templates nessesary. There's only the need to get rid of usage of the Tables and only use Views of them.

Greetings from Hamburg
Steffen

**Comment by marcingminski** [comment]
I believe the code that builds the checks from templates is now working for multiple instances (commit above) 
I still need to deal with the logger so the entire process does not yet work - just building the checks part

**Comment by marcingminski** [comment]
Actually, I may not need to change anything else but getting the check results from the logger would require a join onto config (or maybe meta in the future):
```
SELECT *
  FROM [dbo].[sqlwatch_logger_check] lc
  inner join [dbo].[sqlwatch_config_check]  cc
  on lc.check_id = cc.check_id
  and lc.sql_instance = cc.target_sql_instance
  where cc.target_sql_instance <> @@SERVERNAME
```

**Comment by marcingminski** [comment]
Actually, I may not need to change anything else but getting the check results from the logger would require a join onto config (or maybe meta in the future):
```
SELECT *
  FROM [DBADMIN].[dbo].[sqlwatch_logger_check] lc
  inner join [dbo].[sqlwatch_config_check]  cc
  on lc.check_id = cc.check_id
  and lc.sql_instance = cc.target_sql_instance
  where cc.target_sql_instance <> @@SERVERNAME
```

**Comment by marcingminski** [comment]
added `[target_sql_instance]` to view `[dbo].[vw_sqlwatch_report_dim_check]`. 
The `[target_sql_instance]` column tells us which instance the check was run against and the `sql_instance` tells us which sql instance it ran on.
For a single "remote" instance they will always be the same but for the central repository, the `sql_instance` will be the central repo (no change) and the `[target_sql_instance]` will be the remote instance imported into the repo

**Comment by marcingminski** [comment]
Having said all this, I am still yet to test it properly but it seems to work ok
