### ISSUE TITLE
SQLWATCH-INTERNAL-CONFIG job : usp_sqlwatch_internal_add_procedure missing

### ISSUE THREAD

**Issue by LionelFremondiere** [marcingminski/sqlwatch#266]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**
The job SQLWATCH-INTERNAL-CONFIG is not created with a step for usp_sqlwatch_internal_add_procedure
The table sqlwatch_meta_procedure without this step is always empty.

**To Reproduce**
1. Download SQLWATCH.3.0.9.23735.20210401135603.zip
2. Install package

**Expected behavior**
Add a step named dbo.usp_sqlwatch_internal_add_procedure which call the stored procedure logically placed after the step dbo.usp_sqlwatch_internal_add_table

**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: Windows 2016 Standard

**SQL Server (please complete the following information):**
 - SQL Version: Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
	Sep 24 2019 13:48:23 
	Copyright (C) 2019 Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here:
 
**SQLWATCH version (from DACPAC or from sysinstances)**
install_sequence	install_date	sqlwatch_version	major	minor	patch	build
1	2021-04-19 12:10:34.0209715 +02:00	3.0.9.18505	3	0	9	18505
 
**Additional context**

**Comment by LionelFremondiere** [comment]
Maybe you could also rename [dbo].[vw_sqlwatch_report_dim_**aget**\_job] to [dbo].[vw_sqlwatch_report_dim_**agent**_job]

**Comment by marcingminski** [comment]
Good catch. thanks!
