### ISSUE TITLE
[New Feature] Capturing Page Life Expectancy 

### ISSUE THREAD

**Issue by ColinDouglas92** [marcingminski/sqlwatch#27]
**Is your feature request related to a problem? Please describe.**
Capturing Page Lift Expectancy will help a user determine if performance issues are related to memory pressure or can be used in general performance tuning.

**Describe the solution you'd like**
Display PLE for a server on the main performance dashboard of the PowerBI template

**Describe alternatives you've considered**
I could see where additional memory performance metrics could create a need for a Memory specific tab, where the Overview tab would just display some higher level metrics (PLE, cache hit rates, etc.), while the Memory tab would include those same metrics + additional memory metrics. This would be the same workflow you see in other enterprise database monitoring solutions.

**Additional context**
This would be rather simple to implement, as PLE can be found by querying the sys.dm_os_ring_buffers. Suggestions for implementation (create new tables/use existing tables/create new sp/edit existing sp, etc) would be great! 

I'm excited to have a chance to contribute to this project. Let me know if you have any questions, comments, concerns. Thanks!

**Comment by ColinDouglas92** [comment]
I just realized this information is already being collected in PerformanceCounters. I'll think of another idea :)

**Comment by marcingminski** [comment]
Hi there, thank you for the suggestion! This is somewhat already implemented through Performance Counters and PLE is being captured by default. If you go to PowerBI and click Activity Graph and expand Counter Names in Power BI you will see PLE. I realise this isn't obvious so I am writing documentation as we speak at https://sqlwatch.io/docs. See if this works for you and if you feel free to feed back. The biggest problem is screen estate and the dashboard to show all this data so some of it is hidden.

![image](https://user-images.githubusercontent.com/8288333/45058005-4046e500-b08f-11e8-88fa-dcea94845104.png)

**Comment by marcingminski** [comment]
ah 10 seconds too late!
