### ISSUE TITLE
DEADLOCK

### ISSUE THREAD

**Issue by LionelFremondiere** [marcingminski/sqlwatch#274]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**
The deadlock happened with usp_sqlwatch_internal_insert_header used in usp_sqlwatch_logger_hadr_database_replica_states and usp_sqlwatch_logger_performance

**To Reproduce**
Let the jobs SQLWATCH-LOGGER-AG and SQLWATCH-LOGGER-PERFORMANCE running and deadlocks happens.

**Expected behavior**
Disable SQLWATCH-LOGGER-AG job if no AG is detected.
This can be done at install or later with usp_sqlwatch_config_create_default_agent_jobs with introducing an AG detection

**Screenshots**

**SQL Server (please complete the following information):**
Microsoft SQL Server 2014 (SP3-CU1) (KB4470220) - 12.0.6205.1 (X64)   Nov 30 2018 02:59:03   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
Microsoft SQL Server 2016 (SP2-CU7) (KB4495256) - 13.0.5337.0 (X64)   May 16 2019 02:24:21   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here:
 
**SQLWATCH version (from DACPAC or from sysinstances)**
install_sequence	install_date	sqlwatch_version	major	minor	patch	build
1	2021-04-21 09:44:04.4650186 +02:00	3.0.9.18505	3	0	9	18505
 
**Additional context**

**Comment by marcingminski** [comment]
Can you give me the deadlock graph and can you try the latest `usp_sqlwatch_internal_insert_header` as some of the locking has been changed.

**Comment by LionelFremondiere** [comment]
Thanks Marcin, I will try the latest usp_sqlwatch_internal_insert_header.
[DeadlockGraph.txt](https://github.com/marcingminski/sqlwatch/files/6365670/DeadlockGraph.txt)

**Comment by marcingminski** [comment]
Did it help?

**Comment by LionelFremondiere** [comment]
Hello Marcin!
Sorry I was in holliday last week.
The latest procedure fix the issue.
Thanks

**Comment by marcingminski** [comment]
Great, I will close this then.
