### ISSUE TITLE
The maximum key length for a clustered index exceeded.

### ISSUE THREAD

**Issue by MikeyBronowski** [marcingminski/sqlwatch#29]
**Describe the bug**
When ran the setup for the first time got to warnings.

**To Reproduce**
1. Go to 'setup.sql'
2. Create 'pk_sql_perf_mon_perf_counters' and 'pk_sql_perf_mon_config_perf_counters'
3. See error
```
Warning! The maximum key length for a clustered index is 900 bytes. The index 'pk_sql_perf_mon_perf_counters' has maximum length of 12008 bytes. For some combination of large values, the insert/update operation will fail.
Warning! The maximum key length for a clustered index is 900 bytes. The index 'pk_sql_perf_mon_config_perf_counters' has maximum length of 1536 bytes. For some combination of large values, the insert/update operation will fail.
```

**Expected behavior**
The key length should be within the limit.

**Additional context**
I can see differences in the type VARCHAR vs NVARCHAR + max size.
```
[object_name] varchar(4000) not null,
[instance_name] varchar(4000) not null,
[counter_name] varchar(4000) not null,
```
as well ass

```
[object_name] nvarchar(256) not null,
[instance_name] nvarchar(256) not null,
[counter_name] nvarchar(256) not null,
[base_counter_name] nvarchar(256) null,
```

The usual object_name won't be longer than 128 characters. 
The instance_name it most likely will be OK with the same length (considering FQDN).
Per MSDN counter_name type is nchar(128).

Unless there is a reason for longer fields, the table could use NVARCHAR(128) or to be safe(?) NVARCHAR(256).

Any thoughts?

**Comment by marcingminski** [comment]
Hi, goot spot, thanks for raising this. I am aware of it but its was low on the to-do list until now :)

**Comment by MikeyBronowski** [comment]
I might have time to look at this later this month. Any particular way you would like to see that?

**Comment by marcingminski** [comment]
Hi Mikey, I got round to look at this. SqlPackage.exe will not attempt to alter column due to potential data loss so the only option will be manual alter, perhaps some data migration out of table -> alter -> back in the table to speed it up. I may leave this for the time being as I am planning on doing maintenance release, no new features just sorting out existing objects.

**Comment by fatherjack** [comment]
@MikeyBronowski What SQL version did you install on?

**Comment by MikeyBronowski** [comment]
@fatherjack can't remember exactly now, but it was either 2017 or 2016.

**Comment by marcingminski** [comment]
This will be non breaking change but one requiring a manual intervention. By default the deployment will abort if there is a chance of any data loss and altering existing column does trigger the abort. 

The intervention will require either running deployment with accepted data loss or altering columns manually prior to the employment. However, the dbatools' Install-DbaSqlWatch does not accept "accept data loss" input variable and therefore will fail. 

```
IF EXISTS (select top 1 1 from [dbo].[sql_perf_mon_perf_counters])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT
```

I will bundle this with other risky changes into version 2.0 of the database.
