### ISSUE TITLE
[Feature Request] Change Check Templates for Backup to be HADR aware

### ISSUE THREAD

**Issue by steffenengelhamburg** [marcingminski/sqlwatch#296]
**Is your feature request related to a problem? Please describe.**
- no Problem: Check Template 3 & 4 are not aware of Backups taken on Secondaries / Primaries due to automated_backup_preference and secondary_role_allow_connections setting of AVG

**Describe the solution you'd like**
Checks need to extended to be aware of AVG setting. Return @output = 0 if Databasebackups taken on secondaries or Primary role. Query need to join Database  to AVG and AG dmv of msdb.

**Describe alternatives you've considered**
This are the possible @output with expected 0 on Nodes with Primary or Secondary AVG Role

| NODE ROLE            | bck Preference     | Secondary_Allow_Connection | expected Output   |
| --------------------- | --------------------- | --------------------- | --------------------- |
| 0 Primary            | 0 Primary          | ----                       | DateDiff | 
| 0 Primary            | 1 Only Secondary   | <> 0                       | 0        | 
| 0 Primary            | 2 Prefer Secondary | <> 0                       | 0        | 
| 0 Primary            | 3 none             | <> 0                       | 0        | 
| 1 Secondary          | 0 Primary          | ----                       | 0        | 
| 1 Secondary          | 1 Only Secondary   | ----                       | DateDiff | 
| 1 Secondary          | 2 Prefer Secondary | = 0                        | 0        | 
| 1 Secondary          | 3 none             | = 0                        | 0        | 

Summary -> Cleanup of Table above
| NODE ROLE            | bck Preference     | Secondary_Allow_Connection | expected Output   |
| --------------------- | --------------------- | --------------------- | --------------------- |
| 0 Primary            | <> 0               | <> 0                       | 0        |
| 1 Secondary          | 0                  | ----                       | 0        | 
| 1 Secondary          | >=2                | = 0                        | 0        | 

HINT for Columns
secondary_role_allow_connections
0 NO
1 READ_ONLY
2 ALL

automated_backup_preference
0 Primary
1 Secondary_Only
2 Secondary (Prefer)
3 none (can be done on All)

**Solution**
**Log Backup Check Template**
```
DECLARE @output NVARCHAR(100);
SELECT @output
    = ISNULL(
                MIN(   CASE
                           WHEN db.recovery_model_desc = 'SIMPLE' THEN
                               0
                           -- when DB is in AVG, Current Node is Secondary and Backup Preference is Primary
                           WHEN HADR_REP.role = 2
                                AND AVG_DESC.automated_backup_preference = 0 THEN
                               0
                           -- when DB is in AVG, Current Node is Secondary and Backup Preference is Prefer Secondary or none (use All) and Secondaries not readable
                           WHEN HADR_REP.role = 2
                                AND AVG_DESC.automated_backup_preference >= 2
                                AND AVG_REP.secondary_role_allow_connections = 0 THEN
                               0
                           -- when DB is in AVG, Current Node is Primary and automated_backup_preference on secondary_only and Secondary is Readable -> suggest Backup is done on Secondary,
                           WHEN HADR_REP.role = 1
                                AND AVG_DESC.automated_backup_preference <> 0
                                AND AVG_REP.secondary_role_allow_connections <> 0 THEN
                               0
                           ELSE
                               DATEDIFF(MINUTE, bs.backup_finish_date, GETDATE())
                       END
                   ),
                9999
            )
FROM [msdb].[sys].[databases] AS db
    LEFT JOIN [msdb].[sys].[dm_hadr_availability_replica_states] AS HADR_REP
        ON db.[replica_id] = HADR_REP.[replica_id]
    LEFT JOIN [msdb].[sys].[availability_replicas] AS AVG_REP
        ON HADR_REP.group_id = AVG_REP.group_id
           AND HADR_REP.[replica_id] = AVG_REP.[replica_id]
    LEFT JOIN [msdb].[sys].[availability_groups] AS AVG_DESC
        ON HADR_REP.[group_id] = AVG_DESC.[group_id]
    LEFT JOIN msdb.dbo.backupset bs
        ON db.name = bs.database_name
           AND bs.type = 'L'
WHERE db.name = '{DATABASE}';
SELECT @output;
```

**Full & Diff Backup Check Template**
```
DECLARE @output NVARCHAR(100);
SELECT @output
    = ISNULL(
                MIN(   CASE
                   WHEN db.name = 'tempdb' THEN
                               0
                           -- when DB is in AVG, Current Node is Secondary and Backup Preference is Primary
                           WHEN HADR_REP.role = 2
                                AND AVG_DESC.automated_backup_preference = 0 THEN
                               0
                           -- when DB is in AVG, Current Node is Secondary and Backup Preference is Prefer Secondary or none (use All) and Secondaries not readable
                           WHEN HADR_REP.role = 2
                                AND AVG_DESC.automated_backup_preference >= 2
                                AND AVG_REP.secondary_role_allow_connections = 0 THEN
                               0
                           -- when DB is in AVG, Current Node is Primary and automated_backup_preference on secondary_only and Secondary is Readable -> suggest Backup is done on Secondary,
                           WHEN HADR_REP.role = 1
                                AND AVG_DESC.automated_backup_preference <> 0
                                AND AVG_REP.secondary_role_allow_connections <> 0 THEN
                               0
                           ELSE
                               DATEDIFF(day, bs.backup_finish_date, GETDATE())
                       END
                   ),
                9999
            )
FROM [msdb].[sys].[databases] AS db
    LEFT JOIN [msdb].[sys].[dm_hadr_availability_replica_states] AS HADR_REP
        ON db.[replica_id] = HADR_REP.[replica_id]
    LEFT JOIN [msdb].[sys].[availability_replicas] AS AVG_REP
        ON HADR_REP.group_id = AVG_REP.group_id
           AND HADR_REP.[replica_id] = AVG_REP.[replica_id]
    LEFT JOIN [msdb].[sys].[availability_groups] AS AVG_DESC
        ON HADR_REP.[group_id] = AVG_DESC.[group_id]
    LEFT JOIN msdb.dbo.backupset bs
        ON db.name = bs.database_name
           AND bs.type <> 'L'
WHERE db.name = '{DATABASE}';
SELECT @output;
```

**Todo on Script.PostDeployment-CreateDefaultChecks.sql**
If you agree i'll create a Commit Request for Change in Script.PostDeployment-CreateDefaultChecks.sql.

Greetings from Hamburg
Steffen

**Comment by marcingminski** [comment]
Hi @steffenengelhamburg Thank you for this. 
I think that would also address this issue: https://github.com/marcingminski/sqlwatch/issues/289 ?
Happy for you to submit PR
