### ISSUE TITLE
Procedure sp_sql_perf_mon_logger, Line 130 Cannot resolve the collation conflict 

### ISSUE THREAD

**Issue by francescovista** [marcingminski/sqlwatch#30]
**Describe the bug**
Installing DACPAC deployment using SSMS I receive this:

```
Could not deploy package.
Error SQL72014: .Net SqlClient Data Provider: Msg 468, Level 16, State 9, Procedure sp_sql_perf_mon_logger, Line 130 Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_CI_AS" in the like operation.
```

**To Reproduce**
1. follow the guide DACPAC deployment using SSMS

**Expected behavior**
It should install, right?

**Screenshots**

![collation](https://user-images.githubusercontent.com/30395256/45124569-ee04e180-b1be-11e8-8d75-e3c500e38ace.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10 Enterprise

SSMS:

Microsoft SQL Server Management Studio						13.0.16106.4
Microsoft Analysis Services Client Tools						13.0.1700.441
Microsoft Data Access Components (MDAC)						10.0.15063.0
Microsoft MSXML						3.0 4.0 6.0 
Microsoft Internet Explorer						9.11.15063.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.15063

**Additional context**
The whole error is:

TITLE: Microsoft SQL Server Management Studio
------------------------------

Could not deploy package.
Error SQL72014: .Net SqlClient Data Provider: Msg 468, Level 16, State 9, Procedure sp_sql_perf_mon_logger, Line 130 Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_CI_AS" in the like operation.
Error SQL72045: Script execution error.  The executed script:
CREATE PROCEDURE [dbo].[sp_sql_perf_mon_logger]
AS
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
DECLARE @product_version AS NVARCHAR (128);
DECLARE @product_version_major AS DECIMAL (10, 2);
DECLARE @product_version_minor AS DECIMAL (10, 2);
DECLARE @sql_memory_mb AS INT;
DECLARE @os_memory_mb AS INT;
DECLARE @memory_available AS INT;
DECLARE @percent_idle_time AS REAL;
DECLARE @percent_processor_time AS REAL;
DECLARE @date_snapshot_current AS DATETIME;
DECLARE @date_snapshot_previous AS DATETIME;
DECLARE @sp_whoisactive_destination_table AS VARCHAR (255);
DECLARE @sql AS NVARCHAR (4000);
SET @product_version = CONVERT (NVARCHAR (128), serverproperty('productversioN'));
SELECT @product_version_major = substring(@product_version, 1, charindex('.', @product_version) + 1),
       @product_version_minor = parsename(CONVERT (VARCHAR (32), @product_version), 2);
SELECT @sql_memory_mb = CONVERT (INT, value)
FROM   sys.configurations
WHERE  name = 'max server memory (mb)';
I
 (Microsoft.SqlServer.Dac)

------------------------------
BUTTONS:

OK
------------------------------

**Comment by marcingminski** [comment]
Interesting. As the error suggests, your server has a different collation to the database. One reason we use DACPAC is to avoid these problems. As a temporary workaround, if you manually create database first:
```sql
CREATE DATABASE [SQLWATCH]
GO
```
It will be created with the default server's collation
If you then deploy DACPAC it should retain original collation.

There is additional parameter as in https://docs.microsoft.com/en-us/sql/tools/sqlpackage to handle collation during the deployment wich you may try if the above still does not work:

> This setting dictates how the database's collation is handled during deployment; by default the target database's collation will be updated if it does not match the collation specified by the source. When this option is set, the target database's (or server's) collation should be used.

```cmd
/p: CompareUsingTargetCollation=True|False
```
Another alternative would be for you to open Visual Studio project and change collation in the database properties and re-generate DACPAC or deploy from VS as in https://sqlwatch.io/docs/installation/

Let me know if this works for you. I will keep this issue open as regardless the above, looks like I'm using the old SQL collation anyway. I will change it in the project.

Thanks for raising this!

**Comment by francescovista** [comment]
I created the DB but now it doesn't want to deploy SQLWATCH:

![now](https://user-images.githubusercontent.com/30395256/45126688-b69b3280-b1c8-11e8-9a18-3d33382048f8.PNG)


I don't have VS

**Comment by marcingminski** [comment]
Try Upgrade Data-Tier Application
![image](https://user-images.githubusercontent.com/8288333/45126897-9b4f0980-b16d-11e8-862c-8ae80b40a54c.png)

**Comment by francescovista** [comment]
...mmm...

I don't have it

![not](https://user-images.githubusercontent.com/30395256/45127043-8c4a7480-b1ca-11e8-9d00-dd77dcf48b38.png)

**Comment by leedsdata** [comment]
Hi,

Which version of SSMS?
Which version of SQL Server are you installing on?
What is the collation of your server?

Thanks,
Dan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by francescovista** [comment]
SSMS:

```
Microsoft SQL Server Management Studio						13.0.16106.4
Microsoft Analysis Services Client Tools						13.0.1700.441
Microsoft Data Access Components (MDAC)						10.0.15063.0
Microsoft MSXML						3.0 4.0 6.0 
Microsoft Internet Explorer						9.11.15063.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.15063
```

SQL Server: `2016`

Collation: `Latin1_General_CI_AS`

**Comment by francescovista** [comment]
This issue is fixed, I found Update Data-tier Application doing right click on the database itself
