### ISSUE TITLE
DACPAC 1.0.0.0 Server Collation SQL_Latin1_General_CP1_CI_AS conflict

### ISSUE THREAD

**Issue by larspl** [marcingminski/sqlwatch#32]
**Describe the bug**
Deployment Error DACPAC 1.0.0.0

Could not deploy package.
Error SQL72014: .Net SqlClient Data Provider: Msg 468, Level 16, State 9, Procedure sp_sql_perf_mon_logger, Line 130 Ein Sortierungskonflikt zwischen "SQL_Latin1_General_CP1_CI_AS" und "Latin1_General_CI_AS" im like-Vorgang kann nicht aufgelöst werden.
Error SQL72045: Script execution error.  The executed script:
CREATE PROCEDURE [dbo].[sp_sql_perf_mon_logger]
AS
...
**To Reproduce**
just use to deploy a DACPAC App to a new SQL Server

**Expected behavior**
deployment without error

**Screenshots**
![image](https://user-images.githubusercontent.com/8365382/45222472-fb9c9300-b2b4-11e8-8d92-7f773faf2a6e.png)

**Desktop (please complete the following information):**
 - OS: W2k12R2
 - SQL2k16Sp2 Remote

**Additional context**
Server Collation: SQL_Latin1_General_CP1_CI_AS
Server Lang: EN
SSMS 2017 17.7 EN

**Comment by marcingminski** [comment]
Hi, may I point you to this: https://sqlwatch.io/docs/installation/collation-conflict/
Please report back if you are still having issues.
thanks

**Comment by larspl** [comment]
Hi Marcin, yes. if i dot by hand, it works. 
I post it here while i have not found a how-to-fix that issue. 
So i see now that the DOCs have it.  

so is close this case.
