### ISSUE TITLE
Database exclusion does not work for snapshot 11

### ISSUE THREAD

**Issue by LionelFremondiere** [marcingminski/sqlwatch#320]
**Describe the bug**
The sqlwatch_logger_whoisactive table is full with too much activity on a database and the exclusion table [sqlwatch_config_exclude_database] is not being used.

**Expected behavior**
Add [sqlwatch_config_exclude_database] to the stored procedure [usp_sqlwatch_logger_whoisactive].

**SQL Server (please complete the following information):**
Microsoft SQL Server 2014 (SP3-CU1) (KB4470220) - 12.0.6205.1 (X64) Nov 30 2018 02:59:03 Copyright (c) Microsoft Corporation Enterprise Edition (64-bit) on Windows NT 6.3 (Build 9600: ) (Hypervisor)
Microsoft SQL Server 2016 (SP2-CU7) (KB4495256) - 13.0.5337.0 (X64) May 16 2019 02:24:21 Copyright (c) Microsoft Corporation Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 (Build 14393: ) (Hypervisor)
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) Sep 24 2019 13:48:23 Copyright (C) 2019 Microsoft Corporation Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 (Build 14393: ) (Hypervisor)
 
**SQLWATCH version (from DACPAC or from sysinstances)**
install_sequence	install_date	sqlwatch_version	major	minor	patch	build
- 1	2021-04-19 12:10:34.0209715 +02:00	3.0.9.18505	3	0	9	18505
- 1	2021-05-04 08:38:22.8478050 +02:00	4.0.0.28254	4	0	0	28254
 
**Proposed solution**
[usp_sqlwatch_logger_whoisactive.txt](https://github.com/marcingminski/sqlwatch/files/6421232/usp_sqlwatch_logger_whoisactive.txt)

**Comment by marcingminski** [comment]
I was planning to end support for whoisactive as there is no real benefit to have it in sqlwatch. How do you use it and why? what does it give you that sqlwatch does not?

**Comment by marcingminski** [comment]
As in, just to make it clear, whoisactive is fantastic but for different reasons and slightly different to what sqlwatch is doing

**Comment by LionelFremondiere** [comment]
Good question! :-)
As sqlwatch_logger_xes_long_queries exists we don't really need whoisactive but why keep whoisactive job ?
I have disabled the job SQLWATCH-LOGGER-WHOISACTIVE so you can close this ticket.
Thanks Marcin
