### ISSUE TITLE
usp_sqlwatch_logger_performance missing "collate database_default"

### ISSUE THREAD

**Issue by sozezzo** [marcingminski/sqlwatch#324]
**Describe the bug**

**To Reproduce**
When The SQLWatch database has a different collate than the other databases. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12115808/117254271-35334c80-ae16-11eb-9ac4-fecb092b4d7d.png)

**Windows Server (please complete the following information):**
 - OS Version:  Windows Server 2016 

**SQL Server (please complete the following information):**
 - SQL Version: [e.g. SQL Server 2016 SP1]
 - SQL Edition: [e.g. Enterprise]
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
SQL Server Management Studio						15.0.18369.0
SQL Server Management Objects (SMO)						16.100.46041.41
Microsoft Analysis Services Client Tools						15.0.19342.0
Microsoft Data Access Components (MDAC)						10.0.18362.1
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.18363

 
Solution:
![image](https://user-images.githubusercontent.com/12115808/117254572-8f341200-ae16-11eb-9108-3452b9ea2fca.png)

**Comment by marcingminski** [comment]
Thanks. Would you like to submit this as a PR so you will be accredited as a contributor?

**Comment by sozezzo** [comment]
next time, thanks.
