### ISSUE TITLE
Grafana Dashboard - Activity Panel - SQL Compilations/sec and SQL Re-Compilations/sec always the same number 

### ISSUE THREAD

**Issue by TArmstrong24** [marcingminski/sqlwatch#326]
**Did you check DOCS to make sure there is no workaround?**
Yes

**Describe the bug**
When viewing the activity panel, the SQL Compilations/sec and SQL Re-Compilations/sec display the same number. This also affects the Compilation Rate causing the Re-Compilation Rate to stay at 100%

**To Reproduce**
1. View the dashboard

**SQLWATCH version (from DACPAC or from sysinstances)**
 - Latest version installed from dbatools
 
Researching the problem, I found a typo in the query:

,'SQL Re-Compilations/sec' = AVG(case when counter_name = **'SQL Compilations/sec'** then [cntr_value_calculated] else null end)

This part of the query should be looking for the 'SQL Re-Compilations/sec' counter

**Comment by marcingminski** [comment]
Thank you. I did notice it too but did not have the time to investigate. You are welcome to submit a PR with this change so you can take credit for it.
