### ISSUE TITLE
MS SQL Express not populating metrics after enabling queues

### ISSUE THREAD

**Issue by TArmstrong24** [marcingminski/sqlwatch#335]
**Did you check DOCS to make sure there is no workaround?**
Yes

**Describe the bug**
Data not being populated when utilizing a fresh install on Sql Watch on MS SQL 2012 Express after running 'exec dbo.usp_sqlwatch_internal_migrate_jobs_to_queues' to enable queues as described in the release notes.

**To Reproduce**
1. Install SQL Watch to SQL Server 2012 utilizing dbatools
2. Execute dbo.usp_sqlwatch_internal_migrate_jobs_to_queues
3. View logger tables manually to see if data is being populated

**Comment by marcingminski** [comment]
Can you please show me the output from `exec [dbo].[usp_sqlwatch_internal_broker_diagnostics]`  and `SELECT is_broker_enabled FROM sys.databases WHERE name = 'SQLWATCH'` -- note you may have to change the database name if its not SQLWATCH

**Comment by TArmstrong24** [comment]
[results.txt](https://github.com/marcingminski/sqlwatch/files/6453054/results.txt)

Here are the results.. attached.

**Comment by marcingminski** [comment]
Nothing wrong with that. 
Could you look for errors in 
```
SELECT *
  FROM [dbo].[sqlwatch_app_log]
  where [process_message_type] = 'ERROR'
```
and see if there are any errors related to the broker activation in the SQL ERRORLOG?

**Comment by TArmstrong24** [comment]
Thank you for the help, it is resolved now! After seeing the results of the sqlwatch_app_log query, I saw that my database had a collation conflict. Once I uninstalled/removed the database, created it from scratch with the default server collation, reinstalled and re-ran the migration query, the tables are now being populated!

**Comment by marcingminski** [comment]
I suppose the collation conflict was in the performance logger? This has just recently been fixed: https://github.com/marcingminski/sqlwatch/pull/329. Should be available in the next release but you got it sorted anyway.

**Comment by TArmstrong24** [comment]
Yes, I believe so, the Error_Procedure is usp_sqlwatch_logger_performance and the error was 'Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_CI_AS" in the equal to operation.'
