### ISSUE TITLE
invalid column name 'database_name' - Grafana Wait Events dashboard

### ISSUE THREAD

**Issue by tune007** [marcingminski/sqlwatch#348]
Error: Grafana Dashboard - Wait Events -error updating options :mssql:invalid column name database_name
When opening the Grafana wait events dashboard with the latest SQLwatch dacpac installed the following error comes up and their is no data for Queries and SQL text.

**Comment by marcingminski** [comment]
Is this the same as: https://github.com/marcingminski/sqlwatch/issues/344 ?

**Comment by tune007** [comment]
Hi thank you for noticing , this is my first issue I submitted on github yes it is the same as #344 but I see that issue is closed. From reading the comments if I understand correctly it is not providing any data because their are no evidence for long running queries in the buffer cache so in essence it is not really an error. Please comment I will close.

**Comment by marcingminski** [comment]
Hi, 
Don't worry about it

As for the actual issue - it has been fixed couple of days ago but not yet released. you may have to wait for version 4.2
The idea is to get the query from the plan cache if available but if that fails, we are parsing the event xml so as long as there has been long query registered you will get all details.

**Comment by tune007** [comment]
Thanks for the quick reply Marcin and all the hard work. SQLwatch is fantastic !!! I will wait for the next release.
