### ISSUE TITLE
SQLWATCH-INTERNAL-RETENTION failing after v4.1 upgrade

### ISSUE THREAD

**Issue by mike-halford** [marcingminski/sqlwatch#350]
Since upgrading to SQLWATCH.4.1 **SQLWATCH-INTERNAL-RETENTION** is failing on several servers . Ran ok for first 24hours so assume its a date/time issue.

**Fails at Step 2.** 
EXEC dbo.usp_sqlwatch_internal_purge_deleted_items

**ERROR MESSAGE**
05/12/2021 13:00:22,SQLWATCH-INTERNAL-RETENTION,Error,2,???\???,SQLWATCH-INTERNAL-RETENTION,dbo.usp_sqlwatch_internal_purge_deleted_items,,Executed as user: ???\????. Unable to delete meta record as there are existing config records. Please delete config first [SQLSTATE 42000] (Error 50000)  Purged 0 rows from dbo.sqlwatch_meta_agent_job [SQLSTATE 01000] (Error 0)  Purged 0 rows from dbo.sqlwatch_meta_agent_job_step [SQLSTATE 01000] (Error 0)  The transaction ended in the trigger. The batch has been aborted. [SQLSTATE 42000] (Error 3609).  The step failed.,00:00:02,16,3609,,,,0

VERSIONS
SQL Version 2017 Standard
Windows 2016
SQLWATCH.4.1.0.28258.20210510154229

**Comment by marcingminski** [comment]
Are there any errors in:
```
SELECT *
  FROM [dbo].[sqlwatch_app_log]
  where process_message_type = 'ERROR'
  ```
  
  Could you run `EXEC dbo.usp_sqlwatch_internal_purge_deleted_items` in SSMS and paste the entire output please?

The message comes from a trigger in table `[dbo].[sqlwatch_meta_check]`. I think what happening is that I have changed the purge items retention to 2 days (from 7 in previous versions) but the last_seen only gets updated every 24 hours. There is another bug for that.

You could change `[dbo].[sqlwatch_config]`:
```
config_id	config_name
2	Last Seen Items (date_last_seen) retention days
```

i.e.:

```
update [dbo].[sqlwatch_config]
set [config_value] = 7
where [config_id] = 2
```

**Comment by mike-halford** [comment]
No errors in log table.

EXEC dbo.usp_sqlwatch_internal_purge_deleted_items

**Results**
Purged 0 rows from dbo.sqlwatch_meta_agent_job 
Purged 0 rows from dbo.sqlwatch_meta_agent_job_step 
Msg 50000, Level 16, State 1, Procedure trg_sqlwatch_meta_check_delete, Line 19 [Batch Start Line 0]
Unable to delete meta record as there are existing config records. Please delete config first
Msg 3609, Level 16, State 1, Line 16
The transaction ended in the trigger. The batch has been aborted.

Completion time: 2021-05-12T13:47:04.1394751+01:00

Even after changing the retention period (update [dbo].[sqlwatch_config] set [config_value] = 7 where [config_id] = 2) I'm getting the same error.

**Comment by marcingminski** [comment]
Any chance you could dump `[dbo].[sqlwatch_meta_check]` and `[dbo].[sqlwatch_config_check]`into csv and let me see it? You can obfuscate or remove `check_name` I am only interested in Ids and date columns. Thanks

**Comment by mike-halford** [comment]
Here are the two table dumps. 

** Server/Instance has been obfuscated.
[TableDumps.zip](https://github.com/marcingminski/sqlwatch/files/6466329/TableDumps.zip)

**Comment by marcingminski** [comment]
Thanks.

I believe it is trying to delete records with date `05/05/2021 08:58` in `base_object_date_last_seen` column in the meta table. This change was part of the semi-automated check management, but I am not sure whether it should be doing that. It's more likely that the automated check management should be removing checks if base obejcts have been deleted, rather than retention job doing that. I need to review this piece of code.

As a temporary fix, If you modify `[dbo].[usp_sqlwatch_internal_purge_deleted_items]` and remove `base_object_date_last_seen` from the IN clause in line 22 it should fix it.

Thanks for this!

**Comment by mike-halford** [comment]
I can confirm that applying suggested fix has resolved the issue.

Many Thanks

**Comment by marcingminski** [comment]
Great. I am going to keep this open until a permanent fix is in place.
