### ISSUE TITLE
"Expand by checks" doesnt works for remote instances on central repository

### ISSUE THREAD

**Issue by KONEL-68** [marcingminski/sqlwatch#354]
_I'm learning English. Sorry for mistakes._

**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/ - Yes.

**To Reproduce**
1. Go to [dbo].[sqlwatch_config] and turn on config_id = 19 ('Expand Checks by SQL Instance')
2. Execute [dbo].[usp_sqlwatch_internal_expand_checks]
3. Check [dbo].[sqlwatch_config_check] with target_sql_instance <> @@SERVERNAME

**Expected behavior**
I want get checks on central repository for Database on remote instance.

**Screenshots**
(Second query is empty)
![image](https://user-images.githubusercontent.com/47787046/118182814-16e6d580-b442-11eb-8980-78d2b5bb29e1.png)

**Windows Server (please complete the following information):**
 - OS Version: Windows Server 2019 Standard 10.0 <X64>

**SQL Server (please complete the following information):**
 - SQL Version: Microsoft SQL Server 2019 (RTM-CU9) (KB5000642) - 15.0.4102.2 (X64)
 - SQL Edition: Developer Edition (64-bit)
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
SQL Server Management Studio						15.0.18369.0
SQL Server Management Objects (SMO)						16.100.46041.41
Microsoft Analysis Services Client Tools						15.0.19342.0
Microsoft Data Access Components (MDAC)						10.0.17763.1
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.17763
 
**SQLWATCH version (from DACPAC or from sysinstances)**
- 4.1.0.24109
 
# My Fix:
In procedure [dbo].[usp_sqlwatch_internal_expand_checks] fix "if @expand_by = 'Database'"
![image](https://user-images.githubusercontent.com/47787046/118184309-db4d0b00-b443-11eb-8bdc-9aa19bef94e9.png)

**Comment by KONEL-68** [comment]
I just discovered that there is such a bug with disks too
![image](https://user-images.githubusercontent.com/47787046/118184472-12bbb780-b444-11eb-8947-6bf65fdf5b77.png)

**Comment by KONEL-68** [comment]
Corrected in the same way as with the database.

**Comment by marcingminski** [comment]
I see what you mean. I will test this although I am sure this has worked but probably not quite. Thanks

**Comment by marcingminski** [comment]
Have you checked you have this enabled in the config?
```
select dbo.ufn_sqlwatch_get_config_value (19, null)
```
should return 1 for expanding to work on the central repository.

however, I think there was still a bug in line 196 where it was referencing local instance

**Comment by KONEL-68** [comment]
> however, I think there was still a bug in line 196 where it was referencing local instance

Yes. Its enabled.
![image](https://user-images.githubusercontent.com/47787046/118708748-c8ac4a80-b824-11eb-923b-8c6be99dc37c.png)

Look at line 117. Checks expand by disk will not work for a remote repository, because it is referencing to local instance too.
https://github.com/marcingminski/sqlwatch/blob/5b3cb9325b6f95f933f7bed8a3ccae076ed7b4d4/SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_internal_expand_checks.sql#L117

**Comment by marcingminski** [comment]
yes. good catch!
