### ISSUE TITLE
[New Feature] Capturing Drive Space

### ISSUE THREAD

**Issue by ColinDouglas92** [marcingminski/sqlwatch#37]
**Is your feature request related to a problem? Please describe.**
Capturing drive space usage (drive name, total drive space, free space, etc.). This will allow the user to track how drive space usage changes. This collection could be beneficial if there is an appetite to add a reporting mechanism in the future, as low drive space can be a "show stopper" in some cases. It could also be used to forecast future drive growth. 

**Describe the solution you'd like**
A number of ways this could be collected, with pro's and con's for all. SQL Server does not provide a DMV that includes information for all drives and omits important values like total drive size for all drives that may reside on a server.

The best solution would be to use command line/powershell to pull the information for all drives, but this would be assuming that the user had xp_cmdshell enabled which wouldn't be ideal.

The second best solution would be to use the sys.dm_os_volume_stats system function. This would return all of the necessary information **only** for drives that contain SQL Server data + log files. This gets us closer to the requested feature but still has its pitfalls, such as a drive that contains the OS but does not contain any SQL Server data/log files would not be included in the collection. 

**Describe alternatives you've considered**
Options above. - The PhysicalDisk PerfMon counters do not include total drive space.  

**Additional context**
Let me know if there is a better solution than the ones described above. If the xp_cmdshell requirement is not an issue, then I would say that's the route to go. There could always be a check of if xp_cmdshell is enabled, then collect, if not, skip. Thanks!

**Comment by marcingminski** [comment]
Hi, thank you for your sugestion. Yes, it is something I am working on, currently there’s database utilisation in testing (available in data-size-logging branch if you wan to give it a go), individual table utilisation and storage stats to come soon. I will probably use PS or xp_fixeddrives to grab available disk space as I don’t like to rely on cmdshell. Watch this space :)

**Comment by ColinDouglas92** [comment]
Perfect! That will definitely come in handy! Out of curiosity, have you had a chance to look at the following comments: #31 , #12 ? I'd love to help you out on developing a feature you have backlogged right now!

**Comment by marcingminski** [comment]
Yes I did but didn’t have any valuable answer :) let me comment now with my thoughts.

**Comment by marcingminski** [comment]
Completed in 798dc522f0239f0dccf2412729cf0e83e2aa6536
