### ISSUE TITLE
spelling mistake - function name : GetPerformnaceCounterData

### ISSUE THREAD

**Issue by sozezzo** [marcingminski/sqlwatch#373]
It is not a bug, it is just a mistake.

GetPerfor**mna**ceCounterData

**Screenshots**
![image](https://user-images.githubusercontent.com/12115808/118758165-7aa34100-b83c-11eb-982b-1fb19f364249.png)

nice job, tkx

**Comment by marcingminski** [comment]
Thanks. CLR is going away so I may just not bother fixing that.

**Comment by marcingminski** [comment]
CLR to be removed in 5.0
