### ISSUE TITLE
Replace localhost with Instance in sqlwatch_config_action

### ISSUE THREAD

**Issue by steffenengelhamburg** [marcingminski/sqlwatch#378]
**Describe the bug**

Try to change Action -16 in dbo.sqlwatch_config_action:
Replace localhost with $(ESCAPE_DQUOTE(SRVR))

$(ESCAPE_DQUOTE(SRVR))
is prefered way to pipe Servername\Instance to Powershell Agent Job

[SQLWATCH].[dbo].[sqlwatch_meta_action_queue]
exec Status is 'retrying'

**To Reproduce**
Change your Action -16 replace localhost with $(ESCAPE_DQUOTE(SRVR))
Wait until action is in queue and 'retrying'

Create new Agent Job Test with action_exec Statement from sqlwatch_meta_action_queue
....
Invoke-Sqlcmd -ServerInstance $(ESCAPE_DQUOTE(SRVR)) -Database SQLWATCH -Query "select mpc.sql_instance, mpc.[object_name]....

Run Job:
![image](https://user-images.githubusercontent.com/43856217/119483836-aef39180-bd55-11eb-8227-7f9f89d89f0f.png)
Job is successfull $(ESCAPE_DQUOTE(SRVR)) was used as expected

**Windows Server (please complete the following information):**
 - OS Version: [e.g. Windows 2019]

**SQL Server (please complete the following information):**
 - SQL Version: SQL Server 2017 14.0.3381.3
 - SQL Edition: Enterprise
  
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 4.2.0.37410

**Comment by steffenengelhamburg** [comment]
It would great if it's possible to use $(ESCAPE_DQUOTE(SRVR)) in SQLwatch Powershell Actions (not only in '-16') because i need to deploy the same Action Statement on several named instances.

Workaround is to manual update the Action on each instance with:
update [dbo].[sqlwatch_config_action]
set [action_exec] = 'Invoke-Sqlcmd -ServerInstance ''' + @@servername + ''' -Database  .........
where [action_id] = -16

**Comment by marcingminski** [comment]
Would it not be a better approach to update deployment script to substitute `localhost`with  the actual `@@SERVERNAME`

**Comment by steffenengelhamburg** [comment]
solved with Commit #378 Replace localhost with @@ServerName (#380)
