### ISSUE TITLE
Some Links within Grafana Dashboards produce Dashboard not found

### ISSUE THREAD

**Issue by steffenengelhamburg** [marcingminski/sqlwatch#382]
**Describe the bug**
Some Links within Repository Dashboard and SQL Instance Overview point to non existing Dashboard.

**To Reproduce**
open Repository Dashboard Click on Check Details, new Site opened with Dashboard not found.

In JSON Model Link Points to 
"title": "Check Details",
"url": "/d/sqlwatch-checks/checks?${__url_time_range}&var-DataSource=${DataSource}&var-sql_instance=${sql_instance}"

sqlwatch-checks moved to:
Sqlwatch Instance Overview

**Expected behavior**
Link in Json Point to
"url": "/d/sqlwatch-instance-overview/sql-instance-details?${__all_variables}"

Or better right into Checks Panel
"title": "$sql_instance Check Details",
"url": "/d/sqlwatch-instance-overview/sql-instance-overview?${__url_time_range}&viewPanel=252&orgId=1&var-DataSource=${DataSource}&var-sql_instance=${sql_instance}"

**SQLWATCH version (from DACPAC or from sysinstances)**
 - 4.2.0.37410 Grafana Dashboards
 
**Additional context**
Changes in Progress, Pull Request already in Work

**Comment by marcingminski** [comment]
That’s because I haven’t released all the dashboards yet as I’m not fully happy with them. Doing links in Grafana is painful so I decided to leave them rather than remove for each release and recreate later.
