### ISSUE TITLE
[dbo].[usp_sqlwatch_internal_expand_checks] ERROR PRIMARY KEY

### ISSUE THREAD

**Issue by KONEL-68** [marcingminski/sqlwatch#385]
**Did you check DOCS to make sure there is no workaround?**
Yes

**Describe the bug**
I added record to [SQLWATCH].[dbo].[sqlwatch_config_check_template_action] for CPU Utilistaion and get error from [dbo].[usp_sqlwatch_internal_expand_checks].
```
Violation of PRIMARY KEY constraint 'pk_sqlwatch_config_check_action'. Cannot insert duplicate key in object 'dbo.sqlwatch_config_check_action'. The duplicate key value is (7, 1).
```

**To Reproduce**
1. Install SQLWATCH on two instances and configure central repository (CR).
2. [dbo].[sqlwatch_config]: enable **Expand Checks by SQL Instance** on CR.
```
UPDATE [SQLWATCH].[dbo].[sqlwatch_config]
SET config_value = 1
WHERE config_id = 19 AND config_name = 'Expand Checks by SQL Instance'
```
3. Add to [dbo].[sqlwatch_config_check_template_action]
```
USE [SQLWATCH]
GO

INSERT INTO [dbo].[sqlwatch_config_check_template_action]
           ([check_name]
           ,[action_id]
           ,[action_every_failure]
           ,[action_recovery]
           ,[action_repeat_period_minutes]
           ,[action_hourly_limit]
           ,[action_template_id])
     VALUES
           ('CPU Utilistaion'
           ,1 -- It doesnt matter. I have action for Telegram notifications.
           ,0
           ,1
           ,5
           ,2
           ,1) -- It doesnt matter.
GO
```
4. And execute procedure [dbo].[usp_sqlwatch_internal_expand_checks]
```
EXEC [dbo].[usp_sqlwatch_internal_expand_checks]
```

**Expected behavior**
I want to get automatic generation of alerts for general expanding checks.

**Screenshots**
![image](https://user-images.githubusercontent.com/47787046/120198555-e61ce380-c22a-11eb-9217-ef0772bbfbcc.png)

**Windows Server (please complete the following information):**
 - OS Version: Windows Server 2019

**SQL Server (please complete the following information):**
 - SQL Version: Microsoft SQL Server 2019 (RTM-CU9) (KB5000642) - 15.0.4102.2
 - SQL Edition: Developer Edition 
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
SQL Server Management Studio						15.0.18369.0
SQL Server Management Objects (SMO)						16.100.46041.41
Microsoft Analysis Services Client Tools						15.0.19342.0
Microsoft Data Access Components (MDAC)						10.0.17763.1
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.17763
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 4.2.0.28234
 
**Additional context**
I add some code to [dbo].[usp_sqlwatch_internal_expand_checks] in 284 line
```
select 
	cc.[check_id]
	,a.[action_id]
	,a.[action_every_failure]
	,a.[action_recovery]
	,a.[action_repeat_period_minutes]
	,a.[action_hourly_limit]
	,a.[action_template_id]
	,[date_created]=GETUTCDATE()
	,[date_updated]=GETUTCDATE()
		
from @checks c
inner join [dbo].[sqlwatch_config_check_template]  ct
	on ct.check_template_id = c.check_template_id
inner join [dbo].[sqlwatch_config_check_template_action] a
	on a.check_name = ct.check_name
inner join [dbo].[sqlwatch_config_check] cc
	on cc.check_name = ct.check_name
```
And get this:
![image](https://user-images.githubusercontent.com/47787046/120198999-6ba09380-c22b-11eb-81a3-42822c142030.png)

# In my case, I have following solution (section "load action templates" - line ~285):
```
select 
	cc.[check_id]
	,a.[action_id]
	,a.[action_every_failure]
	,a.[action_recovery]
	,a.[action_repeat_period_minutes]
	,a.[action_hourly_limit]
	,a.[action_template_id]
	,[date_created]=GETUTCDATE()
	,[date_updated]=GETUTCDATE()
		
from @checks c
inner join [dbo].[sqlwatch_config_check_template]  ct
	on ct.check_template_id = c.check_template_id
inner join [dbo].[sqlwatch_config_check_template_action] a
	on a.check_name = ct.check_name
inner join [dbo].[sqlwatch_config_check] cc
	--on cc.check_name = ct.check_name
	on cc.check_name = c.check_name -- ct ([dbo].[sqlwatch_config_check_template]) have expanding checks with {} words and this can lead to errors
	-- Example: "Database {DATABASE} AUTO_CLOSE" <> "Database master AUTO_CLOSE"
	AND cc.target_sql_instance = c.target_sql_instance -- add target_sql_instance for correct INSERT.
```
After that fix I get next:
![image](https://user-images.githubusercontent.com/47787046/120199969-79a2e400-c22c-11eb-84cd-7a2555524d62.png)

**Comment by KONEL-68** [comment]
@marcingminski 
Can I create a request or not? I do not insist.

**Comment by marcingminski** [comment]
Of course, you can, no need to ask. Submit PR and if everything is good, I will have no reason to reject it.
I have not had a chance to look at this issue hence no response yet.

**Comment by KONEL-68** [comment]
> Of course, you can, no need to ask. Submit PR and if everything is good, I will have no reason to reject it.
> I have not had a chance to look at this issue hence no response yet.

Thank you. I did it. 👍

**Comment by KONEL-68** [comment]
It can be closed. We fixed that.
@marcingminski
