### ISSUE TITLE
On version SQWATCH 4.X, the PowerBi Blocking tab report does not work

### ISSUE THREAD

**Issue by jormcand** [marcingminski/sqlwatch#401]
On version SQWATCH 4.X, the PowerBi Blocking tab report (SQLWATCH Dashboard 20210430.pbix) does not work. The table fields were changed from version 3.0 to 4.x , but this tab report is still the same.

To reproduce, open the PowerBi report in tab Blocking:

![image](https://user-images.githubusercontent.com/87420900/125605491-e7f51597-8476-4b0d-a58a-d2630523372d.png)

**Comment by marcingminski** [comment]
Hi, I believe this is the same as https://github.com/marcingminski/sqlwatch/issues/349 ?

**Comment by jormcand** [comment]
I don't think so. This problem is related to the fact that this report uses fields that come directely from database view  vw_sqlwatch_report_fact_xes_blockers and this view has chamged from the version3.0 to 4.x. The fields of this view, that are used by this report tab, have changed names or are not available anymore.

**Comment by Ant-Green** [comment]
All the visualisations are broken due to the column name changes between v3 and v4, as you can see on the screenshot everything is a yellow warning diamond as it cannot resolve "blocking_start_time", "blocking_end_time" etc any more and doesn't seem to be a  clear mapping as to the old field name to the new one to switch them around.

**Comment by marcingminski** [comment]
there must have been some mixup. It all works on mine so wonder if I have gotten the PBI file names and versions mixed up.

**Comment by Ant-Green** [comment]
The one in the main branch is back from April time so looks a bit old.

You got a working branch at all Marcin and I'll pull it and test?

**Comment by marcingminski** [comment]
I’ll have look tonight what’s gone wrong. I’m sure I have a working
version.

**Comment by Ant-Green** [comment]
Did you manage to take a look at this Marcin at all?

**Comment by marcingminski** [comment]
I did. I have a file modified on 21/05 - which is when the 4.2 release was made. The file however has Aprils date in the file name so looked like a mix up in naming. However, that file is exactly the same as in the repo so it may be that I have lost the working version. I am fixing the broken dashboard and should be releasing it soon.

**Comment by marcingminski** [comment]
Can you give this one a go and repot back please? If all good, I will make this into a 4.3 release soon.
It was a bit tricky because the table has changed completely, some fields had to be re-calculated in DAX, which could introduce new problems:

[SQLWATCH Dashboard 20210720.zip](https://github.com/marcingminski/sqlwatch/files/6851513/SQLWATCH.Dashboard.20210720.zip)

**Comment by Ant-Green** [comment]
That looks good Marcin, visuals all working as expected.

Have noticed an issue with the index stats & histogram collection, it just seems to be skipping any collection, the procs executes in subsecond.

Going to try and see where its failing, if you already didn't know of that.

Other than that looks like all visuals are working, just no data populated for the "Index Statistics" page

**Comment by marcingminski** [comment]
I have tried to make index stats collector more intelligent, to collect in batches based on last collection age rather than all at once. I can guess it will be to do with that. I will have a look.

**Comment by Ant-Green** [comment]
Thanks, I'll message you on Slack as may need a bit of a discussion on it, think I found the issue with the >=0 on the config check as it wasn't populating the temp table to then use in the inner join further down.
