### ISSUE TITLE
Dashboards are not functional in Grafana v10.4.2

### ISSUE THREAD

**Issue by SergeiTsernitski** [marcingminski/sqlwatch#490]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**

**To Reproduce**
Just open a dashboard in Grafana v10.4.2 and you will see a warning:
This panel requires Angular (deprecated). No information displayed

**Expected behavior**
See the panels/charts with content
**Screenshots**
![image](https://github.com/marcingminski/sqlwatch/assets/89131430/b9b309ec-5d95-447d-b46c-a9d4f1e5dfad)

**Comment by marcingminski** [comment]
I understand this is just a warning. The panel is working as expected. You can control this behaviour with 

angularDeprecationUI in featuretoggles 
https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/

**Comment by SergeiTsernitski** [comment]
My problem was actually related to sqlwatch import that failed that's why panels were without content. Thank you!
