### ISSUE TITLE
deploying the DACPAC in sql s2016 sp2 windows 2012r2 

### ISSUE THREAD

**Issue by djadcareer** [marcingminski/sqlwatch#63]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**
when i try to deploy a dacpac for the first time i'm getting these errors on the  image please let me know if i need to get you something else.
**To Reproduce**
1. Go to..
2. Click this..

**Expected behavior**
A clear and concise desc
![sqlwatchioinstalation](https://user-images.githubusercontent.com/27824140/46675320-27f54900-cbac-11e8-85ca-d58cc23ba838.PNG)
ription of what you expected to happen.

**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: [e.g. Windows 2012 R2]

**SQL Server (please complete the following information):**
 - SQL Version: [SQL Server 2016 SP3 cu 3]
 - SQL Edition: [Enterprise]
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 Microsoft SQL Server Management Studio						14.0.17028.0
Microsoft Analysis Services Client Tools						14.0.338.80
Microsoft Data Access Components (MDAC)						6.3.9600.16384
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.9600.18817
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.9600
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 1.3.2.0
 
**Additional context**
Add any other context about the problem here. here is the error message 
Could not deploy package.
Error SQL72014: .Net SqlClient Data Provider: Msg 14607, Level 16, State 1, Procedure sysmail_verify_profile_sp, Line 42 profile name is not valid
Error SQL72045: Script execution error.  The executed script:
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS;

 (Microsoft.SqlServer.Dac)

**Comment by marcingminski** [comment]
Hi, interesting, I don’t use sysmail_verify_profile_sp at all, it’s  not even in the code. I suspect you may have some server triggers on create database?

This error suggests you are using the SQL built in email function for something ie you could have a trigger that sends email when new database is created perhaps? SQLWATCH doesn’t send emails and doesn’t use the db mail function. 

Can you try creating empty SQLWATCH database manually and then deploy DACPAC?

**Comment by djadcareer** [comment]
sever trigger you mean ?

**Comment by marcingminski** [comment]
Yes, or something that’s trying to send an email from SQL when database is created.

**Comment by larspl** [comment]
Hi @djadcareer , i have re-try your setup and found out that a non configuration of sysmail are not an issue in case of the dacpac deployment is. my guess, there must be some server trigger for db creation or updated dacpac apps.   if you fix the issue , please close the case or give us a hint. thx lars

**Comment by marcingminski** [comment]
Closing as we cannot add anything. This is a server issue however if you are having problems other than the above I am more than happy to help.
