### ISSUE TITLE
Collation issue in LIKE operator

### ISSUE THREAD

**Issue by olegstrutinskii** [marcingminski/sqlwatch#64]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**

`
(212,1): SQL72014: .Net SqlClient Data Provider: Msg 468, Level 16, State 9, Procedure sp_sql_perf_mon_logger, Line 130 Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Cyrillic_General_CI_AS" in the like operation.
`

**To Reproduce**
1. Install `sqlwatch` in SQL Server with `Cyrillic_General_CI_AS`

**Expected behavior**
Being installed

**Windows Server (please complete the following information):**
 - Windows Server 2016 Standard 10.0 <X64> (Build 14393: )

**SQL Server (please complete the following information):**
- Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64) Developer Edition (64-bit) 
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 1.3.0.0
 - files date at 2018-10-07
 
**Additional context**
Published from VS Community 15.8.7

**Comment by olegstrutinskii** [comment]
This error for all comparisons or inserts where `*char` type used.

**Comment by marcingminski** [comment]
Hi Oleg, are you getting this during installation or were you able to install but getting errors during execution?

**Comment by olegstrutinskii** [comment]
I'm getting a lot of errors during installation, installed from Visual Studio, now running w/o any errors.

I have changed there files in solution:
- sp_sql_perf_mon_logger.sql
- usp_logger_disk_utilisation.sql
- Script.PostDeployment1.sql

**Comment by marcingminski** [comment]
Did you try this: https://sqlwatch.io/docs/known-issues-and-limitations/collation-conflict/ and did it not solve your problem?

**Comment by olegstrutinskii** [comment]
Thank you for pointing into `docs`, was looking there, didn't see that article. Thank you!
