### ISSUE TITLE
Load was cancelled by an error in loading a previous table.

### ISSUE THREAD

**Issue by francescovista** [marcingminski/sqlwatch#65]
**Did you check DOCS to make sure there is no workaround?**
Yes, the closest thing I found was "Login failed error when running disk logger" but is not my case

**Describe the bug**
I installed SQLWATCH-v1.3.20 and I run SQLWATCH Disk Utilisation Dashboard.pbit and I received an error

**To Reproduce**
1. Install latest SQLWATCH
2. Open SQLWATCH Disk Utilisation Dashboard.pbit

```
Server
Microsoft SQL: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)

Database
Load was cancelled by an error in loading a previous table.

DiskUtilisation-Database
Load was cancelled by an error in loading a previous table.

DiskUtilisation-Volume
Load was cancelled by an error in loading a previous table.

DiskUtilisation-Volume-FirstDate
Load was cancelled by an error in loading a previous table.

DiskUtilisation-Database-FirstDate
Load was cancelled by an error in loading a previous table.
```

**Expected behavior**
Well, it should work

**Screenshots**

This is my setup, maybe there was something wrong around the date format?

![setup](https://user-images.githubusercontent.com/30395256/47815582-9c8b6400-ddb5-11e8-97d6-4a23508d3d20.PNG)

This is the error:

![1](https://user-images.githubusercontent.com/30395256/47815618-b462e800-ddb5-11e8-80ef-23c0ba293f38.PNG)

**Windows Server (please complete the following information):**
 - Windows 10 Enterprise

**SQL Server (please complete the following information):**
Microsoft SQL Server Management Studio						13.0.16106.4
Microsoft Analysis Services Client Tools						13.0.1700.441
Microsoft Data Access Components (MDAC)						10.0.17134.1
Microsoft MSXML						3.0 4.0 6.0 
Microsoft Internet Explorer						9.11.17134.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.17134
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
Microsoft SQL Server Management Studio						13.0.16106.4
Microsoft Analysis Services Client Tools						13.0.1700.441
Microsoft Data Access Components (MDAC)						10.0.17134.1
Microsoft MSXML						3.0 4.0 6.0 
Microsoft Internet Explorer						9.11.17134.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.17134
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - SQLWATCH-v1.3.20
 
**Additional context**
None

**Comment by marcingminski** [comment]
Hi, this is PowerBI to SQL connection or authentication problem. Looks like your machine does not trust the SQL ceritificate. Can you connect from PowerBi to this SQL server at all? Forget SQLWATCH, open new PowerBi report and create SQL connection to master DB and see what happens. Do you use certificate based auth? Can you connect to it from SSMS?

**Comment by larspl** [comment]
this error only occurs if a secure/encrypted connection is enabled and not possible in PBI. Just go Edit Query, Data Source Settings 

![image](https://user-images.githubusercontent.com/8365382/48145216-a8de5800-e2b2-11e8-8e21-dcc816372fab.png)

and disable encryption. save and enjoy! :-) 

if the issue is solved, pls close it. thx Lars

**Comment by sev17** [comment]
I'm same error message, although nothing related to encryption. The issue seems to be the amount of data sp_whoisactive captures and the Power BI report associated with sp_whoisactive. To temporarily resolve I modified the report to not load sp_whoisactive data. When I extract the query from Power BI and attempt to run in SSMS, it too runs for 10 minutes before I cancel. The query is listed below. My whoisactive table has 80K rows and is around 144 MB.

`SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT report_time = s.[snapshot_interval_end],
       session = CONVERT(VARCHAR(MAX), st.session_id) + ': ' + st.program_name,
       st.program_name,
       session_start_time = MIN(st.start_time),
       session_duration_s = DATEDIFF(SECOND, MIN(st.start_time), MAX(f.snapshot_time)),
       session_end_time = MAX(f.snapshot_time),
       [sql_command] = REPLACE(
                                  REPLACE(
                                             CONVERT(VARCHAR(MAX), st.[sql_command]),
                                             '<?query --' + CHAR(13) + CHAR(10),
                                             ''
                                         ),
                                  CHAR(13) + CHAR(10) + '--?>',
                                  ''
                              ),
       [sql_text] = REPLACE(
                               REPLACE(CONVERT(VARCHAR(MAX), st.[sql_text]), '<?query --' + CHAR(13) + CHAR(10), ''),
                               CHAR(13) + CHAR(10) + '--?>',
                               ''
                           ),
       st.database_name,
       st.login_name,
       st.host_name
FROM [dbo].[sql_perf_mon_who_is_active] st
    INNER JOIN [dbo].[sql_perf_mon_who_is_active] f
        ON st.session_id = f.session_id
           AND st.start_time = f.start_time
    INNER JOIN [dbo].[ufn_time_intervals](1, 5, 4, GETDATE()) s
        ON st.snapshot_time >= s.[first_snapshot_time]
           AND f.snapshot_time <= s.[last_snapshot_time]
           AND f.snapshot_type_id = s.snapshot_type_id
GROUP BY st.session_id,
         st.program_name,
         s.[snapshot_interval_end],
         REPLACE(
                    REPLACE(CONVERT(VARCHAR(MAX), st.[sql_command]), '<?query --' + CHAR(13) + CHAR(10), ''),
                    CHAR(13) + CHAR(10) + '--?>',
                    ''
                ),
         REPLACE(
                    REPLACE(CONVERT(VARCHAR(MAX), st.[sql_text]), '<?query --' + CHAR(13) + CHAR(10), ''),
                    CHAR(13) + CHAR(10) + '--?>',
                    ''
                ),
         st.database_name,
         st.login_name,
         st.host_name;
`

**Comment by rafaelolsr** [comment]
@sev is right. When the query WhoIsActive takes too long, this error happens causing all the queries to abort. Try using the tweaked query below, it is working here so far.

**let
    Source = Sql.Database(ServerName, DatabaseName, [Query="SELECT report_time = s.[snapshot_interval_end]
          , SESSION = CONVERT( varchar(MAX), st.session_id ) + ': ' + st.program_name
          , st.program_name
          , session_start_time = MIN( st.start_time )
          , session_duration_s = DATEDIFF( SECOND, MIN( st.start_time ), MAX( f.snapshot_time ))
          , session_end_time = MAX( f.snapshot_time )
          , [sql_command] = REPLACE( REPLACE( CONVERT( varchar(MAX), st.[sql_command] ), '<?query --' + CHAR( 13 ) + CHAR( 10 ), '' ), CHAR( 13 ) + CHAR( 10 ) + '--?>', '' )
          , [sql_text] = REPLACE( REPLACE( CONVERT( varchar(MAX), st.[sql_text] ), '<?query --' + CHAR( 13 ) + CHAR( 10 ), '' ), CHAR( 13 ) + CHAR( 10 ) + '--?>', '' )
          , st.database_name
          , st.login_name
          , st.HOST_NAME
     FROM [dbo].[sql_perf_mon_who_is_active] st
          CROSS APPLY
               (
               SELECT session_id
                    , start_time
                    , snapshot_type_id
                    , snapshot_time
               FROM (
                    SELECT session_id
                         , start_time
                         , snapshot_type_id
                         , MAX(snapshot_time) snapshot_time
                    FROM [dbo].[sql_perf_mon_who_is_active]
                    GROUP BY session_id, start_time, snapshot_type_id
                    ) et
               WHERE et.session_id = st.session_id
               AND   et.start_time = st.start_time
               ) f
          INNER JOIN
          [dbo].[ufn_time_intervals]( 1, "&ReportIntervalMinutes&", "&ReportAgeHours&", "&EndTime&" ) s
               ON st.snapshot_time >= s.[first_snapshot_time]
                  AND f.snapshot_time <= s.[last_snapshot_time]
                  AND f.snapshot_type_id = s.snapshot_type_id
     GROUP BY st.session_id
            , st.program_name
            , s.[snapshot_interval_end]
            , REPLACE( REPLACE( CONVERT( varchar(MAX), st.[sql_command] ), '<?query --' + CHAR( 13 ) + CHAR( 10 ), '' ), CHAR( 13 ) + CHAR( 10 ) + '--?>', '' )
            , REPLACE( REPLACE( CONVERT( varchar(MAX), st.[sql_text] ), '<?query --' + CHAR( 13 ) + CHAR( 10 ), '' ), CHAR( 13 ) + CHAR( 10 ) + '--?>', '' )
            , st.database_name
            , st.login_name
            , st.HOST_NAME"])
in
    Source**

If you find any problems, please let me know.

**Comment by sev17** [comment]
Having trouble getting revised query to run in SSMS, syntax errors.
`SELECT
     report_time = s.[snapshot_interval_end]
        , SESSION = CONVERT( VARCHAR(MAX), st.session_id ) + ': ' + st.program_name
        , st.program_name
        , session_start_time = MIN( st.start_time )
        , session_duration_s = DATEDIFF( SECOND, MIN( st.start_time ), MAX( f.snapshot_time ))
        , session_end_time = MAX( f.snapshot_time )
        , [sql_command] = REPLACE( REPLACE( CONVERT( VARCHAR(MAX), st.[sql_command] ), '', '' )
        , [sql_text] = REPLACE( REPLACE( CONVERT( VARCHAR(MAX), st.[sql_text] ), '', '' )
        , st.database_name
        , st.login_name
        , st.host_name
    FROM [dbo].[sql_perf_mon_who_is_active] st
    CROSS APPLY
    (
        SELECT session_id
        , start_time
        , snapshot_type_id
        , snapshot_time
        FROM (
        SELECT session_id
        , start_time
        , snapshot_type_id
        , MAX(snapshot_time) snapshot_time
        FROM [dbo].[sql_perf_mon_who_is_active]
        GROUP BY session_id, start_time, snapshot_type_id
        ) et
        WHERE et.session_id = st.session_id
        AND et.start_time = st.start_time
    ) f
    INNER JOIN
    [dbo].[ufn_time_intervals]( 1, 5, 4, GETDATE() ) s
    ON st.snapshot_time >= s.[first_snapshot_time]
    AND f.snapshot_time <= s.[last_snapshot_time]
    AND f.snapshot_type_id = s.snapshot_type_id
    GROUP BY st.session_id
    , st.program_name
    , s.[snapshot_interval_end]
    , REPLACE( REPLACE( CONVERT( VARCHAR(MAX), st.[sql_command] ), '', '' )
    , REPLACE( REPLACE( CONVERT( VARCHAR(MAX), st.[sql_text] ), '', '' )
    , st.database_name
    , st.login_name
    , st.host_name`

**Comment by marcingminski** [comment]
Hi, what's everyones view on the WhoIsActive report? I am replacing it with extended events which will provide more insight into the workload than WhoIsActive and I will eventually look at deprecating the use of WhoIsActive. To be clear, WhoIsActive is fantastic but SQLWATCH runs it every 1 minute and can be missing a lot of stuff that happens between runs that never gets captured by WhoIsActive.

**Comment by sev17** [comment]
Drawing comparison between commercial products for wait stats analysis, they do variation of whoisactive. One popular one basically runs a similar query 3 times a minute. Yes, you miss some things, but it's lower overhead and it's not meant to capture everything like a extended event or trace.

**Comment by marcingminski** [comment]
I will do some testing but I am pretty confident an XE session to capture let's say queries that run over 20 seconds will have less overhead than firing up agent job and query dmv every 20 seconds?

**Comment by marcingminski** [comment]
Looks like untangling the xe xml is the most resource consuming task, even if there are 50 events in the ring_buffer or target file it still takes 1-3 seconds. I will see what I can do but with this in mind you may be right that it will more efficient to fire up a job ever 15 seconds and either run sp_whoisactive or a custom script.
