### ISSUE TITLE
Alerting in case of Value: Days Until Full is between 0 and 2 ( configurable )  

### ISSUE THREAD

**Issue by larspl** [marcingminski/sqlwatch#66]
**Is your feature request related to a problem? Please describe.**
DiskUtilisation-Volume Data shows Growth,Disk Free and Days until Full.
![image](https://user-images.githubusercontent.com/8365382/48147553-de397480-e2b7-11e8-93c6-885283708b36.png)

**Describe the solution you'd like**
It's a perfect Alert for each SQL Admin to get a Alert if this value is between 0 and 2 or some days.
If the Value is smaller there are some LogShipping or CleanUp Jobs happening so the Alert needs only to fire if value is between 0 and ..( 2 Days ) i think

**Describe alternatives you've considered**
We need to move the Calculation of "Days until Full" additional to new SQL Stored Proc and call this alerting proc in SQL Agent each hour.. maybe in the same JOB where the IO Data collected.
(SQLWATCH-LOGGER-DISK-UTILISATION) or in a new (SQLWATCH-ALERT) or so.. 

for developing:
we can take a look to 
exec sys.sp_check_log_shipping_monitor_alert  ... so here we get from one proc different error/alert outputs.

**Comment by marcingminski** [comment]
Yes good idea. I have alerting planned in the near future. I was thinking a new job, I like your suggestion SQLWATCH-ALERT with couple of new tables for ALERT RULES and config. The Rules table will contain rules or even an SQL code to run and if this returns an output it will be passed to the email queue for sending. This is just in my head so may change when I sit down to design it.

**Comment by marcingminski** [comment]
Hi, A lot has changed in version 2.x. There is now 2.2 beta available: https://github.com/marcingminski/sqlwatch/tree/2_2_beta which has custom alerting and reporting and I believe will fulfill what you were asking for. You are welcome to test it.
