### ISSUE TITLE
[Install-DbaSqlWatch] DACPAC failed ... Cannot bind argument to parameter 'Path' because it is an empty string.

### ISSUE THREAD

**Issue by jarole** [marcingminski/sqlwatch#78]
**Describe the bug**
Installation using dbatools from local file fails. I am using the following command:
```
PS C:\SQLwatch> Install-DbaSqlWatch -SqlInstance ABChostname123 -Database SQLWATCH -LocalFile sqlwatch-master.zip
```
I got this error:
```
WARNING: [15:15:31][Install-DbaSqlWatch] DACPAC failed to publish to SQLWATCH on ABChostname123. | Cannot bind argument to parameter 'Path' because it is an empty string.
```

**Windows Server (please complete the following information):**
 - OS Version: [Windows 2016 ]

**SQL Server (please complete the following information):**
 - SQL Version: [SQL Server 2016 SP1]
 - SQL Edition: [Standard]
 

**SQLWATCH version (from DACPAC or from sysinstances)**
- latest , recently downloaded master and development, the same behavior

**Comment by marcingminski** [comment]
Hi, thanks for raising this. Can I suggest you raise it on the dbatools GitHub as this was developed by the community.

**Comment by jarole** [comment]
thanks for checking
https://github.com/sqlcollaborative/dbatools/issues/5130
