### ISSUE TITLE
Installation fails, when changing isolation level and collation conflict when creating sp_sql_perf_mon_logger ...

### ISSUE THREAD

**Issue by jarole** [marcingminski/sqlwatch#79]
I am facing this issue right now. If anybody has some idea meanwhile, please let me know, perhaps it speed up my investigation.

**Describe the bug**
Offline installation using dbatools fails, with the following error:
```
Error SQL72014: .Net SqlClient Data Provider: Msg -2, Level 11, State 0, Line 0 Execution Timeout Expired.  The timeout
 period elapsed prior to completion of the operation or the server is not responding.

 Error SQL72045: Script execution error.  The executed script:
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION ON;
    END
```

**To Reproduce**
```
Install-DbaSqlWatch -SqlInstance MYSERVER -Database SQLWATCH -LocalFile SQLWATCH_1.3.3.zip
```

**Expected behavior**

**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: [Windows 2016]

**SQL Server (please complete the following information):**
 - SQL Version: [SQL Server 2016 SP1]
 - SQL Edition: [ Standard]
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - 1.3.3
 
**Additional context**
I am working on it, but if you have some hint , please let me know.

**Comment by jarole** [comment]
Seems like [SQL Server 2016 bug](https://social.msdn.microsoft.com/Forums/en-US/60065789-6972-4bf4-b1bd-123967a1db83/enaling-allowsnapshotisolation-hangs-in-sql-2016?forum=sqldatabaseengine)

The DACPAC installation (manual with SQL Studio, or ) hangs on ALTER DATABASE command (ENABLE_VERSIONING wait type)

```
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'SQLWATCH')
    BEGIN
        ALTER DATABASE [SQLWATCH]
            SET ALLOW_SNAPSHOT_ISOLATION ON;
    END
```
![obrazok](https://user-images.githubusercontent.com/38654035/53636330-1de9ea80-3c20-11e9-8db3-26e69870b2b7.png)

![obrazok](https://user-images.githubusercontent.com/38654035/53636347-2f32f700-3c20-11e9-96fa-d362cb412c7b.png)

**Comment by jarole** [comment]
To find  a workarround I've disabled server audit in SQL Server. Installation does not hang on `ALTER DATABASE [] SET ALLOW_SNAPSHOT_ISOLATION ON;` anymore, but failed again with other - Collation related reasons:

**PowerShell installation with dbatools**
```
WARNING: [12:57:08][Install-DbaSqlWatch] DACPAC failed to publish to SQLWATCH on DFGFK080. | Cannot convert value to type System.String.
```

**SQL Management studio .dacpac installation**

```
------------------------------
Could not deploy package.
Error SQL72014: .Net SqlClient Data Provider: Msg 468, Level 16, State 9, Procedure sp_sql_perf_mon_logger, Line 130 Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_CI_AS" in the like operation.
Error SQL72045: Script execution error.  The executed script:
CREATE PROCEDURE [dbo].[sp_sql_perf_mon_logger]
AS
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
DECLARE @product_version AS NVARCHAR (128);
DECLARE @product_version_major AS DECIMAL (10, 2);
DECLARE @product_version_minor AS DECIMAL (10, 2);
DECLARE @sql_memory_mb AS INT;
DECLARE @os_memory_mb AS INT;
DECLARE @memory_available AS INT;
DECLARE @percent_idle_time AS REAL;
DECLARE @percent_processor_time AS REAL;
DECLARE @date_snapshot_current AS DATETIME;
DECLARE @date_snapshot_previous AS DATETIME;
DECLARE @sp_whoisactive_destination_table AS VARCHAR (255);
DECLARE @sql AS NVARCHAR (4000);
SET @product_version = CONVERT (NVARCHAR (128), serverproperty('productversion'));
SELECT @product_version_major = substring(@product_version, 1, charindex('.', @product_version) + 1),
       @product_version_minor = parsename(CONVERT (VARCHAR (32), @product_version), 2);
SELECT @sql_memory_mb = CONVERT (INT, value)
FROM   sys.configurations
WHERE  name = 'max server memory (mb)';
I
 (Microsoft.SqlServer.Dac)
------------------------------
```

Database SQLWATCH has been created, some tables are inside.
**Database collation** is `SQL_Latin1_General_CP1_CI_AS` 
**Server collation** is `Latin1_General_CI_AS`

**Comment by marcingminski** [comment]
Hi, this is MSSQL bug actually, I have seen it happen multiple times with different dbs where audit was enabled. Not a SQLWATCH error but I will make a note in the docs about it. 

The collation problem is documented already.

**Comment by jarole** [comment]
https://github.com/marcingminski/sqlwatch/issues/30

**Comment by jarole** [comment]
https://github.com/marcingminski/sqlwatch/issues/75

https://sqlwatch.io/docs/known-issues-and-limitations/collation-conflict/
