### ISSUE TITLE
investigate potential warning/error on servers with master/target agents

### ISSUE THREAD

**Issue by marcingminski** [marcingminski/sqlwatch#81]
This was raised over at slack channel but the user confirmed his MSX/TSX setup wasn't actually working. Nevertheless, I need to test SQLWATCH deployments with MSX/TSX
![image](https://user-images.githubusercontent.com/8288333/54035165-a3d1dc80-41b0-11e9-938a-abaaf0716e32.png)

**Comment by MikeyBronowski** [comment]
What exactly needs to be done? Can you please provide all the necessary commands and tasks and requirements? :)

**Comment by marcingminski** [comment]
Someone mentioned they had problem installing SQLWATCH on a server with master/slave agents. It looked to me like there was an issue with the MSX/TSX config on that box (screen above) rather than SQWATCH issue but needs testing. Thought you may already have the env setup it would save me some time :). if you could install SQLWATCH on a server with master and then slave agents that would be enough: `Install-DbaSqlWatch -SqlInstance YourSqlServer ` . Thank you!

**Comment by MikeyBronowski** [comment]
Setup:
MSX: DC01\SQL2016
TSX: DC01\SQL2014

![image](https://user-images.githubusercontent.com/13431760/68705961-e8efaf00-0586-11ea-997a-13d72e52369c.png)


<# Installing on a master (MSX)
PS C:\Users\Administrator> # Installing on a master (MSX)
Install-DbaSqlWatch -SqlInstance 'DC01\SQL2016'

ComputerName : DC01-SQL2016
InstanceName : MSSQLSERVER
SqlInstance  : DC01-SQL2016
Database     : SQLWATCH
Status       : (Complete)
#>
![image](https://user-images.githubusercontent.com/13431760/68705940-df664700-0586-11ea-901b-08cb3545b18c.png)


<# Installing on a target (TSX)
PS C:\Users\Administrator> # Installing on a target (TSX)
Install-DbaSqlWatch -SqlInstance 'DC01\SQL2014'

ComputerName : DC01-SQL2014
InstanceName : MSSQLSERVER
SqlInstance  : DC01-SQL2014
Database     : SQLWATCH
Status       : (Complete)
#>
![image](https://user-images.githubusercontent.com/13431760/68705927-da08fc80-0586-11ea-9e68-8afc40c71d09.png)

**Comment by marcingminski** [comment]
Thank you sir!
