### ISSUE TITLE
SQLWATCH Dashboard 2.0 Beta 3 Instalation failed on PowerBI

### ISSUE THREAD

**Issue by julioback** [marcingminski/sqlwatch#83]
Downloading the powerBi dashboard 2.0 beta 3 and setting up and the following the recommended steps (change ref_servers), in the results, we have some errors in the results:

![image](https://user-images.githubusercontent.com/29488069/54295752-6a271a00-4592-11e9-99f9-c552c94bc3ac.png)

View de Applied Steps, the error it's always in invoking custom function.
![image](https://user-images.githubusercontent.com/29488069/54295827-8c209c80-4592-11e9-9566-2d7190ecd5a4.png)

![image](https://user-images.githubusercontent.com/29488069/54295852-9773c800-4592-11e9-9e64-852f07b0f727.png)

![image](https://user-images.githubusercontent.com/29488069/54295867-9e9ad600-4592-11e9-88ca-37efa5df0538.png)

But, looking the mentioned function, she is ok.
![image](https://user-images.githubusercontent.com/29488069/54296010-df92ea80-4592-11e9-9b22-12bced5fa721.png)

Gratz.

**Comment by marcingminski** [comment]
Hi, did you upgrade the database? This error could be also caused by PBI security, did you try "refresh all" from Power Query? Alternatively, you could try clicking the "Advanced editor" and then OK to re-save the query. This is known PBI problem also explained here: https://www.excelguru.ca/blog/2015/03/11/power-query-errors-please-rebuild-this-data-combination/

**Comment by julioback** [comment]
Hi Marcin, yes, i tried to update de database, but returned some erros

ref_report_title
Load was cancelled by an error in loading a previous table.
ref_servers
Load was cancelled by an error in loading a previous table.
Server Group
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Server Info
Load was cancelled by an error in loading a previous table.
Wait Statistics
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Performance Counters
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Database
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Time Intervals
OLE DB or ODBC error: Query 'Time Intervals' (step 'AutoRemovedColumns1') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination..
Process Memory
Load was cancelled by an error in loading a previous table.
Memory Clerks
OLE DB or ODBC error: Query 'Memory Clerks' (step 'AutoRemovedColumns1') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination..
File Statistics
Load was cancelled by an error in loading a previous table.
XE Query Waits
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
XE Query Processing
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
XE IO Subsystem
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
ref_percentage_rage
Load was cancelled by an error in loading a previous table.
File Statistics Sankey
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
File Statistics Sankey Stage
Load was cancelled by an error in loading a previous table.
ref_wait_stat_category_mapping
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Performance Counters Database
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
ref_metric_description
Load was cancelled by an error in loading a previous table.
Schedulers
Load was cancelled by an error in loading a previous table.
Missing Indexes
Load was cancelled by an error in loading a previous table.
Disk Utilisation DB
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
Disk Utilisation OS
OLE DB or ODBC error: Query 'Disk Utilisation OS' (step 'AutoRemovedColumns1') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination..
Last Snapshot
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
ref_perf_counters_poster
Load was cancelled by an error in loading a previous table.
Quick download server list
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
ref_quick_download
Load was cancelled by an error in loading a previous table.
Invoked Function
Load was cancelled by an error in loading a previous table.

And the link isn't working. Thanks

**Comment by marcingminski** [comment]
Can you tell me what errors you encountered during database upgrade and the SQL version please? The link works for me, perhaps it’s blocked by your corporate firewall?

**Comment by marcingminski** [comment]
Hi, I have since found out that this error can be caused by privacy settings in PBI. Can you please disable privacy options in PBI and report back?

![](https://sqlwatch.io/wp-content/uploads/2019/03/SQLWATCH_PBI_Privacy.jpg)
