### ISSUE TITLE
DBA-PERF-LOGGER fails with PK Violation

### ISSUE THREAD

**Issue by rafaelcuesta** [marcingminski/sqlwatch#89]
Job DBA-PERF-LOGGER fails with the following error:

[...]Violation of PRIMARY KEY constraint 'pk_logger_xes_waits'. Cannot insert duplicate key in object 'dbo.logger_perf_xes_waits'. The duplicate key value is (Mar 25 2019  3:54PM, Mar 25 2019 10:03AM, LATCH_SH, 203).[...]The step failed.

Occurs when XE logs multiple identical values:

![image](https://user-images.githubusercontent.com/49949288/56676950-c1da9a00-6695-11e9-8dbf-de887264c3e7.png)

Windows 2012 R2 x64
SQL Server 2016 ENT SP1 
SQLWatch          1.3.6967.36446

**Comment by alexander-suprun** [comment]
It looks like this issue has been fixed in the last beta, but then there is another issue. It fails with an error: cannot insert NULL into activity_id column. That's because it relies on TRACK_CAUSALITY to be enabled and it's not for the default system_health session.

**Comment by marcingminski** [comment]
Good point. I’ll have a look but worried I’m running out of ideas for the primary key here. I may have to add surrogate key.

**Comment by alexander-suprun** [comment]
You only need a natural key just to avoid loading the same data twice, right? I would say simply load the records that have older timestamp than the last loaded, and for the key just use surrogate. The chances of getting a new record with the exactly the same timestamp when you are reading from XE session are slim to none. By the way, XE timestamp is in UTC, are you converting it into local time in Power BI?

**Comment by marcingminski** [comment]
This should have closed with the referencing commit, not sure why it did not.
