### ISSUE TITLE
2.0Beta6.2 Get-WMIObject Win32_Volume Wrong table reference

### ISSUE THREAD

**Issue by FrenchDataWizard** [marcingminski/sqlwatch#96]
When redeploying 2.0Beta6.2 freshly, step Get-WMIObject Win32_Volume of job SQLWATCH-LOGGER-DISK-UTILISATION crashes because it is referencing [sql_perf_mon_snapshot_header] which was renamed into [sqlwatch_logger_snapshot_header]

**To Reproduce**
1. Clean install Beta6.2
2. Run the SQLWATCH-LOGGER-DISK-UTILISATION job
The error is "The error information returned by PowerShell is: 'Invalid object name 'dbo.sql_perf_mon_snapshot_header'.  Invalid object name 'dbo.sql_perf_mon_snapshot_header'."
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - Fresh Beta6.2 setup via manual DACPAC deployment

**Comment by FrenchDataWizard** [comment]
Was going to submit a fix but saw it was ready in Beta7. At least people will know to wait.

**Comment by marcingminski** [comment]
Hi, thanks. This was fixed in beta 7, https://github.com/marcingminski/sqlwatch/commit/603dddd4decc2893f130651d5f5336c51c88e086. Although beta 7 is still work in progress, you are welcome to have a play. I will keep this open for visibility.
