### ISSUE TITLE
partition_number must be part of the PK

### ISSUE THREAD

**Issue by conradg69** [marcingminski/sqlwatch#98]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**
Getting the following error from step 2 of the Index SQL job 

"Msg 2627, Level 14, State 1, Line 1
Violation of PRIMARY KEY constraint 'pk_index_usage_stats'. Cannot insert duplicate key in object 'dbo.logger_index_usage_stats'. The duplicate key value is (May  4 2019  5:31PM, FINDWH, dbo.factBookingSCD_NTJ, 1).'

This is a screenshot of the index in question.

![Index](https://user-images.githubusercontent.com/36333522/57185579-40b9a900-6ec6-11e9-8556-031286af88ab.png)

**To Reproduce**
1. Setup SQLWatch on SQL Server 2016 instance
2. Run the Index job

After our discussion on SLACK, I've attached the scripts you asked me to run and the results are in the spreadsheet also attached.  
[scripts.zip](https://github.com/marcingminski/sqlwatch/files/3144926/scripts.zip)
 [Results.xlsx](https://github.com/marcingminski/sqlwatch/files/3144922/Results.xlsx)

The results for Sheet 1.sql are on sheet 1 etc.

 Also here is a copy of the index referenced in the error message. 
[pk_index_usage_stats.zip](https://github.com/marcingminski/sqlwatch/files/3144929/pk_index_usage_stats.zip)

**Windows Server (please complete the following information):**
 - OS Version: [Windows Server 2012 R2 Standard]

**SQL Server (please complete the following information):**
 - SQL Version: [Microsoft SQL Server 2016 (SP1-CU10-GDR) (KB4293808) - 13.0.4522.0 (X64) ]
 - SQL Edition: [Developer Edition (64-bit)]
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - Microsoft SQL Server Management Studio						14.0.17224.0
Microsoft Analysis Services Client Tools						14.0.1016.244
Microsoft Data Access Components (MDAC)						6.3.9600.17415
Microsoft MSXML						3.0 5.0 6.0 
Microsoft Internet Explorer						9.11.9600.19301
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.9600:
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - beta 3.0.0.0
 
**Additional context**
This was the last message you sent me in the SLACK message just for reference :

"it is the partition: partition_number
1
2
3
4
5
6
19
20
21
13
14
15
16
17
18
7
8
9
10
11
12

can you please raise a bug on github
I will address this in the next version
partition_number must be part of the PK"

**Comment by marcingminski** [comment]
fixed in 8184ca0a65300c3a7095bb9cb28a8bc4345562ab
