### ISSUE TITLE
PowerBI - No SQL Instance filter on  WhoIsActive page

### ISSUE THREAD

**Issue by conradg69** [marcingminski/sqlwatch#99]
**Did you check DOCS to make sure there is no workaround?**
https://sqlwatch.io/docs/

**Describe the bug**
When monitoring multiple SQL Instances, there's no filter on the "Who Is Active" page. 

**To Reproduce**
1. Setup PowerBi report for multiple SQL Instance
2. Select the the "Who Is Active" page. 

**Expected behavior**
With multiple SQL Instances you need to be able to see just the transactions for just the Instance required. 

**Screenshots**

![SQL Instances](https://user-images.githubusercontent.com/36333522/57302728-c0689300-70d3-11e9-83cd-b683565e1a20.png)

**Windows Server (please complete the following information):**
 - Windows Server 2012 R2

**SQL Server (please complete the following information):**
 - N/A
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - N/A
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 - Beta 3.0.0.0
 
**Additional context**

**Comment by marcingminski** [comment]
fixed in 711f56745df20bef04b50fc7a1261d792f87b67f
